### ISSUE TITLE
Translation ?

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#1]
Are you planning on translating the app in English ?
I could help to translate it later in French if you need.

**Comment by raulhaag** [comment]
ready

**Comment by Dostoi** [comment]
Which file contains the english translation (and where is it ? ^^) ?
I want to translate it but can't find it (I don't have any coding knowledge)

**Comment by raulhaag** [comment]
https://github.com/raulhaag/MiMangaNu/blob/master/MiMangaNu/res/values/strings.xml
there is the list of string

**Comment by Dostoi** [comment]
thanks !

**Comment by Dostoi** [comment]
Don't know if you've heard of transiflex (https://www.transifex.com/). It could help translate the app. Open source project don't have to pay and people with no coding knowledge can help too thanks to the way the site work.
I can set things up if you want
