### ISSUE TITLE
Set scroll sensivity

### ISSUE THREAD

**Issue by lenisko** [raulhaag/MiMangaNu#106]
Option allowing to set scroll sensivity would be great. When reading 4koma it just hurts to swipe.

**Comment by Johndeep** [comment]
Hmm, how do you imagine this? Something like scrolling 2x, 4x and so on?

**Comment by lenisko** [comment]
Thanks for your reply.
Yes exactly!

Just little slider in options which allow using multiplier to scroll, starting from
x1 - which is default right now to idk... x3 ?

**Comment by raulhaag** [comment]
testing and is posible just need to add and option on config perhaps

**Comment by Johndeep** [comment]
You already have this feature ready?

**Comment by raulhaag** [comment]
Only need to add options and preference

**Comment by raulhaag** [comment]
commited for next version :wink:

**Comment by lenisko** [comment]
thanks, I will close after test ;)

**Comment by Johndeep** [comment]
Uhm, @raulhaag, did you forget the implement "setScrollFactor" correctly?
I made a fresh fork and encounter this problem: "Error:(626, 18) error: cannot find symbol method setScrollFactor(float)"

**Comment by raulhaag** [comment]
forget to push the image library change

**Comment by Johndeep** [comment]
By the way, max scroll factor is 15x? Seriously? Isn't that a **little too fast**? :sweat:
Isn't it also better if you can set the scrolling speed for each manga separately? Just asking.

**Comment by lenisko** [comment]
Okay, I have compiled from sources and its working well : )
But.. Option should enable enable only x 1,2,3 more is not usable == unneeded.

**Comment by Johndeep** [comment]
Nice one! Another one who can give early feedback :+1: 
Well, I also thought more than 4 is strange, but well. Always fixable.

Can you elaborate what you mean with "weird list of choices"?

**Comment by lenisko** [comment]
well normal list is not 'editable' this one is, while choosing value I can change it to idk... 'A' ?

**Comment by Johndeep** [comment]
You mean the number picker, right? Well, that's a feature of android (not mine) that you can enter different numbers by tapping on that, but the entered word/number has to be in the list.

The picker widget has this ability for you, if you i.e. want to "jump" to 354 of 1000, that would be much easier than just scroll until that number. Furthermore, if the list doesn't have words, you shouldn't be able to enter "A" or other letters.

**Comment by lenisko** [comment]
Slider would be better choice, you can't crash application with it ;)
Also values 1..3 are best, more is unneded.

**Comment by Johndeep** [comment]
Hmm, are you sure that you really can enter something like "A"? I think not.

**Comment by lenisko** [comment]
Ohh... Sorry, you are right.
But still slider is better option.

**Comment by Johndeep** [comment]
Hmm, let me state some things about a simple dialog for choosing numbers.

* First, I notice that the number picker are somehow really small in height, I didn't expect it to be that narrow. So I will probably get rid of the number picker.
* Next, personally I think sliders are not very accurate, especially at really big ranges. _But_ for the scroll sensitivity this could work, because it would be great if you can set something like 1.5 or 2.2 right?
* Lastly, maybe I should reintroduce a list chooser, but with a message or summary, which will be much clearer and cleaner. (If you only need something between 0 and 5, but only whole numbers, then a number picker or slider are inappropriate or just overkill, I think)

Yeah, these are small problems, but well, if it's solved properly, then we can tackle more difficult problems. I'll tell you, when I'm finished with these.

**Comment by Johndeep** [comment]
Jo, I have really thought about this hard and came to a conclusion:
I've made the SeekBar Dialog, which can be used just like NumberPicker. I've in mind to use this like this, for non numerical values (i.e. Names), use List, for values at least 4 and up to 30 at most, use SeekBar, and everything over 30+, use NumberPicker.

This is only a small issue, but yeah, I also fixed the range of scroll sensitivity to 1 up to 4.

If you like to try this out, take a look at my fork.

**Comment by Johndeep** [comment]
By the way, even if the main issue is solved, I've made those improvements mentioned above in my fork (hopefully this will also be merged soon). And yeah, I agree, for small ranges slider are really nice.

**Comment by lenisko** [comment]
gj, now lets wait for raulhaag.
I'm still using 1st commit, and reading on x2 is just perfect.

**Comment by raulhaag** [comment]
now i'm here :-P 
i go to merge john commit now and test and if a have time go to add this feauture by manga (leave this generel as deafault)

**Comment by lenisko** [comment]
it's fine as general imo... too much pain to change it in manga settings.

**Comment by raulhaag** [comment]
check the last commit

**Comment by lenisko** [comment]
Im so proud of you guys ; )
Good job
