### ISSUE TITLE
Old chapter keep downloading as new

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#111]
I've got an issue with the new version (1.34)
With this manga http://kissmanga.com/Manga/Gigi-Goegoe, when I check for new chaper, old chapter keep being added and shown as new

**Comment by raulhaag** [comment]
my bad replace the character whith "-" not "" i go to check if work this way

**Comment by raulhaag** [comment]
no the problem, i see triplicated like in kissmanga page 
Gigi Goegoe Ep. 092 - The Dream-sharing Stone (Part004)	8/26/2015
Gigi Goegoe Ep. 092 - The Dream-sharing Stone - Part004	9/2/2015
Gigi Goegoe Ep. 092 - The Dream-sharing Stone - Part 004	9/2/2015
and testing deleting chapters and find again work, more information please :pray:

**Comment by Dostoi** [comment]
I didn't notice there was an issue with kissmanga too.
My issue is I keep getting new chapter every time I check for update but only two or three at a time.
It goes from chapter 81 to the last one.
But I think it's mostly an issue with kissmanga and I don't know what happened to this manga ^^

**Comment by Dostoi** [comment]
After updating multiple time, it seems to be good. It's probably an issue with kissmanga

**Comment by Dostoi** [comment]
Closing as it is a kissmanga issue
