### ISSUE TITLE
Markbox of "hide already seen" is not visible

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#114]
The markbox (don't know how to call it exactly ^^) of the hide already seen option in not visible

**Comment by Johndeep** [comment]
Hmm, really? I just notice the sprite gets a little bigger..

**Comment by raulhaag** [comment]
i don't know about you two are talking :open_mouth:

**Comment by Johndeep** [comment]
Uhum.. @Dostol do you by any chance mean the hide/unhide button in the overview between the settings and the downloads button?

**Comment by Dostoi** [comment]
Yes this one, the phrase is here but the cross isn't (and the square neither)

**Comment by Johndeep** [comment]
Okay, next question, how is it "not visible"? Do you mean the entire symbol is missing (invisible), are there scaling glitches, or what exactly is about the "phrase"?

To be honest, a screenshot (optionally with some marking) would tell us right away what's wrong though.

**Comment by Dostoi** [comment]
Ho yeah my bad, I don't know why I didn't think about a screenshoot from the start
![screenshot_2015-09-03-21-32-37](https://cloud.githubusercontent.com/assets/7694864/9668756/b4d24ff8-5283-11e5-975c-f34153f17180.png)

**Comment by Johndeep** [comment]
Ahh.. somehow in your case you normally have the three dot menu, right?
I thought raulhaag placed all the symbols on the titlebar altogether..
![what_i_mean_about_the_menu](https://cloud.githubusercontent.com/assets/306953/9669322/8a41e9d0-5286-11e5-8a96-88e1691a4848.png)

So, I want to do more such improvements.

**Comment by Johndeep** [comment]
This would also improve the look for smaller screen I think, but sorry for not considering it beforehand.

**Comment by Johndeep** [comment]
Maybe I'll even get rid of the checkbox and instead replace the text with "Hide already read" and "Show everything" or something like that.

**Comment by Dostoi** [comment]
I've never had the first one.
Is the checkbox is such a bother you can get ride of it and replace it by hide already read and unhide already ride. I think having "already" will help with the confusion
I personally prefer to have the download in the title bar ^^, but it's not really important.

**Comment by Johndeep** [comment]
So menu becomes like 1.31 and before, nice shot in my own foot I say..

But okay, I can't complain, the old layout were really better..

**Comment by Johndeep** [comment]
By the way @Dostol, are you able to compile and send the app per adb (with Android Studio it's the easiest) into your phone for testing or do you want to just wait for release in f-droid?

**Comment by Dostoi** [comment]
I can't, I've never tried but it could be nice to test the app and give feedback faster. Is it hard to set up ?

**Comment by Johndeep** [comment]
Depending how much knowledge you have, it can be easy or difficult.
To not spoiler you, try to learn about the Android Studio IDE.
_One hint is, that you will have to download around 2 GB in total (IDE and SDK for Android), which is why you have to be patient at least._

If you think that you're not ready, don't sweat, at least we **get** the feedback, a little late is never bad ;P

**Comment by Dostoi** [comment]
ok, I'll try ^^

**Comment by Dostoi** [comment]
Work now
