### ISSUE TITLE
About Reading Mode  

### ISSUE THREAD

**Issue by scaPEGoatno** [raulhaag/MiMangaNu#119]
Vertical Reading Mode:Scroll down from top (the images fit width)
![screenshot_2015-09-04-20-33-41](https://cloud.githubusercontent.com/assets/11935355/9683798/fca617b6-5345-11e5-9b55-0b93304bd7f6.png)

**Comment by Dostoi** [comment]
Is it normal if I don't have the same thing as this at all ?

![screenshot_2015-09-04-14-52-59](https://cloud.githubusercontent.com/assets/7694864/9683956/c841d75c-5314-11e5-9489-05d6fb615bb2.png)

**Comment by Johndeep** [comment]
Hmm.. I also think transparent dark is better for the eyes.. or what exactly is the problem?

**Comment by scaPEGoatno** [comment]
The layout is listview  or  recyclerview  Scroll down from top  not left to right

**Comment by Johndeep** [comment]
If you want to read by scrolling from the top down, you have to click on this button:
![vertical_read_mode_button](https://cloud.githubusercontent.com/assets/306953/9684306/07815b2a-5317-11e5-85fb-9dbece707d52.png)

**Comment by raulhaag** [comment]
closed, reopen if it's necesary
