### ISSUE TITLE
can you fix the problem with the submanga server?

### ISSUE THREAD

**Issue by xken2x** [raulhaag/MiMangaNu#126]
the app work fine less in the submanga server.
when i open submanga, the app only change and dont show anything, and when i press in search the app crash, the submanga server is my favorite server, and i look for use in this app, excuse me if i cant fix the problem now, beacuse i dont learn the necesary to do this.

**Comment by raulhaag** [comment]
submanga volvió a una versión anterior de su pagina lo que es bueno y puedo dar un mejor soporte pero ahora estoy programando una vista para que la lectura en celular sea mas cómoda y tratando de que consuma la menor cantidad de memoria posible, esta cerca de estar por salir pero lleva tiempo y mas al ser hecha desde 0, pero ni bien termine con esto, prometo restablecer el soporte a submanga si sigue con la pagina como ahora antes de lanzar la próxima version

**Comment by raulhaag** [comment]
![image](https://cloud.githubusercontent.com/assets/2048339/10396245/da0a3e4c-6e77-11e5-9fca-ba73c3222a8f.png)
todavía no esta funcionando el listado de series hay que esperar
http://submanga.com/series/g
http://submanga.com/series/n
si ves que empiezan a funcionar avisame

**Comment by xken2x** [comment]
bro, creo que te diste cuenta de que hablo español, y yo pensaba que se me entendia el ingles XD.
bueno estaria feliz de ayudarte con el server de submanga, y de paso bato.to, pero la uni y el trabajo de medio tiempo me tienen sin tiempo, aunque en diciembre podria ayudarte, ¿aceptarias a un colaborador?

**Comment by raulhaag** [comment]
el app siempre esta abierta a colaboraciones ;-), ademas yo hablo español y a veces ne me explico tan bien en ingles, submanga si estaría funcionando bien seria simple, pero bato.to cada vez mas complicado lo veo y con la cantidad de reclamos que tiene y están dando de baja mas lejos lo veo

**Comment by raulhaag** [comment]
submanga esta listo para la próxima version

**Comment by xken2x** [comment]
bueno, creo que cuando termine este semestre instalo las 2 gb del Android Studio y te hecho una  mano con la app.
Por cierto, hay un error bastante extraño en el cual las portadas desaparecen cuando se hace scroll a traves de la pagina principal, ademas de que cuando se acaba el tiempo de espera del servidor, en lugar de devolverte a la pagina principal, la app se crashea y reinicia,

**Comment by xken2x** [comment]
por cierto, ¿como hiciste con submanga si aun no arreglan el problema con las categorias?

**Comment by raulhaag** [comment]
use esta lista http://submanga.com/series
acerca del tiempo de espera en que parte es que pasa

**Comment by raulhaag** [comment]
Lo de las imagenes me pasaba solo en el emulador pense que era un problema del mismo pero ahora veo que es un problema de la clase recicle view que no llama siempre al onbind asi que estoy volviendo al gridview que lo hace bien con viewHolders

**Comment by raulhaag** [comment]
cierro cualquier cosa reabrilo
