### ISSUE TITLE
Having beta/alpha release

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#129]
As you asked for help to test the app, I was thinking that it may be a good idea to have beta/alpha (call it like you want) release.
This way people will know that it's buggy but can easily help you.
Kind like what F-droid is doing with it's app. Look at it in the f-droid app. It's written 0.97-alpha6 for the last one.

**Comment by raulhaag** [comment]
i don't know how but i go to test this last commit for 2 days more and if go ok go to release

**Comment by Dostoi** [comment]
Ok no problem

**Comment by aharish** [comment]
@raulhaag you can use build flavors in Gradle to have beta or alpha releases. You can create milestones or whatever you want to call it or release candidates. 

Checkout the Gradle files at http://github.com/plafue/writeily-pro for an example

**Comment by null-dev** [comment]
I can integrate travis-ci into this and add auto-publishing to a server every commit. Then you have a build every commit anyone can download and test?

**Comment by raulhaag** [comment]
added releases 
https://github.com/raulhaag/MiMangaNu/releases

**Comment by raulhaag** [comment]
http://cirelease.nulldev.xyz/mmn-build
travis ci releases
