### ISSUE TITLE
Hide from gallery

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#13]
What does it do ?

**Comment by raulhaag** [comment]
prevent downloaded images to be diplayed on android gallery creating ".nomedia" file on mimanganu directory

**Comment by Dostoi** [comment]
it have to be selected before downloading or is it supposed to work after too ?
Because selecting it doesn't hide the images

**Comment by raulhaag** [comment]
is not in real time because android make an scan finding images whe it found .nomedia file android skip the folder, check if (sdcard)/MiMangaNu/.nomedia exist (is hidden becuase start whit . ) and if was created whiout a problen next scan of android for gallery the images should be hidden

**Comment by Dostoi** [comment]
it works, thanks for the help.
Why not making it the default state ?
