### ISSUE TITLE
Theme.AppCompat not theming status bar on Lollipop

### ISSUE THREAD

**Issue by aharish** [raulhaag/MiMangaNu#130]
Issue can be resolved by adding android: colorPrimaryDark resource attribute in values-v21/styles.xml and colorPrimaryDark attribute in values/styles.xml (to maintain backward compatibility. 

I'll send in a pull request to fix this later on

**Comment by raulhaag** [comment]
Reading about it i think is e good way use Window.setStatusBarColor() and Window.setNavigationBarColor() checking api before

**Comment by raulhaag** [comment]
ready for next version using the custom colors from settings

**Comment by aharish** [comment]
Yeah, I saw the code after I opened the issue yesterday... 😅 Seems like using the `Window.setStatusBarColor()` is the best way. I was able to set it using the primary color that users set, but I have had trouble dynamically generating 700 value colors on the go rather than having a predefined set on hand. Guess I'll go with the predefined set. Has this been added already?

**Comment by raulhaag** [comment]
check this https://github.com/fireflight1/mcg/blob/master/scripts/controllers/color_generator.js

**Comment by raulhaag** [comment]
jhondeep commited this for ligther https://github.com/raulhaag/MiMangaNu/blob/master/app/src/main/java/ar/rulosoft/mimanganu/utils/ThemeColors.java

**Comment by raulhaag** [comment]
don't worry, ready statusbar color - 700

**Comment by Johndeep** [comment]
Nice ^^, now the reader really gets better and better!

**Comment by raulhaag** [comment]
closing, reopen if it's necesary
