### ISSUE TITLE
Manga have 2 different option button/menu

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#133]
With the last version, mangas have 2 different option button, they're next to each other, one with the previous menu and one with only direction.

PS: the new vertical reader is perfect, really smooth and all, great job !

**Comment by raulhaag** [comment]
more details about where

**Comment by Dostoi** [comment]
![screenshot_2015-10-25-23-24-50](https://cloud.githubusercontent.com/assets/7694864/10718428/be031ce8-7b72-11e5-8532-fdf3249703cd.png)

**Comment by Johndeep** [comment]
What does the round dots contain? Because it could be happen due a menu config, where android automatically wrap up the menu, if there is no space (too small screen i.e.).

But I assume this is resolved in 1.37, hopefully?

**Comment by Dostoi** [comment]
The round dots only contain a menu with direction written in it (don't know if it's the french or the english string)
Nope, it's only since 1.37 ^^ But I didn't try the 1.36

**Comment by Johndeep** [comment]
Ah! I see, okay, it seems that I made a little mistake at my latest commit, done, just revert this.

**Comment by Johndeep** [comment]
By the way @raulhaag, can you check, if we need **res/menu/activity_manga**? Because **res/menu/view_chapter** is almost the same.

**Comment by Dostoi** [comment]
Don't worry, it's fine ;)

**Comment by raulhaag** [comment]
@Johndeep it's the old description activity menu

**Comment by Johndeep** [comment]
@raulhaag Okay, just asking, I just leave it there.

By the way, my fix should be merged now, leave a feedback, if new version is released.

**Comment by raulhaag** [comment]
@Johndeep, your fix merged, deleted the xml and the old color picker, if this weekend have time i go to finish the others new readers ;-)

**Comment by Johndeep** [comment]
Nice! Less code be be worried about ;P
