### ISSUE TITLE
Some manga don't have genre

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#134]
Some manga who should have a genre don't have any. I'm only using kissmanga so I can't tell about the other website.
Deleting and redownloading solve the issue so it's just to tell you about the issue.

**Comment by raulhaag** [comment]
just search for updates and the genre go to be updated

**Comment by Dostoi** [comment]
It doesn't work for all manga. But I don't know if you can really do something about it (and it's not really important) ^^

**Comment by raulhaag** [comment]
Tell me an example to test

**Comment by Dostoi** [comment]
Shards of sin from kissmanga.
But I tested readownloading another manga and it corrected the issue, so I'm not sure you can do anything about it

**Comment by raulhaag** [comment]
test on chapter list drag from top to find updates (i tested hello hellper and work fine)

**Comment by Dostoi** [comment]
Ho yeah, I didn't think to try like that since it worked for some from the main menu. Thanks ^^
