### ISSUE TITLE
Issue with the stay on and screen rotation icon

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#135]
If I use the physical option button when reading a manga, a menu appears where I can select to switch the screen rotation and sleep state.
If I use the stay on or off, the icon doesn't change and the same with the screen rotation (not for all state of the rotation) when I'm in this menu and after it doesn't change if I use the icon.
Leaving and coming back make the icon work again and change state if needed.

**Comment by raulhaag** [comment]
new reader or old?

**Comment by raulhaag** [comment]
don't worry now the menu button show  the bars

**Comment by Dostoi** [comment]
New reader.
yes but it doesn't update the icon when using the physical menu button.

**Comment by raulhaag** [comment]
now fisical menu button show and hide the actionbar and the page seek like when you presss on center
