### ISSUE TITLE
MangaHere, MangaFox - confirmed not working.

### ISSUE THREAD

**Issue by lenisko** [raulhaag/MiMangaNu#138]
Idk about rest, but they have changed something on websites.
Whole chapter is one small image of running thing ^>^

**Comment by raulhaag** [comment]
Ready for next version ;-)

**Comment by Dostoi** [comment]
I'm having the same issue with kissmanga. With trace 2.0 last chapter, it's only a small dog for every picture

**Comment by MadHalaster** [comment]
I can confirm I am also seeing this problem.

If you go to the main MangaHere page, you can see what is causing the problem directly.
Before every single page loads, they first do a pre-loading image of the walking teddy bear.

The app is just grabbing the teddy bear image now instead of the page that loads after.

**Comment by raulhaag** [comment]
@Dostoi  i just release the v1.38 fixing mangaPanda and Mangahere, but kissmanga looks good (tested whit trace)

**Comment by Dostoi** [comment]
Deleting and redownloading the manga fixed the issue so it's okay but strange ^^

**Comment by sm7297** [comment]
how do i download apk of 1.38

**Comment by lenisko** [comment]
@sm7297 you can compile it yourself, or wait for F-droid release.
You can always ask nicely, maybe devs configure autobuilds =)

**Comment by raulhaag** [comment]
I Think tomorrow F-droid go to publish, if i publish a release apk with not the same sign it go to delete your configuration data

**Comment by sm7297** [comment]
is there a way to add other manga websites

**Comment by raulhaag** [comment]
build is easy just download android studio and clone the repository, adding servers take more work on mantain and need to be compatible whit the structure of the app to do it easy

**Comment by MadHalaster** [comment]
I built it and installed the newest version onto my device. It is running fine, but it looks like the MangaHere issue has just changed. Instead of showing the Bear it now shows an image of a bunch of Shounen Jump characters and says "MangaHERE For Mobile."

**Comment by raulhaag** [comment]
@MadHalaster look like they still making changes :-(, but ready again check the las commit

**Comment by MadHalaster** [comment]
Thanks for the fix. :) 
Checked it out and verified it is working good.
