### ISSUE TITLE
Test Vertical Reader

### ISSUE THREAD

**Issue by lenisko** [raulhaag/MiMangaNu#139]
In my opinion, it's painfull to read with this thing activated. Yet, might be fine to read 4koma.
Consider setting it to false on default?

**Comment by raulhaag** [comment]
you can set it on config, you can change the default reading sense from settings for those mangas that not have been set

**Comment by lenisko** [comment]
mhm, I have tried this vertical, but it's hmm... making my head hurts ;P
maybe add some border between pages? optional.

**Comment by MadHalaster** [comment]
I really like this mode. Having read many Manhwa and webtoons that were already laid out like this, transitioning to reading Manga this way was super easy. Being able to just keep scrolling down with no flipping between pages is my preferred method. :D

**Comment by raulhaag** [comment]
that was the idea, by the way you can jump from page to page tapping on
left and right the screen

2015-10-30 21:35 GMT-03:00 MadHalaster <notifications@github.com>:

**Comment by lenisko** [comment]
@raulhaag 
indeed it's good for 4koma imo =)
but what do you thing about
when option is enabled allow user to set space between images from 0 % to 5% ? or something like that
