### ISSUE TITLE
Read directions are flipped

### ISSUE THREAD

**Issue by TheSniperFan** [raulhaag/MiMangaNu#140]
When you set the read direction to left-to-right the read direction becomes right-to-left and vice versa.
It's also not just a text issue, because the icon in the chapter view is wrong too.

**Comment by TheSniperFan** [comment]
Okay, this is more confusing than I thought.

Is it possible that when you say LTR, you mean that you move your finger from left to right? Because the icon looks that way and - at least as far as I'm aware - that's not how it works.
LTR means that the next page is always on the right, so you move from the leftmost page to the rightmost one -> you start at the left, you end at the right -> left-to-right.

I think LTR and LTR should indicate the order in which the pages occur and not the direction in which you swipe.

I started replacing your old icons with the new ones from Google and stumbled upon this. I'll wait before I do any further work.

**Comment by raulhaag** [comment]
that's a little confusing, but please do it if you're sure , about the icons if you want do it, i know i'm noot good on that

**Comment by TheSniperFan** [comment]
I'll simply create it during the next days. You'll be able to check it out when I make a pull request. If there will be something you don't like, simply tell me.

**Comment by TheSniperFan** [comment]
Shit! I completely forgot about this. I've had lots of other stuff to do recently.
Tell you what. Once I get around finishing this, I'll just create a pull request. Don't know when it'll be though.

**Comment by raulhaag** [comment]
ok don't worry
