### ISSUE TITLE
Kissmanga isn't working

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#143]
I can't access kissmanga anymore

**Comment by Johndeep** [comment]
I also can confirm this, but aww man.. what the heck happened with kissmanga again?
It seems that the new reader causes a "unable to resume activity" exception and the old reader would load even nothing!

**Comment by raulhaag** [comment]
@Johndeep  is the protection from cloudflare for D.O.S. attacks that was the reason for use ip in kissmanga
fixed and ready for next, but perhaps in few days they remove this protection

**Comment by Johndeep** [comment]
Ah okay, I just started to figure the script to generate the cookie (cf_clearance) ^^"
Sure they will remove the protection?

**Comment by raulhaag** [comment]
not sure but the version using they ip is ready

**Comment by Johndeep** [comment]
Well, IP is a dirty, but working way for now at least..

**Comment by Dostoi** [comment]
Thanks for the quickfixe
