### ISSUE TITLE
Kissmanga not working

### ISSUE THREAD

**Issue by sm7297** [raulhaag/MiMangaNu#144]
1.38 and also can you provide steps on how can i add other website to the application i have installed android studio but cant able to understand

**Comment by Dostoi** [comment]
With which version of the app ?

**Comment by Blapple** [comment]
Kissmanga is also not working for me on version 1.37 and 1.38, haven't tried any other versions.

**Comment by Dostoi** [comment]
Duplicate of #143 
Already fixed, just need to wait for the next version or compile yourself

**Comment by raulhaag** [comment]
ready on 1.39
