### ISSUE TITLE
tumangaonline dejo de funcionar

### ISSUE THREAD

**Issue by xken2x** [raulhaag/MiMangaNu#145]
ahora, tumanga online no permite descargar nada, deja abrir el catalogo de mangas, deja agregarlos, e incluso se puede buscar capitulos nuevos de los mangas agregados a este servidor, pero en el momento de descargar les sale error al cargar el capitulo, y no permite descargar nada, el problema es grave ya que practicamente todos mis mangas (100 aprox) estan en ese server

**Comment by raulhaag** [comment]
ya lo solucione para la proxima version

**Comment by xken2x** [comment]
mmm...
jajaja estaba histerico con ese error ya que sacaron cap nuevo de tokyo ghoul:re y no podia leerlo, por cierto para cuando hay proxima version?

**Comment by raulhaag** [comment]
tengo que terminar unas cosas antes y el trabajo me tubo ocupado asta el
fin de semana asi que capaz mañana termino eso y para el miercoles o jueves
estara la actualizacion de fdroid

**Comment by xken2x** [comment]
ok, todo el munndo tieenes sus propias ocupaciones, por cierto...
no deberias colocar un link de descarga directa en la pag de github para tener la apk recien salida del horno y asi no depender de f-droid?

**Comment by raulhaag** [comment]
si lo hago no perderian la configuracion actual no la db ya que esta en un directorio externo y tendrian que siempre bajarla de aca o sino al instalar la de fdroid perderian de nuevo su configuracion
