### ISSUE TITLE
Reader doesn't renember correctly the viewed pages

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#147]
With the new reader, if you go to a page (for example 10) and leave the chapter, the pages marked as read will be 9 and not 10
With the last build from 15min ago

**Comment by raulhaag** [comment]
if 1 pixel from page 8 is visible and all the page 9 its save 8

**Comment by Dostoi** [comment]
I used the scroll bar at the bottom to do thaht, it shouldn't do that while using this no ?

**Comment by raulhaag** [comment]
ok i found the problem ;-)

**Comment by Dostoi** [comment]
Thanks (for the thousand time I guess ^^)
