### ISSUE TITLE
Being able to hide manga with nothing to read

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#15]
Could you add an option to hide manga where there is nothing left to read ? (another filter sorry ^^)
Because right now there is a lot of manga and it's not easy to know which one has something to read or not

**Comment by raulhaag** [comment]
i dont think that usefull but i think show first mangas whith updates before search for it, that can be usefull?

**Comment by Dostoi** [comment]
Sorry I don't understand ^^
What do you mean by before search for it ?
Putting first manga with something to read ?

**Comment by raulhaag** [comment]
Last reared are first, now 1.08 when you check for updates those Mangas whit updates go to be showed first

**Comment by Dostoi** [comment]
What about old manga where everything is already published. They won't be getting any updates but there will still be something to read in them. Are they going to be at the top too ?
I think it's just a personnal preference to be able to see only manga with something to read. I guess it's because I read a lot of manga and it could be easier to see what to read and what not

**Comment by raulhaag** [comment]
When you read it, it go to top on list,  Manga whit no updates and no recent reads go to the end, try it open any Manga and  then press back and this is in the top

**Comment by Dostoi** [comment]
Yes I know. It just that I don't always read only one manga in one go and I have multiple manga with things left to read and as I don't renember which one I open every one and they all go to the top so the order isn't helping my case ^^
But it's ok don't worry

**Comment by raulhaag** [comment]
i go to test if is not an heavy querry, i don't promise anything.

**Comment by Dostoi** [comment]
Thanks, don't bother too much just for this :)

**Comment by raulhaag** [comment]
ready on 1.09 check it when aviable

**Comment by Dostoi** [comment]
Thanks a lot :)

**Comment by raulhaag** [comment]
1.09 is now avaible, check in overflow menu at start

**Comment by Dostoi** [comment]
Yes I got it. It's great, thanks a lot !
