### ISSUE TITLE
Download remaining - ask for confirmation

### ISSUE THREAD

**Issue by lenisko** [raulhaag/MiMangaNu#150]
It's very confusing button in my opinion, what about adding window with question "Are you sure?" after clicking it ?

**Comment by Dostoi** [comment]
Maybe just finding a more appropriate name ?

**Comment by raulhaag** [comment]
descarga los capitulos no descargados
now whith download unread is almost unusable

**Comment by lenisko** [comment]
It's not name problem, It's easy to miss-click it
