### ISSUE TITLE
Chapter list view is always on top of the read chapter if read chapter is n°1

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#151]
If you're reading the first chapter and you go back to the chapter list, the chapter will be hidden. The view will show the 2nd chapter at the bottom and not the first.

**Comment by raulhaag** [comment]
can't recreate, can you make  a capture? for this and the other, because can be the same problem

**Comment by Dostoi** [comment]
It show this (don't mind the chapter in blue in the middle) : 

![screenshot_2015-11-11-15-39-26](https://cloud.githubusercontent.com/assets/7694864/11093469/b89fc8c6-888a-11e5-8a47-112372cca957.png)


And it should show this : 

![screenshot_2015-11-11-15-39-34](https://cloud.githubusercontent.com/assets/7694864/11093485/cad2683c-888a-11e5-8ae1-e3be5ccbb100.png)

The issue is, when the active chapter is the first one, the chapter list start from chapter 2 and not 1.

**Comment by raulhaag** [comment]
ok now i undarstane this is e proble with the listview beacuse i use to save the position state  get firs visible and set this on resume and if the 8(in this case) visible is taken as mark, it's an android limitation

**Comment by Dostoi** [comment]
You can fix it ?

**Comment by raulhaag** [comment]
not so sure but i will try

**Comment by raulhaag** [comment]
i only can fix whe you go back from reader

**Comment by Dostoi** [comment]
Ok no problem.
