### ISSUE TITLE
Chapter list show manga description and not the last read chapter

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#152]
If the manga description is long and the last read chapter is close the the last one published, the app will show the manga description and not the last read chapter.
An exemple can be found with http://kissmanga.com/Manga/Sidonia-No-Kishi
I'm reading chapter 77 but the app doesn't show me the chapter but the manga description when going to the chapter list.

**Comment by Dostoi** [comment]
It shows this : 

![screenshot_2015-11-11-15-38-45](https://cloud.githubusercontent.com/assets/7694864/11093513/f3b5df54-888a-11e5-9f00-daa3682005d2.png)


When it sould show this : 
![screenshot_2015-11-11-15-38-58](https://cloud.githubusercontent.com/assets/7694864/11093515/f6911662-888a-11e5-90b2-86144adf45ea.png)

**Comment by raulhaag** [comment]
same here, i only can fix whe you go back from reader

**Comment by raulhaag** [comment]
ready

**Comment by Dostoi** [comment]
Great ! I'll test everything later :)
