### ISSUE TITLE
Changing the start point of the new horizontal reader

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#153]
When using the new vertical reader and having the next page on the left (if you're in the middle of the  chapter, the first page of the chapter will be on the right and the last on the left), the first page starts on the left of the manga and not on the right.
Is it possible to change the start point and put it on the right of the first page and not the left if using this view ?

**Comment by raulhaag** [comment]
1 image > 1000 words

**Comment by raulhaag** [comment]
any image to get an idea

**Comment by Dostoi** [comment]
This is the first page of a chapter. You can see the reading sense with the picture.

![screenshot_2015-11-16-17-43-01](https://cloud.githubusercontent.com/assets/7694864/11188145/bd8e32a2-8c89-11e5-99e7-6bc07c4f9abb.png)

The issue is that the reader start on the left side of the page and not on the right page which would be better with this reading sense.

**Comment by raulhaag** [comment]
ok in horizontal, i go to se if i can fix it to v 1.41

**Comment by Dostoi** [comment]
My bad, I used the wrong one ^^
