### ISSUE TITLE
error con tusmangasonline

### ISSUE THREAD

**Issue by xken2x** [raulhaag/MiMangaNu#154]
al agregar un manga desde TMO se poduce un error al agregarla, todos los capitulos salen sin numero, y cuando descargas un capitulo sobreescribe todos los demas, imposibilitando la descarga de todos los capitulos de un manga.

adjunto screenshoots
![screenshot_2015-11-13-17-16-10 1](https://cloud.githubusercontent.com/assets/11857942/11159306/4d44bdc2-8a13-11e5-88b0-b33b26ea8a3c.png)

**Comment by raulhaag** [comment]
listo para la proxima version
