### ISSUE TITLE
Speedup checking for new manga

### ISSUE THREAD

**Issue by lenisko** [raulhaag/MiMangaNu#155]
Like in title.
Maybe checking info about manga on multiple connections?

**Comment by raulhaag** [comment]
on backgorund i thread is ok because you can get all the cpu but in manual chack can be posible

**Comment by lenisko** [comment]
So maybe:

Default threads in background: 1 -- but max 4 available in options,
Default threads in foreground 2 -- max 4 in options.

**Comment by xken2x** [comment]
its a good idea, because the time to update a galery of 100 mangas is veeeery long, and a common person can impatient to wait 10 minutes to know if his favorite manga launch a new chapter.

**Comment by raulhaag** [comment]
Testing, is promising, need to add the cofiguration to finish

**Comment by lenisko** [comment]
@raulhaag nice, willing to test it.

**Comment by raulhaag** [comment]
last commit contains the mod

**Comment by Dostoi** [comment]
Way better right now (with 7 threads at the same time on manual, it takes only a couple of seconds to update)

**Comment by lenisko** [comment]
Okay, thanks. Works like charm!
