### ISSUE TITLE
Improve update notification

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#156]
Right now when an auto-update is running, the notification is only telling that it's updating but not the % or number of manga already/left to check.
It would be better to be able to now how many update check are left.

**Comment by manokara** [comment]
Indeed. Clicking on the notification should open the app as well.

**Comment by Dostoi** [comment]
It could be nice to have this change with the manual update too.

**Comment by raulhaag** [comment]
@manokara  if there is new manga notification open the app
@Dostoi ready for next version n/total in notification and manual

**Comment by Dostoi** [comment]
Great, thanks again :+1:

**Comment by Dostoi** [comment]
I don't know if it's useful to still show the manga name as you can check several mangas at the same time now.
Maybe only show the number ?
