### ISSUE TITLE
Protocol error with the french server

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#157]
When trying to acces a manga on the french server to add it, I've got a protocol error 

![screenshot_2015-11-19-11-26-57](https://cloud.githubusercontent.com/assets/7694864/11269769/91167c34-8eb9-11e5-9221-f89d078f98f8.png)

**Comment by raulhaag** [comment]
ready, but you know :-P

**Comment by Dostoi** [comment]
No, I can't build to test it ^^

**Comment by Dostoi** [comment]
Thanks :)
