### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#161]
There's an issue with the Italian translation that prevent me from building the app.
With this sting:
<string name="last_chapter">Attualmente questo è l'ultimo capitolo</string>
The issue is :
Error:(2) Apostrophe not preceded by \ (in Attualmente questo 'Ã¨' l'ultimo capitolo)

**Comment by raulhaag** [comment]
Sorry i'm waiting for the arrive of a new hardisk next week no Android studio until that. but not complicated to solve

**Comment by Dostoi** [comment]
Ok nice

**Comment by null-dev** [comment]
Follow the instructions, it's literally add a backslash before the apostrophe character in /app/src/main/java/res/value-it/string.xml

Another hint: It's on line 150

I will probably submit a PR for this since it is so simple.
