### ISSUE TITLE
Add more providers

### ISSUE THREAD

**Issue by M2ck** [raulhaag/MiMangaNu#167]
Currently english and spanish languages have five providers each, while french, german and italian languages have only one provider each.
It would be nice to make available the same quantity of choice for these languages.
Thanks in advance.

**Comment by Dostoi** [comment]
The thing is, it's hard to know good providers, or at least used providers.
So maybe adding in the next changelog and somewhere in the app, that if people want to, they can ask for new providers to be added.

**Comment by M2ck** [comment]
You're right, add a "submit a provider in your language" link via maybe Google Drive in Settings > About category would be a good idea.

**Comment by Dostoi** [comment]
Just "Submit a new provider" it doesn't have to be in the native language of the user (I'm French but only reading manga on an English website ^^).
In the about section would be nice. 
How would you do that with google drive ?
I was more thinking of having a link that open the browser to the github page of the app and show the readme (where there would be a new part which explain that you can ask for new provider and tells you do to that by creating an issue).

**Comment by raulhaag** [comment]
can you tell me a few providers how can fit to model used to the app i only add 5 spanish provider because i speak spanish, english servers for they big collection, and only 1 for others for alternative to those how does not speak english and spanish

**Comment by M2ck** [comment]
@Dostoi, sorry i meant via Google Docs or Sheets.
I'm not sure there are many GitHub users so that why i think post a request via Google Docs would be the best choice. 
Or via email address like apps available on Google Play, where developer must provide an email address.

@raulhaag, well i'm not sure i've checked others manga reader apps and i've found these following providers:
French language: Anime Story, Batoto(FR), French manga
German language: MangaTube
Italian language: MangaEden(IT), Itascan, Batoto(IT)

**Comment by raulhaag** [comment]
Anime story and french manga sites?
the others ar incompatible at the moment

**Comment by M2ck** [comment]
Yes if they are compatible with your app, thanks!

**Comment by raulhaag** [comment]
web pages? to general name

**Comment by M2ck** [comment]
Forget websites I mentioned above, I've found better:
[japscan] (http://www.japscan.com)
[lel-scan] (http://lel-scan.co/lecture-en-ligne-one-piece.php)
[lirescan] (http://www.lirescan.com)
[wallagain] (http://www.wallagain.cc)
Please add them if you can!

**Comment by Dostoi** [comment]
Except if you really want these particular site to be added, I can go to a manga club I know and ask them for good scan site in french if you want ?

**Comment by M2ck** [comment]
Well if there is a problem with reader sites requested above, yes why not. It's always good to have outside opinions.
Thanks for your proposal!

**Comment by Wabuo** [comment]
Hey I would really love to see manga-tube.org to be integrated in this wonderful app. If you need help maybe I'm able to do something. If you need anything from the manga-tube guys feel free to ask, I know few of them.

**Comment by raulhaag** [comment]
added manga-tube y mangaedenIt

**Comment by null-dev** [comment]
I think you should just open an issue if you want a new provider, then we can tag it and assign it since it's not really different from an issue anyways.

**Comment by M2ck** [comment]
Running on v1.42 and unfortunately mymangaio is not really good.
@raulhaag what's new about these providers?:
> [japscan] (http://www.japscan.com)
[lel-scan] (http://lel-scan.co/lecture-en-ligne-one-piece.php)
[lirescan] (http://www.lirescan.com)
[wallagain] (http://www.wallagain.cc)

Not a request for eta just for know if you can or not add them.

**Comment by raulhaag** [comment]
@M2ck japscan not and the other don't have more than 20 mangas

**Comment by null-dev** [comment]
Ooh, maybe we could have plug-in based providers *wink* :).

**Comment by M2ck** [comment]
@raulhaag ok but I prefer to have less choice and a better data base.
