### ISSUE TITLE
Improve colors chooser

### ISSUE THREAD

**Issue by M2ck** [raulhaag/MiMangaNu#169]
Could you use the colors chooser built-in to this library: [material-dialogs] (https://github.com/afollestad/material-dialogs), there are many presets and custom color feature too.
Thanks in advance.

**Comment by Johndeep** [comment]
Hmm, I suggested this to raulhaag too, but well, he doesn't seem to like custom color chooser.
I can at least add some color to the list, if you like ;)

**Comment by M2ck** [comment]
Too bad, it would be a real improvement to have a color chooser like on Material Dialogs library mentionned above.

**Comment by raulhaag** [comment]
@Johndeep  i think it's injustificated to add the library only for the color chooser, if you wan't to make a color chooser leaving the option to select default colors its ok to me

**Comment by Johndeep** [comment]
To have backwards compatibility, new stuff like the material theme and feel requires extra library, which usually does _not_ coming from google. Of course, you can just raise the API border, but then.. well, you know.

Also.. I really go the feeling, the more modern the app gets, the slower it becomes.. maybe it's just my imagination.

@raulhaag Why me? M2ck wants a new color chooser, not me! :sweat_smile:

**Comment by M2ck** [comment]
@raulhaag You're right so rather see it as an example of what I looking for.
> i think it's injustificated to add the library only for the color chooser

@Johndeep if only I had skills for coded I would have directly sent a pull request... :wink: 
> Why me? M2ck wants a new color chooser, not me! I'm totally fine with the current chooser! :sweat_smile:

**Comment by M2ck** [comment]
@raulhaag @Johndeep what do you think about this new theme engine library: [https://github.com/afollestad/app-theme-engine]()?
