### ISSUE TITLE
Improve horizontal reader

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#171]
Right now with the horizontal reader set on reading from right to left, taping on the left side of the screen (on the side of the next pages) move the reader to the previous pages and not the next. And taping on the right side move to the next and not the previous, which isn't logical with the reading sense.
it would be more logical to switch them.

And also to change the sense of the scroll bar at the bottom to be in the same sense as the reading sense.

Picture here this time ^^
![screenshot_2015-12-01-09-15-34](https://cloud.githubusercontent.com/assets/7694864/11495617/f3ce1a7e-980c-11e5-90dd-ed54d2f34255.png)

**Comment by raulhaag** [comment]
the tap no problem, the seekbar i go to see

**Comment by Dostoi** [comment]
Thanks ^^
