### ISSUE TITLE
Lollipop - Need permission to write to microsd

### ISSUE THREAD

**Issue by zero13th** [raulhaag/MiMangaNu#174]
Lollipop - Need permission to write to microsd, so I can save manga to external microsd.

https://metactrl.com/docs/sdcard-on-lollipop/

**Comment by raulhaag** [comment]
read the end of the article 
"This is a system bug. Apps can't workaround it by themselves."
also in the article you can learn how to make it work without an app modification

**Comment by zero13th** [comment]
Would you please point me out where the article is?
Thank you.

On Mon, Dec 7, 2015 at 5:43 AM, raulhaag <notifications@github.com> wrote:

> read the end of the article
> "This is a system bug. Apps can't workaround it by themselves."
> also in the article you can learn how to make it work without an app
> modification
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/raulhaag/MiMangaNu/issues/174#issuecomment-162356654>.
>



-- 
ZerO13th

**Comment by zero13th** [comment]
sorry, nevermind. case closed

On Tue, Dec 8, 2015 at 4:30 AM, First Last <zero13th@gmail.com> wrote:

> Would you please point me out where the article is?
> Thank you.
>
> On Mon, Dec 7, 2015 at 5:43 AM, raulhaag <notifications@github.com> wrote:
>
>> read the end of the article
>> "This is a system bug. Apps can't workaround it by themselves."
>> also in the article you can learn how to make it work without an app
>> modification
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/raulhaag/MiMangaNu/issues/174#issuecomment-162356654>
>> .
>>
>
>
>
> --
> ZerO13th
>



-- 
ZerO13th
