### ISSUE TITLE
ad the permission for read protected storage

### ISSUE THREAD

**Issue by xken2x** [raulhaag/MiMangaNu#175]
a one limitation of the system introduced in android 5+ it makes for write in the external storage, the app need apply for the read permission to protected storage, i have a tablet with android 5 and this is a big problem to me, because only have 16 gb of internal storage.

**Comment by raulhaag** [comment]
supuestamente estaba comprendido dentro de 
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
pero lo agrego igual no hay problema
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
