### ISSUE TITLE
Migrate Network Code to OkHttp?

### ISSUE THREAD

**Issue by null-dev** [raulhaag/MiMangaNu#176]
I would highly recommend migrating all network code to OkHttp. I acknowledge that libraries increase APK sizes however the current network code is not very failsafe and does not work very well on trippy connections (like mine). It would reduce your network code by a couple hundred lines too :+1:. Most apps that access the internet these days use OkHttp anyways...

If this is ok, I can start working on it right away.

P.S. Also, I am looking at the parsing code and I just really, really want to stick in the JSoup library and parse it normally. As many of you know (from here: http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags) that parsing HTML with regex is just a plain bad idea so I think a real HTML parser would do use a lot of good :). I think I can do this too if you are ok with it.

P. P. S. I've already tested adding the Jsoup and OkHttp libraries and in total, APK size went up by only about 0.3mb.

**Comment by raulhaag** [comment]
i never used httpOk if you wanna try do it and test it.
about to change regexp to any parser no (i know there are more clean but)
1- speed (really notorius on test special in old phones) 
2- memory usage (big numbers of objects allocated(same sites have all the manga list on all pages))
if you don't believe you can try it

**Comment by null-dev** [comment]
Ok then, I will get started on OkHttp.
About the JSoup, yeah, I do admit DOM traversal can be slower than regex :(.
