### ISSUE TITLE
Mark Previous As Read

### ISSUE THREAD

**Issue by digiwombat** [raulhaag/MiMangaNu#178]
I'd really find it useful to have the ability to long press and mark all chapters before (or including) the long pressed chapter as read.

For many manga, individual selection is fine, but as I am about 120 chapters behind on some shounen manga and recently had to change source for them, the tedium is too much.

**Comment by Dostoi** [comment]
I agree, it would be better to be able to do it this way. Replacing the current system by that to avoid having to many option in the menu ^^

**Comment by raulhaag** [comment]
![added](https://cloud.githubusercontent.com/assets/2048339/12010659/bed0b098-ac8e-11e5-99a8-03241112fb95.jpg)
ready for next version
