### ISSUE TITLE
Cloud sync/backup

### ISSUE THREAD

**Issue by digiwombat** [raulhaag/MiMangaNu#179]
Losing my database and read progress across a few hundred manga is always a terrifying idea. It's happened to me more than once. 

I'd love to be able to sync the db to a cloud storage service or at least have automated backups to a local folder that I can then manually sync.

**Comment by Dostoi** [comment]
Already here for the backup (see #65 ).
But it would be better to be able to know about it somewhere in the app

**Comment by raulhaag** [comment]
you can backup the db and mangas from the download directory (defaul sdcard/MiMangaNu) and if you copy this to other phone o tablet to defaul folder after install it go to get the db without problems the only lose are config about theme download threads, etc

**Comment by xken2x** [comment]
Why you need a backup un the cloud storage if you have the db of the app?
Only copy the archive and yet.
Please close the issue if has been resolved.

**Comment by Dostoi** [comment]
To avoid losing everything if you lose your phone I guess and not having to manually copying on your computer

**Comment by digiwombat** [comment]
Dostoi pretty much covered it, but cloud storing the database via a
built-in mechanism allows a few things.

One, protection against a lost device, and two, a simple way to keep the
library synced across multiple devices.

If the devs don't want to put the feature in, I'm fine with them closing
it, but I do think cloud syncing of the library haa added value over manual
copying.

**Comment by xken2x** [comment]
the problem is than the app going to be most heavy (by the extra library) arround thr 20-30 mb and need more permits, and the users compained of the intrusive what will be the app

**Comment by xken2x** [comment]
i have 3 devices (a smartphone and two tablets) and if i want have the db synchronized only use a service of storage in the cloud as mega and select the folder to sync automatically, when you modify the db, the backup on the cloud will updated, simple and efficient.

**Comment by raulhaag** [comment]
@digiwombat like xken2x says "the problem is than the app going to be most heavy (by the extra library) arround thr 20-30 mb and need more permits, and the users compained of the intrusive what will be the app"
other way the folther is totally public to any sync app
the app don´t take any data from user (sync procedures needit)

**Comment by digiwombat** [comment]
No worries then! Just wanted to get your thoughts on it.

Consider this one closed/wontfix.
