### ISSUE TITLE
Manga added to downloads notification

### ISSUE THREAD

**Issue by lenisko** [raulhaag/MiMangaNu#182]
Notification is working bad. I mean after adding chapter to download it last lets say 2 seconds. After adding 10 chapters, it's 20seconds. Can you make hard limit for notification, which would ignore ammount of added to download chapters?

**Comment by xken2x** [comment]
I have the same problemas, put than the time is reset when a chapter is added
Example: the time of notification is 2 seconds, when i add 20 chapters, after i add the last, the remaining time of notificación is 2 seconds.
