### ISSUE TITLE
Zoom out limited

### ISSUE THREAD

**Issue by b8e5n** [raulhaag/MiMangaNu#184]
When zooming in and out, I think it is pointless and not convenient to be able to zoom out a page to a smaller size than the screen. That would be convenient to quickly zoom out as much as possible and it fits directly according to the settings (best fit or width fit...).

**Comment by raulhaag** [comment]
if you are reading on a tablet widescreen R2L L2R (verticall don't but has the same base) you need to zoom to fit the page to screen
![zoomout](https://cloud.githubusercontent.com/assets/2048339/11931368/f415bba4-a7ca-11e5-89cd-8026ddd70041.jpg)
but concepts like fit to width in this example make things like a big page to single page but an small to double pages
![fits](https://cloud.githubusercontent.com/assets/2048339/11931320/68d9178e-a7ca-11e5-8f5f-c4e41152fb3e.jpg)
the reader actually make whit the images a big rectangle to matains limits and try to make and easy navegation (not perfect but is all i can do for now) im thinking add a feature  how check the pages size to calculate an accurate fit to width (only on downloaded and R2L and L2R readers) and automatic make the zoom look like the first image but in a futher
