### ISSUE TITLE
change the interface

### ISSUE THREAD

**Issue by xken2x** [raulhaag/MiMangaNu#186]
When the develop of the app was in the early versión 1.15< the app interfaces had a design in which when the finger sideways changed between servers and added mang , instead of the button at the bottom of the app with the current list of servers deployed moved . I would like to implement the old interface or enable it in settings allow , as I think it is more comfortable than the current.

Pd: i know, i am a older user of this app, i use it since half on 2014.

**Comment by raulhaag** [comment]
eso es imposible a menos que seas yo, sos yo? :-P la primera version de mmn en fdroid fue aceptada el 26 de diciembre por lo que va a cumplir un año despues de navidad, de a cuerdo a lo que querias android depreco los tab por eso rediseñe de esta forma la app, despues me fijo si que tal queda si livero la funcionalidad de swipe.
pd: te escribo en español por que se que sos de habla hispana y me cansa mi mal ingles

**Comment by xken2x** [comment]
disculpa XD me he equivocado, yo use la primera version de fdroid, porque casualmente en ese tiempo estaba comenzando con android, solo que me equivoque, ahora que caigo en cuenta era otra app de manga la que use a mitad del 2014.

pd: tu app se crasheaba cada 2 minutos XD, es increible como ha avanzado el desarrollo de esta app, ahora es estable y llena de funciones que jamas soñaria que fueran incluidas en una app como esta
