### ISSUE TITLE
App using too much battery

### ISSUE THREAD

**Issue by Syborg49** [raulhaag/MiMangaNu#188]
Here's the screenshot. http://i.imgur.com/i2MLakW.png

**Comment by xken2x** [comment]
Its a reasonable use of energy, apps as manga rock use arround of 20% of the batery!!
I use the app un the versión 1.41 by problems with the download in the next versión, and have a consumption arround of 1% un a tablet with a batery of 4000 mah.
If you dont need read in russian, install the app in the version 1.41 and tell the ressult.

**Comment by raulhaag** [comment]
@Syborg49  a couple of question to try to find the problem
1- App version? 
2- Always was or this problem start at certain version?
3- AppUse / consumition is to high?
(this is needed to find from were come this probem)
Sorry for my bad english

**Comment by Syborg49** [comment]
1. App version is 1.42 (My android version is 4.2.2 BTW)

2. Always was a problem but now its getting worse. 

3. I think its Too high. I mean the app kept the CPU awake for almost an hour. That's not normal. And don't worry about your English. Its fine @Raulhaag

**Comment by raulhaag** [comment]
indaging about kill the app on back i read this

    Question: Does the user have a choice to kill the application unless we put a menu option in to kill it? If no such option exists, how does the user terminate the application?

    Answer: (Romain Guy): The user doesn't, the system handles this automatically. That's what the activity lifecycle (especially onPause/onStop/onDestroy) is for. No matter what you do, do not put a "quit" or "exit" application button. It is useless with Android's application model. This is also contrary to how core applications work.

the app is designed to not mantain services running and do nothing on backgroud (only if you have downloads whe its finish is destroyed) the update services is opened by the "alarm" run the check and then is destroyed, android keeps on memory to speedup the open but its a part of the system

**Comment by raulhaag** [comment]
@Syborg49 last version reduce cpu uso in a couple of sites, so chek it if reduce in your case the battery usage

**Comment by raulhaag** [comment]
close reopen if necesary
