### ISSUE TITLE
enquiry eng manga sources in this app

### ISSUE THREAD

**Issue by Adamlord1** [raulhaag/MiMangaNu#19]
Request kissmanga addition

**Comment by raulhaag** [comment]
there are others english sources now, this use cloudflare to detect browsers but if i get the ip i can do it whithout problems, i leave this opened for future

**Comment by Adamlord1** [comment]
Can I get the names of sources ,can u have ur details in english too  .I will love if mangapark is supported too if it isn't already there I mean.
Thanks for reply, cool man
Keep going .

**Comment by Adamlord1** [comment]
Sorry I closed issue by mistake

**Comment by raulhaag** [comment]
added kissmanga in v 1.11, i don't go to add mangapark for the moment
