### ISSUE TITLE
Titles are cut in half in List View 

### ISSUE THREAD

**Issue by Awakens** [raulhaag/MiMangaNu#190]
Go to a source and then click on the List icon. Every single title is missing its bottom half.
This is because my tablet screen is small (Amazon Fire 7in. 5th Gen - 2015) and I have set my text font to be huge.
Small screen + large text -> Break UI

**Comment by raulhaag** [comment]
can you make a screenshot?

**Comment by Awakens** [comment]
![screenshot_2015-12-21-13-08-23 1](https://cloud.githubusercontent.com/assets/11169857/11937736/3b2dbf50-a7e4-11e5-9e55-c63d91e21b8b.png)

**Comment by raulhaag** [comment]
only on this list? if is the fix is ready
