### ISSUE TITLE
ListView Button Disappears

### ISSUE THREAD

**Issue by Awakens** [raulhaag/MiMangaNu#191]
After pressing on the button, you are taken to the ListView but there is to way to return directly back to the grid view (back button takes to server list).

**Comment by raulhaag** [comment]
@Awakens  i can't undestand the issue, guide me step by step to check out and recreate from firts screen on app

**Comment by xken2x** [comment]
the problem what awakens said is than in the app, when you open a server and return to the main page the app dont show the main page, instead show the list of servers.
he want what the app return to the main page when you exit from a server, and not return to the list of servers

**Comment by Awakens** [comment]
Ah sorry I forgot there's more than one ListView being used.
1.click on a server that has a list mode (like MangaPanda)
2.click on the ListView button on the top
3.you get directed to the ListView but there is no way to directly return to the previous page (page with all the mangas and their thumbnails displayed in a grid format)

**Comment by raulhaag** [comment]
ok i do it this way to free the memory used by the gridview, if you want i can add a menu button to reopen the list
