### ISSUE TITLE
Crash to main window when reading Manwha.

### ISSUE THREAD

**Issue by AxezCore** [raulhaag/MiMangaNu#193]
Only happens when reading Manhwa, not with Manga. Usually when changing pages but sometimes when scrolling the page as well. Screen either locks or goes black followed by a "MiMangaNu has stopped working" notification and a return to the main window. I realize the comic format are not the reason so probably has to do with image size.

Phone: Galaxy S II
Android build 4.1.2
MiMangaNu build 1.42

**Comment by raulhaag** [comment]
please submit server / manga / chapter

**Comment by AxezCore** [comment]
server was kissmanga, manhwa was h-mate and sports girl, and chapters was all of them. Downloaded prior to reading rather than streaming.
tried running dumpstate/logcat but can't find the logs anywhere. don't know much about android sadly.
As you say, it's likely a memory issue, it's an older model after all.

**Comment by raulhaag** [comment]
h-mate show images from 720 x 4xxx its clare an out of memory i need to develop a way to partial load this images i go to take a time (and perhaps luck)

**Comment by raulhaag** [comment]
![antesydespues](https://cloud.githubusercontent.com/assets/2048339/12010146/575927c0-ac79-11e5-8c66-eac0ec89e2c2.jpg)
and the old reader
![old](https://cloud.githubusercontent.com/assets/2048339/12010175/5ac671f0-ac7a-11e5-993a-c1811eaac9e5.jpg)
testing memory usage after an before the changes from 20mb to 13.5mb in h-mate manga and on old reader 36mb for now testing but really promising

**Comment by AxezCore** [comment]
Looks really promising :)

**Comment by raulhaag** [comment]
also i found a couple of thing that can cause win_death and a realy big reestructuration was mede, i think i can finish this before my hollidays

**Comment by raulhaag** [comment]
did you test las version?

**Comment by AxezCore** [comment]
Sorry for the late reply, just did a quick test with both manhwas I mentioned earlier. Sports girl is now working perfectly, but h-mate still crashes during page changes. IIRC h-mate would also crash when scrolling as well as page changing before but that doesn't happen anymore, so it's has definitely helped.
