### ISSUE TITLE
The add manga button is over the synopsis if it's too long

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#194]
It's just the right size to prevent me from going down and hide the button.

![screenshot_2015-12-26-07-59-18](https://cloud.githubusercontent.com/assets/7694864/12005479/08b48eca-aba7-11e5-9edc-f9ad5a9142d4.png)

**Comment by Awakens** [comment]
Hi, could you specify what the dimensions of your device's screen are?

**Comment by Dostoi** [comment]
It's 4.5, it's an alcatel one touch pop 2 
http://alcatelonetouch.com/global-en/products/smartphones/pop_2-4-5.html
