### ISSUE TITLE
Deleting picture then redownloading them and reading the chapter reset the page counter

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#195]
Deleting the picture of a chapter then redownloading them and reading the chapter again reset the page counter of the chapter with the last travis version

**Comment by raulhaag** [comment]
i think now is fixed

**Comment by raulhaag** [comment]
i go to test for two days the new "new" reader things i pushed if evething go well go to be released in 3 days, please test it

**Comment by Dostoi** [comment]
I'll test it :)

**Comment by raulhaag** [comment]
updated travis version
