### ISSUE TITLE
Mark as read a chapter only when you reach the end of it

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#20]
Right now a chapter is marked as read when you begin to read it, so if it's the last chapter of the manga and you've already mark as read the rest of the manga, the manga isn't going to be shown anymore if you go back (and have selected the hide read manga option)

**Comment by raulhaag** [comment]
ok, mora than readed is opened, i see if i can fix in the next version, now i'm working on other part

**Comment by Dostoi** [comment]
Ok no problem

**Comment by raulhaag** [comment]
ready for the next version
