### ISSUE TITLE
Raw Manga chapter

### ISSUE THREAD

**Issue by wwark** [raulhaag/MiMangaNu#201]
Hello,

Did you plan to add some website with japaneses manga chapter ?

Best regards,
Wark.

**Comment by xken2x** [comment]
to add a new source website this need have a lot of mangas, because exist so many fansub pages with 5 or 6 proyects, and cannot add all.

**Comment by wwark** [comment]
http://raw.senmanga.com/
http://online.mangaraw.net/

Maybe there is more site with much more content.

**Comment by M2ck** [comment]
>to add a new source website this need have a lot of mangas, because exist so many fansub pages with 5 or 6 proyects, and cannot add all.

Unfortunately some of these websites with lot of choice are in reality empty, that's the problem...

**Comment by miyamama** [comment]
This one will be a good start 
http://mangabox.co

**Comment by raulhaag** [comment]
semanga look possible

**Comment by raulhaag** [comment]
addad senmanga
