### ISSUE TITLE
Option to cancel all download

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#207]
Right now if you launch a lot of download at once, to cancel it you have to either manually cancel all of them or stop your internet connection.
An option to cancel all of them could be nice if you change your mind on a download

**Comment by raulhaag** [comment]
![downloadoptions](https://cloud.githubusercontent.com/assets/2048339/12533480/0d2fe728-c20f-11e5-9dac-95be3a178e4e.jpg)
adding this option on test

**Comment by Dostoi** [comment]
It's way more than what I hoped for ^^
I'll test it right away :)

**Comment by Dostoi** [comment]
I don't have any change in the interface. No option menu, pressing the physical option button doesn't do anything

**Comment by raulhaag** [comment]
Testing local not committed yet

**Comment by raulhaag** [comment]
test it on travis

**Comment by Dostoi** [comment]
Perfect, doesn't seem to have any bug. You can even stop and delete download in progress which wasn't allowed before.
Really great work !
