### ISSUE TITLE
MangaHere and MangaHereES Download Issues.

### ISSUE THREAD

**Issue by digiwombat** [raulhaag/MiMangaNu#209]
MangaHere and MangaHereES chapter downloads time out regularly owing to a minor difference in how their CDN serves up images.

Basically, their CDN requires a valid timestamp on the image or it serves the image extremely slowly.

Easiest solution would seem to be adding the timestamp to the regex for grabbing the page filename and just remove it when you save file to disk.

**Comment by raulhaag** [comment]
do you reffer to jpg?v=0000000000 ?

**Comment by digiwombat** [comment]
Yeah, if the ?v=0000000000 querystring is removed, the images load far slower and often timeout.

Also, if the v= querystring is not set to the correct time, the images will load slowly.

**Comment by raulhaag** [comment]
ready on last version
