### ISSUE TITLE
Can't find a manga with kissmanga

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#21]
I was trying to find this manga (http://kissmanga.com/Manga/Hive) but when I search with the app I can't find it.
I don't know if you can do something about it.

**Comment by raulhaag** [comment]
Sorry, no at home until the next week.

**Comment by Dostoi** [comment]
Don't worry, it's not urgent :)

**Comment by raulhaag** [comment]
fixed on next update

**Comment by Dostoi** [comment]
Ok great
