### ISSUE TITLE
Bug on lockscreen

### ISSUE THREAD

**Issue by lenisko** [raulhaag/MiMangaNu#213]
After locking screen, position in chapter is set to end of it.

**Comment by raulhaag** [comment]
i know this bug, i go to see if i can fix (its on when recreate activity the problem)

**Comment by lenisko** [comment]
sure, good luck!

**Comment by lenisko** [comment]
Still same problem

**Comment by raulhaag** [comment]
paged reader or continuous?

**Comment by lenisko** [comment]
continuous
