### ISSUE TITLE
Is every travis version supposed to have a different signature ?

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#215]
Every time I download a travis apk, I have to uninstall the app because the apk have a different signature from the last I used, so I have to reput all my settings.
Is it normal ?
Can it be changed ?

**Comment by null-dev** [comment]
In all Android apps, debug versions are built with a different signature than release versions. Does this happen between travis versions or when you are upgrading from the last release?

**Comment by Dostoi** [comment]
Between travis version, I'm only using them now and every time I have to delete the app to reinstall the newest version

**Comment by raulhaag** [comment]
no idea really about it and without time ti investigate

**Comment by Dostoi** [comment]
No problem

**Comment by raulhaag** [comment]
from now all travis and my release go to have the same sign, avaible on the repo and all the data to use. i don't know if this affect fdroid sing until next release

**Comment by Dostoi** [comment]
Great, thanks for the change
