### ISSUE TITLE
Bug - Wrong manga status - KissManga, maybe other too

### ISSUE THREAD

**Issue by lenisko** [raulhaag/MiMangaNu#217]
It's always Ongoing.

I am not Java developer and in python I didn't need to escape chars unless there was `"`, so maybe your regex is broken?
```
boolean status = getFirstMatchDefault("Status:</span>&nbsp;([\\S]+)", source, "Ongoing").length() == 9;
```

`\\S` shouldn't be `\S` instead, or it's just escape?

**Comment by raulhaag** [comment]
in java you need to scape the string of \ using \\ an to the regex only read \S (is the slash scape)
