### ISSUE TITLE
Manga crash when changing page with new reader

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#218]
When I'm going from page 4 to 5 of the manga Funouhan from kissmanga (http://kissmanga.com/Manga/Funouhan/Vol-001-Ch-001--The-consequences-of-an-unjust-crime?id=233400) the app crash.

I'm using the last travis version and the new reader, I tried to redownload the chapter but it doesn't change anything. Using the scrolling bar at the bottom to go directly after the 5th page make the app crash too.
It works fine with the old reader.

**Comment by raulhaag** [comment]
test last version i did a pair of changes

**Comment by Dostoi** [comment]
Fixed, thanks :)
