### ISSUE TITLE
Feature request - delete chapter after read

### ISSUE THREAD

**Issue by lenisko** [raulhaag/MiMangaNu#220]
"You want to open the next chapter?" how about adding one more option like `Clean & OK` ?

**Comment by Dostoi** [comment]
:+1:

**Comment by raulhaag** [comment]
![del_images](https://cloud.githubusercontent.com/assets/2048339/13702155/4f95df1a-e76b-11e5-9175-768159d5fd2d.png)
don't worry about 2 taps chackbox has memory of your last selection
