### ISSUE TITLE
Update on Kiss manga not showing in the app

### ISSUE THREAD

**Issue by sm7297** [raulhaag/MiMangaNu#223]
update for different manga not showing in the app from kissmanga server
other servers work fine

**Comment by lenisko** [comment]
Its like that sometimes

**Comment by raulhaag** [comment]
please examples to test (i just test whit One punch man and work ok)

**Comment by sm7297** [comment]
Now there are some many error when downloading manga and while reading some pictures are missed it dont even reload the picture i have to delete and download the whole chapter

**Comment by xtj-9182** [comment]
please re-test with v1.49 and check if it still happens.

**Comment by raulhaag** [comment]
@sm7297 i updated the download system check last travis version
