### ISSUE TITLE
Add option to redownload single page(s)

### ISSUE THREAD

**Issue by chazzam** [raulhaag/MiMangaNu#228]
Why isn't there an option to try redownloading single errored pages in a chapter? The only thing I can find is to back out of the chapter, delete the whole thing, and open it again. Why do I need to redownload 48 pages that worked correctly to get one page that errored out?

**Comment by manokara** [comment]
:+1: I second this. On a slow connection and with many pages, well, redownloading all pages could take a while (and it might error again, and you have to restart the download, again).

**Comment by chazzam** [comment]
It is also very expensive when it repeatedly errors out (and you have to restart the whole thing) when considering data caps, for both data and home internet now :(

**Comment by raulhaag** [comment]
![reloadimage](https://cloud.githubusercontent.com/assets/2048339/13671258/9ea85d94-e6ad-11e5-8471-e4e34feedfbf.png)
