### ISSUE TITLE
Downloading chapter and zoom

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#23]
I'm not sure if it's related but when I was downloading the last chapters of a manga and reading it at the same time, I might have found an issue.
If you're zooming on a page, the zoom will go off when the download is finished.
I couldn't try it again after that but it seem to be related.

**Comment by Nodd** [comment]
I confirm this problem, the zoom is reset when a download finishes.

**Comment by raulhaag** [comment]
i think i fix this to the next version check when available (probably i commit tomorrow whit other fixes) around 2 days to f-droid release

**Comment by raulhaag** [comment]
still having this problem?

**Comment by Dostoi** [comment]
It seems to be good for me.
