### ISSUE TITLE
Imposible mover descargas a la tarjeta SD

### ISSUE THREAD

**Issue by cristfcb** [raulhaag/MiMangaNu#234]
Hace poco intente pasar las descargas a la tarjeta SD y siempre que quiero establecerla como directorio de descarga me sale como directorio no escribible, no se si es problema de mi teléfono (Xperia z3 compact) o acaso es una imposibilidad de la aplicación

**Comment by raulhaag** [comment]
desde android kitkat no se puede escribir la tarjetasd (algunos dispositivos los parchearo por su cuenta, pero depennde de la marca), pero si creas la carpeta Android/data/ar.rulosoft.mimanganu/ podes usarla sin problema si la seleccionas

**Comment by cristfcb** [comment]
Gracias por el dato, funciono perfectamente
