### ISSUE TITLE
Tu manga online 

### ISSUE THREAD

**Issue by cristfcb** [raulhaag/MiMangaNu#237]
Mi pregunta es: la conexión con tu manga online se retomará al momento de que la pagina vuelva a la normalidad o eso ya no sería posible? 
Espero y se pueda retomar ya que no quiero cambiar a otro servidor de manga, me encanta tu manga online.

**Comment by raulhaag** [comment]
estoy esperando a que terminen para ver que nivel de compatibilidad habrá si se puede hacer automático o si va a ser necesario que sea un servidor enteramente nuevo cuando este listo te contesto definitivamente

**Comment by cristfcb** [comment]
OK lo estaré esperando, gracias por responder

**Comment by raulhaag** [comment]
se va a retomar pero no va a ser compatible con los mangas anteriormente agregados

**Comment by cristfcb** [comment]
Ahh OK gracias, entonces solo tendría que eliminar los mangas que tenia agregados y añadirnos nuevamente.
