### ISSUE TITLE
Unfortunately mimanganu has stopped working message on kitkat

### ISSUE THREAD

**Issue by sm7297** [raulhaag/MiMangaNu#242]
i have installed latest version in kitkat 4.4 and it not opening

**Comment by raulhaag** [comment]
i need more information

**Comment by sm7297** [comment]
what information can i give

**Comment by raulhaag** [comment]
use any logcat app or from pc

**Comment by sm7297** [comment]
i have deleted everything related to mimanganu and also the folder and then installed the 1.46 version and now its working

**Comment by raulhaag** [comment]
may be next time
