### ISSUE TITLE
Simultaneous download doesn't work

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#243]
I set the Simultaneous download setting at 8, and if I try to download several chapter at the same time, only one at a time is downloaded. For my last test it was this manga : http://kissmanga.com/Manga/Freesia
I don't remember seeing that feature ever working

With the last travis

**Comment by raulhaag** [comment]
That is the numbers of pages at same time not chapters

**Comment by Dostoi** [comment]
Ho ok my bad, I misunderstood the feature.

Is it possible to have one to download several chapter at the same time then ?

**Comment by raulhaag** [comment]
the number of parallels download is to speed up the download, multiple images at same time, and on end its start the next, if you star to read an chapter its go to the top of the download list and all the download go to be assigned to this, start all chapter at time dont change the download time
