### ISSUE TITLE
MyManga.Io new restriction's politic

### ISSUE THREAD

**Issue by Zykino** [raulhaag/MiMangaNu#246]
[MyManga.Io](http://MyManga.Io) have a new politic and say that since you download the image not directly from them you are "stealing their bandwidth".

They are asking to contact them if you want to use their images (the standard webmaster e-mail is given).

I had it when re downloading a chapter of "Gun X Clover" but it's more like they change their term of use.

Don't know if I'm clear here, I can send them the e-mail if you want to so we can quickly know if Mi Manga Nu will be authorize to use the images. But since I'm not from the dev team not sure it would be a good help.

As a workaround the website give the possibility to download the Zip so maybe this still works.

(If my message is not clear I'm sorry, it's late here)

**Comment by raulhaag** [comment]
check last compilation (Travis)  if work (for me works well)

**Comment by Zykino** [comment]
I'm on version 1.47 (the last one on F-Droid)

Just tested it and still download the said images instead of the manga.

Don't want to delete my other saved chapters. But it's happening with "Chapitre 07".

If you need any informations/log/... just tell me how to get it and I'll post them.

**Comment by raulhaag** [comment]
ok wait for 1.48 is on develop but is working

**Comment by raulhaag** [comment]
a moment ago i commit the version 1.48 in 1 o 2 days fdroid go to publish whit their sign

**Comment by Zykino** [comment]
Just updated it and download the chapter, images are  back here thank you :)
