### ISSUE TITLE
Being able to rotate a picture

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#25]
It would be nice to be able to rotate a picture.
Like if you reading while laying down in your bed you can't use the auto rotate of android because the phone will rotate in the wrong direction.
It would be usefull especially for scan of 2 pages at the same time

**Comment by raulhaag** [comment]
the library used (imageviewtouch) don´t support rotate

**Comment by Dostoi** [comment]
ok no problem
