### ISSUE TITLE
is Mark selected as unread working as intended ?

### ISSUE THREAD

**Issue by xtj-9182** [raulhaag/MiMangaNu#252]
select any chapter and press mark selected as unread. Now what happens is that the color of the chapter is changed from dark grey to white and that is all, my expectation would be that it would also reset the page to 1 (or 0) so that one can read the chapter from the beginning again, but that is not happening.

**Comment by raulhaag** [comment]
the function you find is reset chapter

**Comment by xtj-9182** [comment]
yeah so I know about reset chapter, however that's also deleting the chapter/volume.

when I was testing the memory leak I had to constantly reset chapter which would delete whole volumes and then I had to re-download these volumes, that's why I was asking if it's the intended function.

so I just looked at the code and I think all we have to add is three lines in the markRead function. Anyway so I'm gonna make a pull request and if it's not the intention of the mark selected as unread function then just reject the request.

**Comment by xtj-9182** [comment]
last time I was in a hurry, I forgot some things; 

I didn't update the db and forgot about mark all as unread give me a moment

**Comment by xtj-9182** [comment]
ok so I made some enhancements but I'm not sure if the mark all as unread code is good as it is 
I think it could probably be improved;

`
                mChapterAdapter.selectAll();
                SparseBooleanArray selection = mChapterAdapter.getSelection();
                for (int i = selection.size() - 1; i >= 0; i--) {
                    Chapter c = mChapterAdapter.getItem(selection.keyAt(i));
                    c.markRead(getActivity(), false);
                }
                mChapterAdapter.clearSelection();`

**Comment by xtj-9182** [comment]
marking as closed for now, if anyone wants to improve my code that's ok.
