### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by xtj-9182** [raulhaag/MiMangaNu#253]
This bug is the same as https://github.com/raulhaag/MiMangaNu/issues/30, however that issue is at the end of page 2 so I'm making a new issue but it's technically the same. 

to reproduce:
1. add School Rumble from Mangareader.net (School Rumble is released in volumes that's why it works)
2. go from page 0 to end page of any one volume and see how we constantly allocate memory but never release any (or at least we don't release enough)
(3. interestingly once we go from volume to volume / (chapter to chapter) we suddenly release lots of memory. If we could somehow do something like that after 40 to 50 pages that would probably help a lot.)

So we are leaking a ton of memory, just look at this: https://imgur.com/5PJBZ0C
this is after I went from page 0 to 161 on a Volume of School Rumble. As you can see we are never
releasing any of the bitmaps that we allocate, previously we would crash at around ~190 to 200 MB of allocated memory, there are two workarounds, that don't fix the problem but that make it more bearable, one of them is just lowering the texture size to 1024 and the second is increasing our heap size, I just made a commit to accomplish the latter but again this isn't fixing our memory leak, it's only making it more bearable.

The long term solution is probably to rewrite ActivityPagedReader (possibly some other classes too) maybe turning the readers into fragments could help.

**Comment by raulhaag** [comment]
Testing in android 4.4.2 and this is what i get
![memoriasr](https://cloud.githubusercontent.com/assets/2048339/15028177/f1a75036-121d-11e6-8de5-da367f949c53.jpg)

probable a modification to last android are needed

**Comment by raulhaag** [comment]
check last commit

**Comment by xtj-9182** [comment]
the latest commit fixed it, now I sit around 30 to 50 MB allocated after going from page 0 to 183.

Interesting to note I did some tests before you made the latest commit and I found out that only devices with android 5+ seem to have been affected, devices with kitkat or less probably were probably not affected by this memory leak, I'm guessing it has something to do with the way pixel data is saved in 5+ since they put that data in the heap and it used to be separate from it so on kitkat or lower people didn't notice.
