### ISSUE TITLE
(Feature) Add local files to db

### ISSUE THREAD

**Issue by wyrex** [raulhaag/MiMangaNu#254]
I couldn't find how to do it, but if I already have chapters locally (with file names they have at server) it would be nice if there was a way to add them so they show as "downloaded" chapters. I tried to add new manga and then manually move files but when I open chapter local files get deleted and downloaded from server. There could be menu button for selecting path to local files, or it could be automatic from existing folder.

**Comment by raulhaag** [comment]
on the way, testing, but need more work

**Comment by raulhaag** [comment]
sorry, i forget to comment the last version on fdroid contains this anhancement
