### ISSUE TITLE
[Android 6] (possibly not a bug) What are we doing with the Phone permission group ?

### ISSUE THREAD

**Issue by xtj-9182** [raulhaag/MiMangaNu#258]
On Android 6 you can check what permission an app is granted and what permissions an app is not granted. When looking at MiMangaNu I can see that we have a Storage permission and that is granted once we start up and the user grants it, then there is a Phone permission group but it's not granted, I have no idea what we are doing with this phone permission group but from what I can tell we never request that permission. According to google these permissions fall under this group:

> 
    READ_PHONE_STATE
    CALL_PHONE
    READ_CALL_LOG
    WRITE_CALL_LOG
    ADD_VOICEMAIL
    USE_SIP
    PROCESS_OUTGOING_CALLS

see: https://developer.android.com/guide/topics/security/permissions.html#normal-dangerous

as far as I can tell I have not run into any problems yet even though it's not granted, I just thought it was odd that we have that permission.

Edit: even weirder is that in our manifest we only declare these permissions:

> 
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

the following three are normal permissions and on android 6 you get those granted for free:

> 
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

and these two we get when we request storage permission:

> 
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

Why am I seeing a phone permission group even though we don't declare any phone permissions ?

Edit2: here is a picture of what I am seeing: https://imgur.com/TbzqILu

**Comment by raulhaag** [comment]
no idea, really don't needed, if you read the code you can note there is no personal data touched and i don't know why that happend and don't know if all app has this optional permision on their list

**Comment by xtj-9182** [comment]
I found out that when I install v1.45 it states that MiMangaNu wants to have the READ_PHONE_STATE permission, maybe we used that once and it's now just left over code ?

**Comment by xtj-9182** [comment]
I found this: https://stackoverflow.com/questions/30277242/why-is-my-app-asking-for-phone-id-permission 

So it seems that we are using a library that has targetSdkVersion < 4. I wonder if it has any effect that we don't request this permission on Android 6 ...

**Comment by xtj-9182** [comment]
from what I can tell this seems to cause no problems on Android 6 even though we don't request the permission and it stays as denied, marking as closed
