### ISSUE TITLE
Mimanganu closed automatically

### ISSUE THREAD

**Issue by sm7297** [raulhaag/MiMangaNu#264]
when i click on new chapter in any manga or manhwa for example if there is an new chapter and i click to click read the app closes automatically without any warning and then second time when i open it then it open correctly in the latest in build
on my android kitkat

**Comment by xtj-9182** [comment]
can you install https://play.google.com/store/apps/details?id=com.nolanlawson.logcat&hl=en and try to reproduce the error ? Please give us the exception that is logged thanks.

**Comment by sm7297** [comment]
error log
[2016-05-15_21-14-26.txt](https://github.com/raulhaag/MiMangaNu/files/265072/2016-05-15_21-14-26.txt)

**Comment by xtj-9182** [comment]
can you try using this debug build:
(you need to uninstall your current version first)
[app.zip](https://github.com/raulhaag/MiMangaNu/files/265128/app.zip)

I tried to fix the first crash with a bounds check, the others seem like OutOfMemory errors so probably harder to fix...

**Comment by raulhaag** [comment]
@sm7297 closed if continues reopen
