### ISSUE TITLE
Missing Chapters for Mangafox

### ISSUE THREAD

**Issue by hafernstock** [raulhaag/MiMangaNu#27]
Adding a manga from the source mangafox.me results in missing chapters.

For example adding "Monster" (http://mangafox.me/manga/monster/) will result in chapters 01-14, 40-49 and 152 of total 162 chapters. Deleting and readding it won't solve the issue. However using other sources like mangahere will add all chapters.

I've read of your absence and I will switch to other sources in the meantime, so no hurry.

**Comment by raulhaag** [comment]
chek if work when the next version avaible.

**Comment by hafernstock** [comment]
Adding chapters from mangafox using version 1.14 works fine. Thanks for the fix.
