### ISSUE TITLE
Physical option button doesn't work in the manga page

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#272]
When you're in a manga page and press the phone physical option button to open the option menu, it doesn't work.
It does work in the global menu.
With the last travis

**Comment by raulhaag** [comment]
really i don't know why, i use hardbuttons on my tablet and works on main screen, on manga desc/chapter and both of readers (on readers the function is show the gui).

**Comment by Dostoi** [comment]
Well it's working with the last version now ^^
