### ISSUE TITLE
Add readcomiconline.to

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#276]
So I know it supposed to be a manga reader but is it possible to add this site http://readcomiconline.to/ as it seems to work the same way than kissmanga (I found the link on their main page).

Thanks in advance :)

**Comment by raulhaag** [comment]
ok ican try

**Comment by raulhaag** [comment]
owners are the same to both sites :-P

**Comment by Dostoi** [comment]
That's what I thought ^^

**Comment by raulhaag** [comment]
ready try it on travis

**Comment by raulhaag** [comment]
thigs to care about this site:
   the image are realy big (when i have time an get a good way to assume max size and scale on load to use less memory)

**Comment by Dostoi** [comment]
Thanks a lot !
Yes but I'll do with it for the time don't worry ^^

**Comment by Dostoi** [comment]
Did a quick test and everything seems to be fine. Thanks again :)

**Comment by Dostoi** [comment]
Two smalls issues :
- When in the scan list on the server menu, the icon on the top left is the one from kissmanga
- There's an encoding error in the genre list. The "&" in "movie & Tv" isn't shown correctly

**Comment by raulhaag** [comment]
ready wait travis compilation

**Comment by Dostoi** [comment]
Ok nice :+1:
