### ISSUE TITLE
The manga name is still showed after adding it if you're in search mode

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#283]
If you're searching for a manga, then add it, the app will automatically go back to the search result once the manga is added but the manga name wil still be showed at the top instead of the search bar

Happens with the last travis and kissmanga/readcomiconline

**Comment by xtj-9182** [comment]
some notes:
adding manga is not necessary. 
We change the title when we load the DetailsFragment in line 109.
And we never change it back. We set the title to "Mangas from + server" in 
ServerFilteredNavigationFragment line 77 and 123.

**Comment by xtj-9182** [comment]
it turned out we never called setTitle in the SearchResultsFragment's onResume method.
