### ISSUE TITLE
Add option to directly add to library from catalogue

### ISSUE THREAD

**Issue by sm7297** [raulhaag/MiMangaNu#284]
For example if we are on kissmanga server list manga will be displayed then if i long press on the certain manga it will give saying add to library or home this will increase the speed for adding large number of mangas

**Comment by xtj-9182** [comment]
side note: for some reason every time we load a DetailsFragment with the Manga Information it takes like 2-3 seconds which seems kinda slow. This would certainly be a good band aid for that.

**Comment by raulhaag** [comment]
ready
