### ISSUE TITLE
Can't check for update if no connection when launching the app but connection when checking

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#285]
If you launch the app without an internet connection, but activate it after launching the app. The app will still think that you don't have any internet connection and won't allow you to check for update.

With the last travis

**Comment by raulhaag** [comment]
Add manga works? I only test it on marshmallows because my cellphone have
it, I go to try it on emulator pre lollipop

**Comment by Dostoi** [comment]
Hum it's seems to be working in fact, my bad.
Before, you could check right away after enabling internet connection. But now you have to wait a bit for the app to notice that the connection is enabled (must be because it wasn't checking for it before) and allow to check for update.

**Comment by raulhaag** [comment]
Yes on wifi there is an Toast message but on data I can take a large time
and not announced
