### ISSUE TITLE
[Bug] When you hide all servers, there is no way to unhide them

### ISSUE THREAD

**Issue by xtj-9182** [raulhaag/MiMangaNu#286]
for testing purposes I tried hiding all servers and as it turns out when you hide all servers there is no way to unhide them anymore, you need at least one server to be able to trigger the Edit server UI. Maybe we could try hindering users from doing that, like we could show a dialog and tell them that at least one server needs to be visible or something like that. Edit: Or possibly we could have a reset to defaults setting in the settings

**Comment by Dostoi** [comment]
Wouldn't it be better to add the managing of the list as an option in the option menu ?
Because right now, it's not easy to know that you can manage it

**Comment by xtj-9182** [comment]
yeah that makes sense I just don't know about the implementation, currently we rely on having a server to click to trigger the edit server UI and I don't know how we would trigger the UI from the Preferences. 


That said I think it's trivial to have a reset to defaults option since we save the unused servers in an invisible "option" so we just need to clear that string to reset the server list.

**Comment by xtj-9182** [comment]
ok so I fixed my problem. @Dostoi  you might want to ping @raulhaag for the thing with accessing the edit server UI from the settings.
