### ISSUE TITLE
Manga Read

### ISSUE THREAD

**Issue by Sheiko222** [raulhaag/MiMangaNu#29]
to switch from one page to another , should be from right to left. Like a real Manga.

cambiar de una pagina a la otra con el sentido japones.

**Comment by Dostoi** [comment]
if it can only be an option please, I like it the way it is now ^^

**Comment by tenebr050** [comment]
Right, and not all manga are right-to-left. For example, the official English translations of Pokémon Adventures and Dragon Ball go left-to-right.

**Comment by raulhaag** [comment]
added on next version on chapter list menu
