### ISSUE TITLE
Can't download chapter from readcomiconline

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#296]
I'm getting an error when I try to download a chapter from readcomiconline
With the last travis from the master branch

**Comment by xtj-9182** [comment]
I can confirm this. I just tested it with commit 815fd4d4be0bb3b91c4fa8cb3c0b4956086d9be9 which is the one right before I made my recent commit so I think I didn't break it. I think it's caused by something that they changed on the site.

**Comment by raulhaag** [comment]
@xtj-9182  i don't know, i don't know :-P 
Just testing and any request of comic it make an capcha this is't showed
like this http://readcomiconline.to/Special/AreYouHuman?reUrl=%2fComic%2fUltimate-X-Men%2fIssue-70%3fid%3d26096
more info soon. maybe bad news?

**Comment by Dostoi** [comment]
Strange, it's not happening on kissmanga

**Comment by raulhaag** [comment]
i hope this don't extends to their other service, for now next official release don't go to have readcomic on the list for now, just because don't getting this working and official version is to outdated

**Comment by xtj-9182** [comment]
holy shit they added google recaptchas oh god :0

**Comment by raulhaag** [comment]
that's is not the base problem (can be implemented in an extreme case but to much work(popup etc)) the problem is every time you read a chapter (not like kissmanga before ~100) i go to make a release this weekend an for now is out 
@xtj-9182  any pr please before 03/07 using dd/mm

**Comment by xtj-9182** [comment]
yeah that seems overly zealous even if you try to read it on a normal browser :-1: 

@raulhaag yeah ok.

**Comment by raulhaag** [comment]
working on a way to get cf cookie with this http://developers-club.com/posts/258101/

**Comment by raulhaag** [comment]
@Dostoi ready for test last travis, that really gibme a headache but begin working, probabily need more work, but now im tired

**Comment by Dostoi** [comment]
It seems to be good
Don't exaust yourself too much with this, you're doing a great job !
