### ISSUE TITLE
Can't see the full chapter name if it's too long in the new chapter notification

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#297]
If a chapter name is too long, the notification won't show it but cut the end.
It would be better to make it go to the line if it's too long for the screen

**Comment by xtj-9182** [comment]
I can make the notifications expandable if you have android 4.1+

**Comment by xtj-9182** [comment]
![screenshot_20160629-202254](https://cloud.githubusercontent.com/assets/9414008/16464324/f99419e4-3e39-11e6-8d80-5e45c3d97fee.png)
![screenshot_20160629-202135](https://cloud.githubusercontent.com/assets/9414008/16464329/fe543450-3e39-11e6-80a6-26fa8d5b72a1.png)

**Comment by Dostoi** [comment]
Great ! :)
Will it work with the option to have only one notification for all update too ?

**Comment by xtj-9182** [comment]
you mean when we just show "New chapters were found (%s)" ? Currently no. Why would we need to make that expendable ?

**Comment by Dostoi** [comment]
Instead of having n notification, only one that you can expand and that show the list of all the new chapter name by manga
But if it's too much work don't bother

**Comment by xtj-9182** [comment]
I think they introduced that feature in Android N. I can probably add that for Android N once my LG G3 gets Android N via Cyanogenmod. For anything before N this is probably not possible.

**Comment by Dostoi** [comment]
Ok no problem

**Comment by xtj-9182** [comment]
I made some quick tests and I think your suggestion is possible on older android versions too with the limitation that I think I can only show at max 10 chapter titles in one notification. I think even though it's not optimal I think it's a good feature to have especially if it's optional.

here some pictures from current WIP:

![screenshot_20160630-183212](https://cloud.githubusercontent.com/assets/9414008/16505088/ac2dc7b2-3f1b-11e6-9843-aaed758f600b.png)
![screenshot_20160630-182954](https://cloud.githubusercontent.com/assets/9414008/16505091/b1842594-3f1b-11e6-8443-0df54c6cee47.png)

**Comment by xtj-9182** [comment]
@Dostoi @raulhaag anyone mind if I replace the current notification system with the new one ?

I will remove the one we use now that only shows "New chapters were found (%s)" and also the one that shows one notification per new chapter with the new one that shows one notification per manga that has new chapters as shown above. This way we don't need an extra setting and we can remove the one chapter per notification setting.

If no one has any complains that is.

**Comment by raulhaag** [comment]
I really like more single notification with list

**Comment by xtj-9182** [comment]
@raulhaag you mean the new system where we show one notification per new manga that has new chapters ? So should I go ahead and remove the one notification per chapter and the current default, and replace it with the new system ?

**Comment by raulhaag** [comment]
yes why not

**Comment by xtj-9182** [comment]
ok just wanted to make sure that I understand you correctly.

**Comment by xtj-9182** [comment]
@raulhaag ok I'm done PR is up. That should be all from me for 1.50.
