### ISSUE TITLE
Change the way the wifi only option work to prevent only for auto update

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#298]
It would be better if the wifi only option doesn't prevent the user from checking update if he want to manually do it without wifi but instead only prevent the auto update to check without wifi

**Comment by xtj-9182** [comment]
not sure about this. Use only WiFi implies that only WiFi is used. What if a user accidentally swipes down ? The expected behavior would be that the update fails if he is on mobile Internet. My opinion on this is that it's working as intended.

**Comment by Dostoi** [comment]
Yes I can understand but the feature I was talking about in #86 was to prevent the auto update of manga if the wifi isn't on. Not prevent the user from manually updating the list if the wifi isn't on.
If you want to let this feature, is it possible to have a new one preventing the auto-update of the app if the wifi isn't on.

**Comment by xtj-9182** [comment]
> Not prevent the user from manually updating the list if the wifi isn't on.

yeah that wasn't #86 that was #230 

> If you want to let this feature, is it possible to have a new one preventing the auto-update of the app if the wifi isn't on.

I thought we already did this. I'm not 100% sure since that was a chaotic merge and @raulhaag changed some of the network check code due to compatibility reasons I think. From what I remember I thought I implemented exactly what you asked for in #86 and also #230 too.

**Comment by raulhaag** [comment]
can be a second option only aviable when only wifi is not select, let me think about that

**Comment by Dostoi** [comment]
What I was asking was to prevent auto update without wifi but allow the user to manually do thing without or with wifi.

Ok thanks :)

**Comment by xtj-9182** [comment]
what about an option to disable wifi detection ? If you want to do a manual update you just activate that and then deactivate it so that auto update isn't updating without wifi.

**Comment by raulhaag** [comment]
one general otrer only for auto updates added
