### ISSUE TITLE
App crash sometimes

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#30]
The app crash sometimes when going back from an image to the chapter list.
It happens at the end of a chapter but in the middle of ti too. I didn't find a pattern so I can't really help. Maybe others have an idea.

**Comment by raulhaag** [comment]
Random errors are difficult to fix

**Comment by Dostoi** [comment]
Yeah I know that's why I was hopping someone else was having this error but manage to find pattern.
It's not very important anyway

**Comment by raulhaag** [comment]
if any can find a patter real, it go to be realy usefull

**Comment by raulhaag** [comment]
Still happening ?

**Comment by Dostoi** [comment]
I'm still having crash but not on the same issue ^^
It's not exactly the same, the app crash and restart on the main menu but I didn't find any typical behavior

**Comment by Dostoi** [comment]
And I'm not using the same phone. Now it's a alcatel one touch pop 2 with android 4.4.4

**Comment by Johndeep** [comment]
Up until now, some methods are creating threads. They (those many little threads) all are calling a main method from the main thread only, which can lead to crashes (well.. threads and parallel stuffs, always nasty work).

Especially random ones can happen, which is more likely due heavy load of many Manga at once.
With the patch #98 I _hopefully_ reduced those random crashes..

**Comment by Dostoi** [comment]
I'll give feedback on it then :)

**Comment by Johndeep** [comment]
The initial issue
>The app crash sometimes when going back from an image to the chapter list.
It happens at the end of a chapter but in the middle of ti too. [...]

is most likely happening, because of those still not correctly handled random null pointers.. now this is getting deep into the heart of this jungle, wohoo.. :sweat_smile:

By the way, does the app just reloads after crash? Or does it throw you out entirely?

**Comment by Dostoi** [comment]
From what I remember it reload in general

**Comment by xken2x** [comment]
close the thread if the problem has been solved

**Comment by Dostoi** [comment]
Yes, don't worry.
The thing is, I'm not sure if it still happen as it didn't happen often in the end ^^

**Comment by Dostoi** [comment]
Still happening from time to time and while doing totally different stuffs, so ^^

**Comment by Johndeep** [comment]
I'm gradually also wondering where the heck those crashes come from.. still.. trying to fix them if there is time, but they keep popping up here and there.. mostly null pointer errors.

**Comment by Gomgoru** [comment]
@Johndeep it's happening to me as well. 

Sometimes it happens: Within minutes of the last time **MiMangaNu** crashed/stopped; Other times it happens several times in a day; Other times it happens several times in a week or once every couple of weeks. I'm seeing these crashes quite often, **on the order** of _two to three times a week_!

So far I've not seen a repeatable set of steps. The only thing I've seen that appears to repeat is _I've almost always been using **MiMangaNu** for **at least an hour or more!** and quite often after clicking the  :leftwards_arrow_with_hook: [Return_Button]. While it does crash almost immediately after a previous crash, it is **very rare!**_

Most of the time **MiMangaNu** restarts to the main __Select_Manga__ screen. Other times **MiMangaNu** does not restart. I can't remember if **MiMangaNu** ever restarted at some other page though.

I'll try to see what I can do to get more info on the crashes that are happening on my machine and insert the revelent into this issue discussion. Maybe I'll have to start a  :notebook: _Defect Detection Journal_  :notebook: :smiling_imp:  :weary: \<sigh\> (I prefer debugging in `machine code!`  :yum:)

Sincerely, Gomgoru  :pray: :mount_fuji: :smiling_imp:

**Comment by Johndeep** [comment]
Now that I also have those frequent crashed while reading, I tried to read manga while obeserving per debugging with Android Studio, and see there, I found a new hint! (Or reason why it crashes while reading)

The times it crashes, the debugger called for not enough size to allocate.
What you can try is to decrease the texture size from 2048 to 1024 for now and test it again.
I noticed that it stopped crashing, for me at least.

**Comment by xtj-9182** [comment]
everyone should retest with v1.49 and check if it still happens, since that version fixed a memory leak in Android 5+

**Comment by Dostoi** [comment]
It doesn't seem to happen anymore. Nice work !

**Comment by xtj-9182** [comment]
woohoo ! It was probably the Memory Leak that raul fixed. Finally we can close this long standing issue.
