### ISSUE TITLE
Añadir leomanga.com

### ISSUE THREAD

**Issue by jikanleaper00** [raulhaag/MiMangaNu#300]
Si fuera posible añadirlo. Y en la busqueda de tumangaonline aparecen los mismos 20 mangas independiente de lo que escribas.

**Comment by raulhaag** [comment]
creo que no seria problema pero por ahora estoy tratando de cerrar un poco todo para la proxima release despues de eso veo si se puede agregar sin problemas

**Comment by raulhaag** [comment]
agregado cuando salga en fdroid la 1.52 va a estar

**Comment by jikanleaper00** [comment]
Muchas gracias. Esta es la mejor app de manga.
