### ISSUE TITLE
About that WIP Reader

### ISSUE THREAD

**Issue by xtj-9182** [raulhaag/MiMangaNu#305]
@raulhaag 
so I know it's still WIP but in case you didn't notice
1. the paged reader won't currently show any menu
2. the Left and Right taps only zoom in in paged reader
3. I'm getting an Exception sometimes when trying to scroll past the first page of a chapter in L2R in paged reader mode
`FATAL EXCEPTION: main
                                                                       Process: ar.rulosoft.mimanganu, PID: 23486
                                                                       Theme: themes:{}
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'boolean ar.rulosoft.mimanganu.componentes.readers.paged.PagedReader$Page.canScroll(int)' on a null object reference
                                                                           at ar.rulosoft.mimanganu.componentes.readers.paged.L2RPagedReader.onInterceptTouchEvent(L2RPagedReader.java:46)`

**Comment by raulhaag** [comment]
Yes I know but I use github to pass it from desktop to laptop

**Comment by xtj-9182** [comment]
ok just wanted to make sure you know about it.

**Comment by raulhaag** [comment]
reader are ready for test if you can help whit it
