### ISSUE TITLE
Latest Travis Build Fails to Mark as Read.

### ISSUE THREAD

**Issue by digiwombat** [raulhaag/MiMangaNu#306]
More specifically, the latest build (d42fac053896788483710ec2c5296e983bedeecf) doesn't mark the most recent chapter as read when you finish reading it.

This seems to be related to the new seamless read function, which also occasionally fails to advance to the next chapter and likewise sometimes fails to auto download the next chapter when that is selected, but I don't have solid reproductions for those yet.

**Comment by Johndeep** [comment]
I want to second it.

Also, can't you get back the extra page with "previous" and "next" option (with dark and bright theme included this time)? It was much easier to handle with than the currently annoying pop-up.

Also, isn't the threshold for the "next chapter" trigger TOO INSTANT? At least let the user swipe a bit before it triggers.. (pss, just use the extra page, much better)

**Comment by xtj-9182** [comment]
@digiwombat @Johndeep also ping @raulhaag 
currently much of the reader stuff is being reworked so it might be buggy. Are these bugs happening with stable 1.51 ?

> Also, can't you get back the extra page with "previous" and "next" option (with dark and bright theme included this time)? It was much easier to handle with than the currently annoying pop-up.

can you elaborate a little bit I'm not really sure what you mean.

> Also, isn't the threshold for the "next chapter" trigger TOO INSTANT? At least let the user swipe a bit before it triggers.. (pss, just use the extra page, much better)

some of this might be WIP currently so it might be changed soon. I'm not too deep into the reader code but Raul changed a lot recently.

**Comment by raulhaag** [comment]
@Johndeep  ok i know what you mean about too instant when i finish whit the branch im working on that not go to be a problem, about to going back to last page no. 
@digiwombat that commit on finish to change all the sdk to last, now i need to find why same funtions are not working, meanwhile you can use an early version (only change Android sdk & jdk)

**Comment by raulhaag** [comment]
Sorry by error merge the two branches that was the error

**Comment by Johndeep** [comment]
@raulhaag Nah, no problem, I just didn't see that change coming. According to the commit changes and @xtj-9182, there were many changes, right?
But well, as long as it still in the development branch, everything is fixable..

**Comment by raulhaag** [comment]
@Johndeep merge not planed juat my error 
last travis ready for test, i hope not forget nothing

**Comment by digiwombat** [comment]
Latest travis update (build 281).

It's now marking as read and deleting properly however it now crashes to desktop/home screen when finishing a final chapter.

A related bug, I suspect, is that the reader now crashes back to the chapter list when rotating the screen while the reader is up. No crash occurs while rotating on the chapter list itself.

**Comment by raulhaag** [comment]
can't recreate test last if still hapens

**Comment by digiwombat** [comment]
Okay. Still happens on Build 282. But ONLY happens in the Paged Reader. Both errors still occur. The orientation change close AND the end-of-last-chapter change.

My guess is that there is something crashing on the close/dispose of the paged reader since that seems to be the common factor (finishing last chapter will outright close the reader, and changing orientation seems to dispose of the reader and re-load it).

**Comment by raulhaag** [comment]
@digiwombat can you guide step/step and tell me if sealess activated/ delete activated, to try to fix and please in separated messages.

**Comment by digiwombat** [comment]
Seamless deactivated.
Open any chapter, rotate tablet, crashes to chapter list.
https://gfycat.com/MajesticGlassFruitbat

Same happens on finishing last chapter, regardless of rotation. Crashes to desktop.

**Comment by raulhaag** [comment]
i try the same as the video but not hapens, im fix some acra reported errors around there just test the Build  285

**Comment by digiwombat** [comment]
Fixed in build 285. Haha.
