### ISSUE TITLE
Bug: Read direction option doesn't work in v1.51

### ISSUE THREAD

**Issue by wyrex** [raulhaag/MiMangaNu#307]
I just updated F-droid version from 1.49 to 1.51 and read direction is now always left to right (swipe from right to left) instead of right to left I used to have. Option doesn't change this.

**Comment by raulhaag** [comment]
I downloaded and tested the v1.51 from fdroid and work check the default on
your coonfiguration maybe the default changed

**Comment by wyrex** [comment]
It suddenly started working, after force closing and clearing cache third time.
