### ISSUE TITLE
Fallo al añadir manga desde TMO 

### ISSUE THREAD

**Issue by cristfcb** [raulhaag/MiMangaNu#308]
Al querer añadir algún manga desde TMO no añade todos los capítulos que tiene el manga, si no solamente 25.... Esto solamente ocurre con la última versión.
La ultima versión me encanta, el único fallo que le encuentro es este que menciono.

**Comment by raulhaag** [comment]
estoy al tanto pero estoy ahora trabajando en el lector unificandolo, cuando termine con eso voy a arregar un par de cosas como fastUpdate / fullUpdate (para que en las busquedas rapidas solo chequee los ultimos (y algo parecido me quedo activado en tmo))

**Comment by cristfcb** [comment]
OK... Una cosa mas, al momento de cambiar la carpeta de los mangas a la tarjeta SD hay el problema que al leer los mangas la transición de página a página tiene mucho lag, así como también al momento de abrirlos,  no se si eso tenga alguna solución o si ya de plano es imposible..... Al fin de cuentas gracias por tu atención y excelente trabajo con la app cada vez mejora más.

**Comment by raulhaag** [comment]
si lo probaste en la memoria del telefono y era diferente de base te diria que el problema es casi seguro de la velocidad de la tarjeta o de la velocidad de acceso a ella dada por el telefonno yo uso una sandisk ultra y no me da problemas pero cada dispositivo es un mundo diferente igual reescribi gran parte del los lectores en estos dias asi que proba la proxima version cuando este lista

**Comment by cristfcb** [comment]
Como dices, creo que mi tarjeta es el problema, optaré por cambiarla. 
OK entonces esperare la próxima versión también. Gracias.
