### ISSUE TITLE
Showing the number of chapter available in the manga description

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#309]
It could be nice to know the number of chapter available in the manga description before choosing to add it to our database.
For example if we don't want to add a manga which only has one chapter available, or if we know that a manga has more chapter than that and we want to look for it on another server

**Comment by raulhaag** [comment]
ready aside on server name on servers that preoload chapters (all exept tmo)
![chapters preview](https://cloud.githubusercontent.com/assets/2048339/17063084/ff979f80-500b-11e6-9ca5-0ffa775ab2d1.jpg)

**Comment by Dostoi** [comment]
Thanks :)
