### ISSUE TITLE
error al obtener numero de paginas

### ISSUE THREAD

**Issue by Sheiko222** [raulhaag/MiMangaNu#31]
Tira este error al intentar abrir un capitulo de esninemanga.

**Comment by raulhaag** [comment]
ahí lo arregle espero que entre en la próxima actulización de f-droid

**Comment by Sheiko222** [comment]
Gracias

**Comment by raulhaag** [comment]
No entro en esta versión, la próxima

**Comment by Sheiko222** [comment]
Me di cuenta, no importa, era una critica constructiva. Gracias por molestarte.

**Comment by raulhaag** [comment]
igual ya hice los commit para que salga lo antes posible (tengo que programar una utilidad que chequee los server pero no ando con mucho tiempo)
