### ISSUE TITLE
Feature request - FromFolder auto add new

### ISSUE THREAD

**Issue by Flu-Ger** [raulhaag/MiMangaNu#310]
I have a device, I don't want internet on, but I download mangas from my computer and copy them to my device.
I would love if MiMangaNu could automatically detect new folders/chapters (in the download directory?) and add them to the collection. When the collection is relatively big, it gets bothersome to add new ones manually.

**Comment by xtj-9182** [comment]
I've been thinking about this. 

I could probably add this to the update process, so that a user selects a folder in the settings and then when the update process runs it will also check this folder and add new folders as Mangas. I need to run some tests since so far I've only been thinking and not yet tinkering.

**Comment by Flu-Ger** [comment]
Sounds good.
Instead of selecting an additional folder, scanning the folder users select for the cache (in settings under "download settings")? Should be faster to test and might suffice for the beginning.
More complex could be to check when FromFolder is added, whether it's a single manga or multiples
and check for new in there too, if it is?

**Comment by xtj-9182** [comment]
a little update I'm almost done with this.

Here is what I'm going to do:
first I'm adding a setting to import all sub folders in a path so you can import multiple folders at once.
Second as I had proposed I'm going to add an option to choose a path which will be checked after
the normal update process and all folders in that will be added as manga if they haven't already been added.
