### ISSUE TITLE
local folders don't update without WIFI

### ISSUE THREAD

**Issue by Flu-Ger** [raulhaag/MiMangaNu#311]
When "use only WIFI" is active, no new chapters are searched.
But local folders should be searched though non the less.
This misbehaviour only occurs in global update, if I manually search for update on a certain series, it works as expected.

**Comment by xtj-9182** [comment]
Is this still happening ? I can't reproduce with latest travis build.

**Comment by Flu-Ger** [comment]
I tried with 1.55 from f-droid and got the following error

System.err: ar.rulosoft.mimanganu.Exceptions.NoWifiException: No WiFi connection
System.err:    at ar.rulosoft.mimanganu.utils.NetworkUtilsAndReciever.isConnected(NetworkUtilsAndReciever.java:43)
System.err:    at ar.rulosoft.mimanganu.utils.NetworkUtilsAndReciever.onReceive(NetworkUtilsAndReciever.java:151)
System.err:    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2759)
System.err:    at android.app.ActivityThread.-wrap14(ActivityThread.java)
System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:    at android.os.Looper.loop(Looper.java:148)
System.err:    at android.app.ActivityThread.main(ActivityThread.java:5461)
System.err:    at java.lang.reflect.Method.invoke(Native Method)
System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by xtj-9182** [comment]
that exception means that there is no wifi connection, it's thrown when there is no wifi connection.

I think that I don't understand your problem yet.

If I use "use only WiFi" then the global update search works as long as I have a WiFi connection. If I lose WiFi connection I get the above mentioned exception which is normal it indicates that there is no WiFi connection. This behavior is forced with the "use only WiFi" setting.  "use only WiFi" is meant to avoid data plan cost that comes with using 3g/4g/lte networks. What kind of behavior are you expecting ?

**Comment by xtj-9182** [comment]
I've got something. Soo we somehow forgot about FromFolder Mangas and I didn't understand your Issue cause you referred to it as local folder but internally we only refer to it as FromFolder Mangas anyway I have a fix that will make it so that if no Internet or WiFi connection is found FromFolder Mangas will still be checked, this will also apply to the automatic update so you can also use that.

**Comment by Flu-Ger** [comment]
Yes I meant FromFolders, sorry for the misunderstanding ...
the patch looks promising, thanks you
