### ISSUE TITLE
Swipe to next back future request

### ISSUE THREAD

**Issue by lenisko** [raulhaag/MiMangaNu#313]
Last updates bring us awesome future where by swiping on start / end of chapter we can change them. There is just one problem, it's too fast. Sometimes it's triggered by mistake. My idea is to create some progress bar so if we swipe down and hold our finger it will start counting like 1-2 seconds and will switch chapter.

**Comment by raulhaag** [comment]
ok now use an fast swipe to change between chapters test last travis

**Comment by raulhaag** [comment]
closed, re open if needed
