### ISSUE TITLE
Update manga status ongoing/finiahed

### ISSUE THREAD

**Issue by lenisko** [raulhaag/MiMangaNu#314]
This one is not working like it should I mean If manga is finished, change status to complete (in app) and don't update it anymore. Status updating is not working (maybe data is not fetched)

**Comment by Dostoi** [comment]
There's an option to update finished manga. But by default it's not updated from what I understood

**Comment by lenisko** [comment]
Lets say we have following example:
1. User started reading ongoing manga
2. Manga got finished
3. When updating, status should change in application to "Complete" right now it's not.

**Comment by Dostoi** [comment]
Ho ok my bad I wasn't talking about that. I have no idea then ^^

**Comment by raulhaag** [comment]
isn't easy to test but the code is there and its executed on every update
```java
        if (mangaDb.isFinished() != manga.isFinished()) {
            mangaDb.setFinished(manga.isFinished());
            changes = true;
```
tell me the server to check it if it imfor the progress well
update finised manga is to find updated for any extra added after the manga was complete

**Comment by lenisko** [comment]
So it's server related mhm. Most times I'm using KissManga

**Comment by raulhaag** [comment]
teste kissmanga and working as spected, please teke note of manga an server to test i teste with naruto7 kissmanga editing the db value and work as espected
https://gfycat.com/MinorDangerousHamster

**Comment by lenisko** [comment]
Sorry you are right
