### ISSUE TITLE
Option to disable fullscreen

### ISSUE THREAD

**Issue by jsteel44** [raulhaag/MiMangaNu#317]
Hi,
Can you add an option to disable fullscreen? I would like the top bar (time, battery etc) and the home and back button always shown, without having to tap the screen first.
Thanks

**Comment by xtj-9182** [comment]
I'm almost done with this. My PR should be up tomorrow or so.

**Comment by xtj-9182** [comment]
do note that this option is hidden behind a kitkat check. So it only works on kitkat+ (currently).

**Comment by jsteel44** [comment]
Thanks for adding this option! I'm happy with it, but just thought I would report back that it overlaps almost half of the action bar. Not a big issue but would be nice if it didn't. Cheers

**Comment by raulhaag** [comment]
ready for next (a kind of hack just buacuase android don't acts as expected) version if you have f-droid it go to take a time.
