### ISSUE TITLE
Boeing able to change the speed by 0,25 and not 0,5

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#318]
Right now we can only change the reader speed by 0,5 but it's not precise enough sometimes. 1,0 is too slow and 1,5 too fast ^^
Is it possible to change the speed by 0,25 instead of 0,5 ?

**Comment by raulhaag** [comment]
i think it's possible.

**Comment by Dostoi** [comment]
Thanks :)
