### ISSUE TITLE
Auto update doesn't update all manga

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#319]
Auto update only update 3/4 of the manga updated with the manual update

**Comment by raulhaag** [comment]
in only i can think is in the firsts get bad request before awake the connections on same devices

**Comment by Dostoi** [comment]
It's not that, I think it's because the auto update doesn't check finished manga.

Manual update :
![screenshot_2016-08-11-11-27-45](https://cloud.githubusercontent.com/assets/7694864/17584425/b9e99744-5fb6-11e6-8afb-feb47b6ef736.png)

Auto update :
![screenshot_2016-07-28-16-44-08](https://cloud.githubusercontent.com/assets/7694864/17584431/bd773ab0-5fb6-11e6-8432-49c5ce640723.png)

**Comment by raulhaag** [comment]
ok that make the things more simple, thanks
