### ISSUE TITLE
Downloading status displays in Spanish

### ISSUE THREAD

**Issue by tenebr050** [raulhaag/MiMangaNu#32]
On my KitKat device, the system language is set to English, but the downloading status appears in Spanish.

![](https://img.bi/#/15hVXXO!XWDb6Ka3NPVsEwfJnOZvh8WdudnezNnlHv1ak3tx)

**Comment by Dostoi** [comment]
Same here

**Comment by raulhaag** [comment]
not an error just i used the enum name, next version added support traslation (1.13)
