### ISSUE TITLE
The reader go to the end of the next chapter when changing chapter

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#323]
When I swipe to go to the next chapter, the reader go to the end of the chapter. It only seems to happens when reading from right to left.
Like if I reach the end of chapter 44 of a manga and swipe to go to the beginning of the next one, the reader begins at the end of the chapter 45

I'm using the continuous reader with the seamless transition

**Comment by raulhaag** [comment]
ready

**Comment by Dostoi** [comment]
Thanks again :)

**Comment by Dostoi** [comment]
Thanks again :)
