### ISSUE TITLE
[Bug] Snackbar won't show if DownloadsFragment was opened

### ISSUE THREAD

**Issue by xtj-9182** [raulhaag/MiMangaNu#326]
@raulhaag 
using latest commit (220df44a54f6c1dfbe34fe701b7d8939f296a51a)
1. go to any manga and download any chapter, snackbar will show "manga added to downloads"
2. go to DownloadsFragment
3. go back and try downloading any chapter 
-> snackbar won't show anymore. If you go back to the MainFragment and back into the Manga the Snackbar shows up again.

Also on the technical side do we really need to use a CoordinatorLayout and a MainActivity as Parameters for the showFastSnackbar method? Wouldn't it be better to use a View and a Context respectively ?

**Comment by raulhaag** [comment]
i use mainActivity for the colors acces and context at same time and coodination layout just becouse if i don't use it floating action buttons are blocked when snackbar is visible.(https://material.google.com/components/snackbars-toasts.html#snackbars-toasts-usage)
still need to add snackbars for confimation messages, etc.
