### ISSUE TITLE
Add option in Update interval 

### ISSUE THREAD

**Issue by sm7297** [raulhaag/MiMangaNu#333]
It will be good if another option will be added to Update interval submenu like "Update when started" like when you start Mimanganu it will start checking for update rather than manual updating

**Comment by Dostoi** [comment]
And add option like "check at every start" or "check once a day"

**Comment by xtj-9182** [comment]
@Dostoi "check once a day" is already possible, we have update intervals already implemented and check once a day is an option already. Having said that I have never actually used update intervals since I always do manual updates.

**Comment by Dostoi** [comment]
I mean check on app start only once a day. Not like it's actually done

**Comment by Dostoi** [comment]
But update intervalle are working

**Comment by xtj-9182** [comment]
I think I know what you mean now.

on a side note I just checked some of the code of the AlarmReceiver and I just noticed that we use a completely different notification for the automatic update, which seems kinda inconsistent, I think I'm going to make the notification more consistent with what we use for manual updates.

**Comment by xtj-9182** [comment]
@sm7297 @Dostoi What do you understand as start up ? I was thinking that when selected in the options that it would check for updates at start up but only when the app has been started from a cold start, as in it hasn't been started before and once it resides in the memory it won't check for updates on start unless it is ejected from memory using something like greenify or if android ejects it due to other apps needing the memory, so that it would only check for updates on start up if it's a cold start.

**Comment by sm7297** [comment]
Yes update on cold start is what I am asking for

**Comment by xtj-9182** [comment]
okay, I have a prototype that's working well on my side and doing the update at cold start I'll add the PR later today.

**Comment by Dostoi** [comment]
Great, thanks :)

**Comment by xtj-9182** [comment]
@sm7297 @Dostoi 
Any feedback ? Is it fixed or are there any outstanding bugs or enhancement requests ?

**Comment by Dostoi** [comment]
Is it possible to have an option that uptdate at start up only every few hours
Right now the app check at every start Up which is too often if I open it several time in an hour

**Comment by Dostoi** [comment]
1 day is good for me :)

**Comment by xtj-9182** [comment]
too late now I also added 6 and 12 hours as options :p

**Comment by Dostoi** [comment]
Ok ^^
No problem, i'll test it as soon as i can

**Comment by Dostoi** [comment]
It seems to be good :)

**Comment by xtj-9182** [comment]
good to hear :)

**Comment by Dostoi** [comment]
Just an issue.
If you open the app with no connection a message show up "No connection (todo)" ^^

**Comment by xtj-9182** [comment]
fuck I forgot to update the string to the localized one

**Comment by xtj-9182** [comment]
ok I think closing this issue is adequate seeing how it has been resolved.
