### ISSUE TITLE
Add gogomanga and add to library option from results in servers

### ISSUE THREAD

**Issue by sm7297** [raulhaag/MiMangaNu#334]
We can add manga from homescreen of server but when we search we can't add from search result directly

**Comment by xtj-9182** [comment]
I got a prototype for the "adding stuff from search results" stuff

**Comment by raulhaag** [comment]
the url ? is it http://gogomanga.co/ or http://gogomanga.se/ ? 
what it has better?

**Comment by xtj-9182** [comment]
I think http://gogomanga.co/ since that comes up first in a google search for the term gogomanga. @sm7297 please clarify

**Comment by sm7297** [comment]
sorry for the late response    the link you have given is same as i was talking about but now it given like this http://www1.gogomanga.to/

**Comment by xtj-9182** [comment]
thx now @raulhaag can try to implement it when he isn't busy.

**Comment by xtj-9182** [comment]
@sm7297 
I just looked at the site again and I don't think adding gogomanga is a good idea.
I looked at this chapter:
http://www1.gogomanga.to/shokugeki-no-soma/shokugeki-no-soma-179.html
as you can see on the first few pages there are watermarks from multiple different sites on there
including mangareader.net (which we already have), mangafast.online and marumaru.in .
I mean who is going to use a site that uses so many watermarks ? One can barely see the chapter o.O .

**Comment by raulhaag** [comment]
@xtj-9182 had the reason i don't see this as a good source having a lot of better sources in english
