### ISSUE TITLE
Download error on kissmanga

### ISSUE THREAD

**Issue by AxezCore** [raulhaag/MiMangaNu#336]
I've come across a rather peculiar problem, whenever I try to download new chapters for all my subscribed series on kissmanga it returns with a (Error) message instantly, same happens if I add a new series, the peculiar part being that I have no problem downloading chapters I already read from the same source. Also tried adding manga from a different source and have no issues downloading them.

EDIT: Just went on their website from my desktop instead and it asked me to confirm I wasn't a robot as soon as I tried loading a new chapter which has never happened before, after doing so I can download through the mi manga app again, I guess it remembers my ip and knows i'm not a robot now.

**Comment by Dostoi** [comment]
There's a capcha check after downloading 20 chapters on kissmanga

**Comment by raulhaag** [comment]
it's the kissmanga anti-leech, it's happens to me only one time (around 100 chapters) but can't be recreated easy to get the capcha from mmn (jus't open kissmanga on browser)
