### ISSUE TITLE
View one chapter in one page

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#34]
Is it possible to have an alternate view of the page that allow to see a whole chapter in one page and you just have to scroll down to see the next page ?
Sort of like kissmanga allow. it could be usefull for some manga where the page is cut in half (like hive http://kissmanga.com/Manga/Hive or distant sky http://kissmanga.com/Manga/Distant-Sky). It happens a lot with webcomic.

**Comment by raulhaag** [comment]
ok, perhaps an vertical ViewPager (an option like L2R, R2L), beacuse load all pages go to make a lot of out of memory,  let me see i don't promise anything, but go to be usefull for cellphones.

**Comment by Dostoi** [comment]
Or maybe only loading only some pages in advance and show them as we scroll. Like when you reach the end of the first page, the second will be just under it, already shown and the next one will be loading.
I don't know if I'm clear ^^

**Comment by raulhaag** [comment]
Viewpager do that

**Comment by raulhaag** [comment]
in last version 1.15 added as read direction L2R,R2L,VERTICAL

**Comment by Dostoi** [comment]
Perfect :)

**Comment by raulhaag** [comment]
did tou test it?

**Comment by Dostoi** [comment]
Yes it's great
