### ISSUE TITLE
left overs from #337

### ISSUE THREAD

**Issue by xtj-9182** [raulhaag/MiMangaNu#344]
from https://github.com/raulhaag/MiMangaNu/issues/337

> Canceling an update still open the app. Not sure if I was clear with open the app.
Like if you launch an update, leave the app but not close it (leave it runing in the background but having another app in the foreground), and click on cancel, the app will come to the foreground and put the app you were using in the background

@Dostoi 
sorry I didn't see your response since the issue was closed; anyway I'll look into it.

~~Did this work with the old automatic update notification ? I'm not seeing any code for a cancel action in the old code, how did it work before ?~~

never mind I fixed it.

**Comment by Dostoi** [comment]
Don't worry it's ok. Thanks for the quick fix :)
