### ISSUE TITLE
Add the time of last update in the manga description

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#347]
Hi, it's been a long time since my last feature request :P 

It could be nice to have the time of last update in the manga description to know if the manga isn't updated anymore and that there's no need to wait for a update on this server and that you should search elsewhere

**Comment by xtj-9182** [comment]
something like this: ?

![2016_10_11_11 20 50](https://cloud.githubusercontent.com/assets/9414008/19265579/f192244e-8fa5-11e6-9335-7e09fa75980d.png)

only concern I have is that cover images look odd 
due to the added line which makes them seem smaller
than before even though the size is the same.

here is an image of how it looked before:
![2016_10_11_11 17 24](https://cloud.githubusercontent.com/assets/9414008/19265651/3f978562-8fa6-11e6-9325-907ce4699681.png)

I probably have to add a date field to the manga table I think. 
So far I'm only experimenting with the look.

**Comment by Dostoi** [comment]
Yes that's exactly what I wanted ^^
I don't know how to change it

**Comment by xtj-9182** [comment]
ok I only need to figure out the logic behind setting and saving the date 
since I probably need to change the database which I haven't done before.

after I get that done we can do like a test run to see if people like the new change.

**Comment by Dostoi** [comment]
Ok no problem, it's not urgent anyway

**Comment by raulhaag** [comment]
@xtj-9182 if you want i can add the field at manga table, or just on database.java change version of db ,read line 738 to upgrade ones,  and don't forget new databases created.

**Comment by xtj-9182** [comment]
> if you want i can add the field at manga table, or just on database.java change version of db ,read line 783 to upgrade ones, 

yeah I think I can do that 
I was thinking something like this:
```
        if(oldVersion < 14){
            db.execSQL("ALTER TABLE " + TABLE_MANGA + " ADD COLUMN " + COL_LAST_UPDATE + " TEXT DEFAULT 'N/A'");
        }
```

> and don't forget new databases created.

oh yeah almost forgot about that one.

**Comment by raulhaag** [comment]
@xtj-9182 it's ok,  don't remove the others :+1:

**Comment by xtj-9182** [comment]
why would I remove the others ? xD, we still have people on old versions. going back to v1.51 probably even earlier since I only started implementing acra around 1.51.

**Comment by raulhaag** [comment]
Never know

**Comment by xtj-9182** [comment]
ok got a first working prototype
I'm gonna PR soonTM

**Comment by Dostoi** [comment]
I'm going to test it

**Comment by Dostoi** [comment]
When is updated las update value ? When a new chapter is found ? 
For the cover which look smaller, maybe reducing the size of the right column ?

**Comment by xtj-9182** [comment]
> When is updated las update value ? When a new chapter is found ? 

yes

> For the cover which look smaller, maybe reducing the size of the right column ?

I'm wondering what would happen if there are a lot of genre though, not sure ...

**Comment by Dostoi** [comment]
I noticed it's only shown on the manga present on the phone and note on the server list.

Is it possible to get the time of last update from the server and not from the last new chapter found ? I know that kissmanga show it on the website. http://kissmanga.com/Manga/Naruto
This way it could be shown on the server list too and be more accurate

**Comment by xtj-9182** [comment]
> Is it possible to get the time of last update from the server and not from the last new chapter found ? I know that kissmanga show it on the website. http://kissmanga.com/Manga/Naruto
This way it could be shown on the server list too and be more accurate

meh this would require potentially unique code for every server to detect this last updated chapter date. This is not at all what I had in mind. @raulhaag is better at this website stuff.

I wonder if we could detect the upload date for every chapter and display it underneath the chapter name, I saw that there is such a thing as a subitem which could be the upload date of the chapter whereas the chaptername is the item in the listview we use. 

This is a feature that I want but I don't want to implement it xD.

**Comment by raulhaag** [comment]
@Dostoi it's possible but not all servers support it and was needed a different implementation by any sever xtj-9182 implementation its usefull to know last update at a folowing manga

**Comment by xtj-9182** [comment]
I agree with raul :D.

**Comment by Dostoi** [comment]
No problem ^^
I'll go with what you'll do anyway :)
