### ISSUE TITLE
Manga with new chapter aren't shown after auto-update

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#349]
If a new chapter of a manga is found with the auto-update on start, the manga isn't moved to the top in the manga list and there's no star on it. You have to manually refresh the manga list to have the right order and the star on the manga cover.

I noticed it because I let the app run in the foreground when the auto-update launch and just wait for it to end and see if there's a new manga found.

**Comment by xtj-9182** [comment]
yes that is how auto update works we don't call setListManga (which is what triggers the moving mangas with new chapter to the front with recently read sort) cause the method is not easily accessible from the automaticUpdateTask Class. The reason why we can call setListManga with the manual update is cause the method is a part of the MainFragment Class. I just checked the old source code for the old auto update before I rewrote it and indeed that class also can't call setListManga.

What I tried to do initially was to use the manual update when doing the start up update but I realized soon after that this would cause a crash in some cases on my device, especially if I restarted my device.

The only solution here is to try to call the manual update at start up but I'm not sure if that's doable, I'll look into it and report back with my findings...

**Comment by xtj-9182** [comment]
ok I think I have a new prototype for this.

I managed to switch the update at start up code to use the manual update and it's not crashing on my device.

**Comment by Dostoi** [comment]
It seems to be good :)

**Comment by xtj-9182** [comment]
good to hear. This bug will be closed soon.
