### ISSUE TITLE
Always having a new chapter icon but there is no new chapter

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#35]
Some manga always have the new chapter icon when I look for update but they don't have any new chapter and even with the whole manga mark as read.
It happens with naruto but I don't remember from which site I took it.

**Comment by raulhaag** [comment]
Server name and Manga?

**Comment by raulhaag** [comment]
i don't remember but a few days ago a note an problem on one of the english server (its loaded the chapter list twice and at insert repeated are not allowed and giving theat error) i fix all server yesterday and make update more efficient, just check whe the next version (actual commit) if aviable if you still getting the problem ( the server icon on mis mangas not commited yet)

**Comment by Dostoi** [comment]
Ok I'll tell you if it's still there with the next version

**Comment by Dostoi** [comment]
The last update fixed it
