### ISSUE TITLE
If i reader into landscape mode after reading complete chapter pressing back button manga list also display landscape

### ISSUE THREAD

**Issue by sm7297** [raulhaag/MiMangaNu#353]

**Comment by xtj-9182** [comment]
stupid question but should I just make it so that it changes direction to portrait when you press back ? Was this how it worked before ?

**Comment by raulhaag** [comment]
Is my error, I forgive remove to remove screen otation lock

**Comment by xtj-9182** [comment]
so is my fix correct ? or did you intent to do it differently ?

**Comment by raulhaag** [comment]
@xtj-9182  on back press work well :+1:

**Comment by xtj-9182** [comment]
ok good to know :)
