### ISSUE TITLE
CI Server Down

### ISSUE THREAD

**Issue by null-dev** [raulhaag/MiMangaNu#355]
I'm just creating this issue to let you know that I am aware that my CI server is down.

Unfortunately, it appears like my hosting account was suspended for high CPU usage. They have deleted all the files on the server.

Fortunately, I do have backups of 90% of the builds excluding some of the most recent ones.

I will be moving the CI server to a VPS which has more bandwidth and has a higher CPU cap ASAP.
If you wish to use your own hosting service instead, feel free to!

**Comment by null-dev** [comment]
It looks like you have migrated to your own host, so I will be closing this issue.

**Comment by null-dev** [comment]
Actually, if you still want the old builds, I have my backup of them here: http://dl.nulldev.xyz/tmp/mmn-build-backup.zip

**Comment by xtj-9182** [comment]
Thank you, I have downloaded the backup just in case. Unfortunately @raulhaag is a little busy so he's only around like once or twice a week, I have no idea what his plan is.

**Comment by raulhaag** [comment]
I opened a free account in byehost just for this, ci version are for last repository updates and mantain old version is not necesary, so don't brother about that.
