### ISSUE TITLE
[bug] new multifilter looks odd on some devices

### ISSUE THREAD

**Issue by xtj-9182** [raulhaag/MiMangaNu#356]
@raulhaag 
using NineManga as my source, this is how the new Multifilter looks on three of my devices:

Starting with my Samsung Galaxy Tab S 8.4:
![2016_11_07_15 17 15](https://cloud.githubusercontent.com/assets/9414008/20062053/8cc7de42-a502-11e6-93f4-85bdf82f7c83.png)

Samsung Galaxy S7:
![2016_11_07_15 25 58](https://cloud.githubusercontent.com/assets/9414008/20062066/9cd76d7a-a502-11e6-9fc5-bb69dfbca1d1.png)

LG G3:
![screenshot_20161107-092202](https://cloud.githubusercontent.com/assets/9414008/20062074/a7470784-a502-11e6-9f05-7effd2140b27.png)

so from what I can tell it only looks good on my tablet but not on my smartphones.

edit: is it possible to have all Genres and Order in 1 row instead of 2? That would make it easier to see for smaller devices

**Comment by raulhaag** [comment]
Working on it

**Comment by raulhaag** [comment]
check last if still occur

**Comment by xtj-9182** [comment]
yeah that fixed it thanks !
