### ISSUE TITLE
KissManga and ReadComicOnline manga list doesn't work anymore

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#357]
Hi, great work on the manga genre selection ! :)

But the manga list doesn't work with those 2 server. If I let it in the default state or try to check some stuff, there's nothing loading.

**Comment by raulhaag** [comment]
The default km now take a while because load all the list at once, and rco
is almost the same

**Comment by Dostoi** [comment]
My bad I didn't wait long enough ^^

But if I check a genre, the loading circle appears for a second then disappears and nothing change, even after waiting for a long time.

For example on kissmanga, I wait for the default list to load, then check the horror filter and press apply. But there's no change in the manga list.

**Comment by Dostoi** [comment]
Don't mind this issue, it's fixed with the last travis x)
