### ISSUE TITLE
Add scan site in details

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#36]
Can you add the scan from which the manga was taken ? 
It could be usefull to give feedback about an issue if you don't renember from which site you've taken it ( #35 ) and also if you want to read it on your computer from the same scan site (as all site doesn't have the same state for each manga, some lack a lot of chapter)

**Comment by raulhaag** [comment]
Easy, added to next version as an icon on mi mangas items

**Comment by Dostoi** [comment]
Thanks :)
