### ISSUE TITLE
Checked genre aren't easily visible in black theme

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#360]
In black theme, checked genre appears in black too. Switching the color to white would make it more visible

**Comment by Johndeep** [comment]
what do you mean by "checked genre"? Do you mean the already read chapters?

**Comment by Dostoi** [comment]
I should put a screen-shoot everytime to make it easier. In the genre selection in server search
 
![screenshot_2016-11-12-15-32-36](https://cloud.githubusercontent.com/assets/7694864/20238511/8ec759ae-a8ed-11e6-93f1-c5ca277a0612.png)

**Comment by raulhaag** [comment]
forgot to use appcompat component, i think they will fix it
![filter](https://cloud.githubusercontent.com/assets/2048339/20239738/3b65f128-a8e6-11e6-8938-591ba09e45fc.jpg)
