### ISSUE TITLE
Adding a manga make the hidden finished manga appear in the manga list

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#364]
Check to hide the finished manga (and have one at the top of the manga list for easy testing)
Go in the manga list of a server (I went on kissmanga)
Add any manga
Go back to your manga list
Hidden finished manga are shown even if they shouldn't be

With version 1.56

**Comment by xtj-9182** [comment]
good on you for finding this, this is a bug that I accidentally introduced in commit d137e195fb83a4cf29ce17070f62fbe3bdc9d826

so what was happening was that the empty value in the search somehow triggered the gridview to be filled with the wrong mangas, as in it was showing all mangas that would appear when you search for ""

I fixed it and it should be merged soonTM.
