### ISSUE TITLE
Don't show a downloading next chapter pop-up if it's already in the download list

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#365]
With the option to download next chapter automatically, you get a pop-up saying so.
But it's not useful to show it if you've already manually added the chapter to the download list.

**Comment by xtj-9182** [comment]
so I have a prototype for this. I'm a little worried cause we have to traverse the whole list of chapters that are currently being downloaded to find out if we want to show the toast. 
I hope you still have your old and slow device so you can test if it will make things slow or if I'm just imagining things.

**Comment by Dostoi** [comment]
Yes i'll tell you ^^

**Comment by Dostoi** [comment]
Seems good too !
