### ISSUE TITLE
App go fullscreen after leaving the reader

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#367]
When leaving the reader, the app is set to full screen and doesn't leave the top bar (the one with the time and all) visible.

![screenshot_2016-11-17-19-55-28](https://cloud.githubusercontent.com/assets/7694864/20403189/226724b2-ad00-11e6-86bc-6b9eebd35a55.png)

I can't take a screen shot the app after leaving the reader because by trying to do it I leave the full screen ^^

**Comment by xtj-9182** [comment]
The bar at the top which displays the clock etc is called status bar ;).
I can reproduce this but it only seems to happen when the option to show the status bar is de-selected.

I look into it.

**Comment by Dostoi** [comment]
Oh ok, it's better with the name x)

Good lock in your search ^^

**Comment by xtj-9182** [comment]
ok so I have a fix that works on my device. I hope it works on android <5 devices too

**Comment by Dostoi** [comment]
I'll tell you

i'll try it after :)

**Comment by Dostoi** [comment]
Fixed with last travis ! :+1:
