### ISSUE TITLE
An opened chapter isn't considered as a unread chapter even if it's not read

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#368]
While testing I noticed that if you open an unread chapter but don't read it, just leave the reader right away, delete the downloaded picture of this chapter then press download all unread chapter, the app will not download the picture for the opened chapter even if you're still at page one of this chapter and never wen further than that.

Shouldn't a chapter be considered as read only when you reach the end of it and not when you open it ?

**Comment by xtj-9182** [comment]
there are 4 states: New(-1), Unread(0), Read(1) and Reading(2). When you go to a chapter and go back without finishing it, it will be in Reading state.

We currently do this when you press on download all unread chapters:
``` java
ArrayList<Chapter> chapters = Database.getChapters(getActivity(), MangaFragment.this.mMangaId, Database.COL_CAP_STATE + " < 1", true);
```
so every chapter with state < 1 will be downloaded.

I think that the assumption here is that a chapter that is in reading state is either currently being downloaded or already downloaded.

**Comment by Dostoi** [comment]
So just changing to !=1 will fix this issue except if @raulhaag doesn't want the behavior to change ?

**Comment by xtj-9182** [comment]
I was thinking of doing this:
``` java
ArrayList<Chapter> chapters = Database.getChapters(getActivity(), MangaFragment.this.mMangaId, Database.COL_CAP_STATE + " != 1" + " AND " + Database.COL_CAP_DOWNLOADED + " != 1", true);
```
