### ISSUE TITLE
Can't search in readcomiconline.to in the app

### ISSUE THREAD

**Issue by TheWrightStuff1994** [raulhaag/MiMangaNu#369]
The app won't let me search anything even if I made the search vague enough for the app to search for it.

**Comment by xtj-9182** [comment]
this affects KissManga too. For me the first search always works but a second or third or fourth etc search will always return no result. 

Search seems to work fine on other sites like NineManga / MangaPanda so it's likely something to do with KissManga and readcomiconline's cloudflare protection @raulhaag any ideas ?

**Comment by raulhaag** [comment]
@xtj-9182 easy cake, just getNavigator() return the nav whit old parameter, and the server don't give a good response to this, just modified getNavigator() from ServerBase, now is nedded to create a copy of this for current proc, just need to revice all the servers if any other use getNavigator every line.
@TheWrightStuff1994 almost ready just neeed to find if a make new problems whit the mdificatio :-P

**Comment by raulhaag** [comment]
@TheWrightStuff1994 ready on travis version (or v.1.57 at its time)

**Comment by xtj-9182** [comment]
to be fair I didn't check the code when I made the comment.

**Comment by TheWrightStuff1994** [comment]
So what should I do?
