### ISSUE TITLE
[Bug] SeekBarCustomPreference seems to not call onPrefChangelistener sometimes

### ISSUE THREAD

**Issue by xtj-9182** [raulhaag/MiMangaNu#370]
from  https://github.com/raulhaag/MiMangaNu/issues/204

to reproduce put the grid columns seekbar to 1 and go to 2 and back to 1. When going back and forth between 1 and 2 the PrefChangelistener isn't called.

I looked through the SeekBarCustomPreference class but I'm not yet sure what is wrong, any pointers @raulhaag ?

**Comment by raulhaag** [comment]
install.packages("vertexenum")
install.packages("numbers")


2016-11-21 16:33 GMT-03:00 xtj-9182 <notifications@github.com>:

**Comment by xtj-9182** [comment]
are these R packages ? Why do I need R for this to work ?

so it works on your side ?

**Comment by raulhaag** [comment]
Sorry my bad, wrong mail list

**Comment by xtj-9182** [comment]
oh xD

**Comment by xtj-9182** [comment]
@raulhaag 
but for real tho you don't know why the listener isn't called sometimes ?

I mean I could just not rename the summary however that might be confusing to users.

I could also just add a switch instead for the automatic detection

**Comment by xtj-9182** [comment]
nevermind I went with adding an extra switch for auto grid detection which is enabled by default

**Comment by raulhaag** [comment]
sorry no time on the week to checkout :-$
