### ISSUE TITLE
Icon isn't refreshed when the chapter is finished to be downloaded

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#375]
The icon that allow to download a chapter picture isn't replace when the chapter is finished to download if you stay on the manga page.

For exemple go to a manga page, press the button to download a chapter, wait for it to end and when it's over, you still have the arrow button and not the bin one.

**Comment by raulhaag** [comment]
ready for test when travis finish

**Comment by xtj-9182** [comment]
the fix works on my side.  👍

**Comment by Dostoi** [comment]
Good for me too
