### ISSUE TITLE
Can't download the chapter picture if it was downloaded and deleted

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#376]
If you download a chapter, wait for it to be downloaded, then delete the picture, you can't download it again while the chapter is still in the download page (in finished state).

I know I'm reporting edge behavior but it's still a bug :p

**Comment by raulhaag** [comment]
yes is anoying bug knowed and now fixed, check last travis

**Comment by Dostoi** [comment]
Fixed, you were quick on those one :+1:  :)
