### ISSUE TITLE
Issue with mangafox and mangareader

### ISSUE THREAD

**Issue by Furanbelius** [raulhaag/MiMangaNu#379]
From Saturday 4 December, when updating the list of mangas and find more than a new chapter, only the second new chapter is downloaded and it is read as the first new chapter, generating an error when trying to read the next chapter, which is In fact the first new chapter. This happens with different mangas on the two servers named in the title.
Also, mangafox gives download errors in some occasions, not being able to download a new chapter even when it is available in the web version.
I hope you understand, greetings.

**Comment by xtj-9182** [comment]
I can confirm mangafox is broken right now. It seems like they changed some stuff around 4th of december and now most of our regex aren't working anymore. I'll try to fix it but it's going to take a few days...

I can't reproduce problems with mangareader I only took a quick look but mangareader works fine on my side. I can correctly download and update mangas from mangareader not problems here on my side.

**Comment by wyrex** [comment]
I use One punch man as example. 

Mangafox 'downloads'  chapters but every image is picture of 404 penguin.  Mangahere shows this exception http://postimg.org/image/ld0evb9s9/

**Comment by raulhaag** [comment]
the prinny an 404 error from server, other (server side) error or exausted retrys (generally connection stability problems or server down)

**Comment by Furanbelius** [comment]
The new versión fix the error un mangafox, but i found that some mangas like the chapter 10 of usotoki rhetoric, dos not download the full chapter, in this case 37 pages when the webmobile page shows 38. This rare error does not happen with all the mangas and just realise by luck

**Comment by Furanbelius** [comment]
The new versión fix the issue of mangafox and now all the pages of a chapter are been downloaded, so issue closet.

Great work!!!!!!!!!!!!!
