### ISSUE TITLE
Error when donwloadind chapter

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#38]
I'm getting an error when downloading chapter from Front Mission Dog Life Dog Style from mangapanda. At least with chapter 6, don't know for the rest.
Same for Blood And Steel chapter 58 from mangapanda.

**Comment by raulhaag** [comment]
i test and they working ok

**Comment by Dostoi** [comment]
Strange, I'll try redownload the database

**Comment by Dostoi** [comment]
I'm still having the issue even after re-downloading the database
