### ISSUE TITLE
Add gogocomic.net to the app

### ISSUE THREAD

**Issue by TheWrightStuff1994** [raulhaag/MiMangaNu#382]
and viewcomic.com and view-comic.com

**Comment by TheWrightStuff1994** [comment]
and Comicastle as well

**Comment by Zolued** [comment]
and japscan.com for french people please :3

**Comment by xtj-9182** [comment]
I'm working on this. Expect something in the next few weeks.

**Comment by xtj-9182** [comment]
done.
