### ISSUE TITLE
Some corrections at strings.xml (spanish)

### ISSUE THREAD

**Issue by plablo** [raulhaag/MiMangaNu#383]
I suggest some changes in strings.xml (app/src/main/res/values-es/strings.xml), are grammar and spelling corrections that will make the app more accurate in this language.
[strings.zip](https://github.com/raulhaag/MiMangaNu/files/654868/strings.zip)

**Comment by raulhaag** [comment]
Hola pablo cuando quieras mandar modificaciones del strings entra a https://github.com/raulhaag/MiMangaNu/edit/master/app/src/main/res/values-es/strings.xml ahi tenes la opcion de editar y al terminar generar un pull request (lo mas facil para un solo archivo)o podes hacer un fork y alli modificar varios archivos y luego realizar el PR ahi lo hice manual, gracias por las correcciones de mis horrores ortograficos esta vez los agregue manualmente

**Comment by plablo** [comment]
Hola Raul,
Gracias por leer mi aportación, aún estoy algo verde con el github (^_^U). Si encuentro algo más lo haré de la forma que me has descrito. 
Muchas gracias de nuevo.
Un saludo.
