### ISSUE TITLE
Can you make the app have a switch to low resolution to read/download?

### ISSUE THREAD

**Issue by TheWrightStuff1994** [raulhaag/MiMangaNu#387]
I have not that great of a internet speed so this will be a fantastic feature for me and others that have the same problem.

**Comment by raulhaag** [comment]
to download, non possible in my knows without an external service, perhaps 1 or 2 servers on supported had implemented a funtion like this (but i really don't know), to read i tested a library to do it and the resize loading time is really to much (i have to say memory usage is lower, but it fell so "weigth").
sorry, i can't help you whit this.

**Comment by TheWrightStuff1994** [comment]
How about Maximum Texture Size?

**Comment by TheWrightStuff1994** [comment]
Okay thank you for replying.
