### ISSUE TITLE
Black screen instead of the manga page

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#39]
Downloading Trace 2.0 chapter from mangahere work but when I want to read it, all I got is a black screen. It load for a while then there is just a black screen. It happens with chapter 40, 41 and 42, I don't know for the rest.

**Comment by Nodd** [comment]
Same for Dragon's Son Changsik (I don't remember which site). It also happens in other mangas from time to time, randomly.

**Comment by Dostoi** [comment]
@Nodd the logo of the scan site has be added on the top left of the manga picture with the last update

**Comment by Nodd** [comment]
Oh right ! On some covers it's not really visible. That's from MangaPanda then.

**Comment by Dostoi** [comment]
yes maybe putting it in the manga details too would help

**Comment by raulhaag** [comment]
i found some variant on nomenclature of image, i need check the server
