### ISSUE TITLE
BataTo Login Issues

### ISSUE THREAD

**Issue by Yuu1305** [raulhaag/MiMangaNu#392]
Hello there, I find it awesome that you included batato. But I can't seem to login. It says login failed. Tried username, email, changed pw in batato, but doesn't help at all :/

**Comment by xtj-9182** [comment]
do you have uppercase letters in your username ? 

There is a bug currently with uppercase letters in usernames since we check for a string that automatically turns them into lowercase letters but we don't account for that currently.

**Comment by Yuu1305** [comment]
Yes my username uses uppercase letters.

**Comment by xtj-9182** [comment]
yeah so that's causing problems right now but I fixed it. Now we just need to wait for Raul to merge my PR.

**Comment by raulhaag** [comment]
sorry my username have only lowercase so test go good merging, i know i neeed to do this test with the cookies but no much time since i mede it i added the lowercase to inteceptor to for now

**Comment by Yuu1305** [comment]
Downloaded newest Travis and works now, thank you for the fast response both of you ^^
