### ISSUE TITLE
Make the OK button more look like a button

### ISSUE THREAD

**Issue by Zykino** [raulhaag/MiMangaNu#398]
When I "download the unread chapters", a message appear at the bottom.
This message may look like a "download started" message if you do not take the time to read it's a confirmation one.

Putting a square around the "OK" text should help the user understand that an other action is required.

**Comment by xtj-9182** [comment]
the message at the bottom is called a snackbar.

I'm not sure if it's easy to change the design of it. I could probably change the color of the text but that's also kinda meh. Personally I would be more happy if we reverted to the dialogs we used before, similar to what we do at the end of a chapter.

**Comment by raulhaag** [comment]
i know and in tablets i keep to low on the screen, i think to change back
to material dialogs only those dialogs that need confimation, but no time
now.

2017-03-07 12:58 GMT-03:00 xtj-9182 <notifications@github.com>:

**Comment by Zykino** [comment]
Yeah snackbar looks to be nice only to show an information (between toasts and notification levels) or showing an error and having a "retry" button.

Maybe changing the color could be a quick fix if you don't have the time right now. Not sure which one could go well with that deep blue over black background.

**Comment by xtj-9182** [comment]
now that you mention it, the color of the background of a snackbar changes based on what you select as primary color. Given that I'm not sure what color would be a good pick here.

**Comment by xtj-9182** [comment]
I found some time so I switched us back to the old alertdialogs
