### ISSUE TITLE
Bug with auto-rotate of the screen

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#4]
The screen auto-rotate even when the option isn't activated.
If the phone is turned and you go to "mis manga" click on a manga and go back, the screen is going to auto-rotate every time you go to mis manga after that

The same thing happen if you refresh your manga database.

**Comment by raulhaag** [comment]
yes try in the new version when if aviable

**Comment by Dostoi** [comment]
Ok, I'll try it out. Love the app so far :)

**Comment by Dostoi** [comment]
The bug is still here after updating the manga list, the screen auto-rotate. But the others one isn't here anymore.

**Comment by raulhaag** [comment]
try in the v 1.08

**Comment by Dostoi** [comment]
It's fixed

**Comment by raulhaag** [comment]
Ok
