### ISSUE TITLE
Kissmanga download error

### ISSUE THREAD

**Issue by bendunnb4** [raulhaag/MiMangaNu#400]
Getting Error while attempting to download manga from Kissmanga site.

**Comment by AxezCore** [comment]
I get an error too, and it's not caused by the anti-bot filter.

**Comment by raulhaag** [comment]
no the problen is they use now CryptoJS to encrypt the images, not solution for now

**Comment by raulhaag** [comment]
there is an implemetation for java of CryptoJS just need to find the key... and a lot of work behind

**Comment by raulhaag** [comment]
ready on travis,  using ducktape to execute script like with cloudflare
