### ISSUE TITLE
Suggestion to use google drive to synchronize

### ISSUE THREAD

**Issue by MakuSensei** [raulhaag/MiMangaNu#403]
Hi i want to suggest in using google drive to sync the list of mangas and settings.

Greetings from Argentina

**Comment by raulhaag** [comment]
Hola, acerca de la sincronizacion con google drive ya se hablo hace un tiempo realmente como vienen muchas herramientas para ello no seria necesario hacerlo (podes seleccionar la carpeta de de mimanganu para la sinc), ademas la necesidad de usar servicios de google bloquearia a los usuarios de que no tengan los servicios de google (como blackberry y los dispositivos de amazon).
Saludos desde Argentina :-P

**Comment by MakuSensei** [comment]
hola, y como sincronizo desde el celu dicha carpeta?

**Comment by raulhaag** [comment]
hay muchas app en el store como foldersync o titanium backup que permiten esta funcion pero el uso depende de cada app.

**Comment by MakuSensei** [comment]
gracias :)
