### ISSUE TITLE
ninemanga sites broken

### ISSUE THREAD

**Issue by xtj-9182** [raulhaag/MiMangaNu#404]
@raulhaag 
currently only displaying niadd ads

edit: I just noticed this now but it seems like en ninemanga is just rehosting content from http://www.taadd.com/

edit2: this is issue #404 lol

**Comment by raulhaag** [comment]
not the same, took me 2 hrs find what they do when you read that triki page may be it make you laught but tracing it, was a headcache, now i need a way to improbe the method, the #404 was only an extra header, this an extra cookie, almost ready for 1 server, tomorrow perhaps the other and a v1.62 release

**Comment by xtj-9182** [comment]
looks like they've added a mandatory recaptcha check every time you visit their sites now.

If it's too much work I think we should consider disabling their sites since they seem to be hellbent on pushing their shitty app.

**Comment by raulhaag** [comment]
is a little to much work, i can do it but go to find this really anoying, (the captcha is for a couple of hours), in app if there is an update search and need a captcha, really i don't think they can mantain the captcha for longer time becuase peaple just look another site less anoying, i just considering disable the ninemanga site but i go to give their a little time to see the problem of have the recaptcha on theirs pages

**Comment by xtj-9182** [comment]
ok.

I've been thinking since EN (only the en one unfortunately :( ) ninemanga is just linking to content from taadd, that I could replace EN ninemannga with taadd since they have the same content and taadd is currently not requiring any recaptcha. I'm working on that right now, I do hope that taadd isn't gonna do the recaptcha thing too.

**Comment by xtj-9182** [comment]
as of this writing ninemanga seems to be up again.

**Comment by xtj-9182** [comment]
@raulhaag 
seems it didn't last long. EN RU and DE all give me "mangadog" ads when trying to download images. For some reason ES ninemanga still works though. 

for en ninemanga I can add taadd as a replacement they have the same content but don't give me shitty ads when I download their images which is the same content that the en site links to.

**Comment by raulhaag** [comment]
RU and EN, give me the thief message, DE i don't know why not

**Comment by raulhaag** [comment]
in the navigator  they give me the same message :-D :-D :-D

**Comment by raulhaag** [comment]
![image](https://cloud.githubusercontent.com/assets/2048339/25087916/db4a0f62-2348-11e7-9d24-6de739045c0f.png)
when tryn to enter the promocionated site :man_facepalming:

**Comment by xtj-9182** [comment]
> in the navigator they give me the same message :-D :-D :-D

this happened to me too in Google Chrome somehow... in firefox + adblock plus, I can browse their sites just fine though.

**Comment by raulhaag** [comment]
all ninemanga are working just fine now (or only i?)

**Comment by xtj-9182** [comment]
> all ninemanga are working just fine now (or only i?)

still broken for me. Only ES works for me.

it's possible that it sometimes works temporary. I tried different changes and got it to work for me but only temporary before it would give me the ads again.

**Comment by xtj-9182** [comment]
case in point: I added bleach on ninemanga en and it gave me ads on a chapter then I waited a bit and downloaded a different chapter suddenly no ads then I added a different manga and suddenly I get ads again.

**Comment by xtj-9182** [comment]
as of this time period all ninemanga sites work for me.
