### ISSUE TITLE
Version 1.61 is causing an error every installation attempt

### ISSUE THREAD

**Issue by Gomgoru** [raulhaag/MiMangaNu#405]
Version 1.61 is causing an error every time I try to install it; **There is a problem parsing the package.**

**Comment by raulhaag** [comment]
don't worry soon v1.62 go online

**Comment by xtj-9182** [comment]
@Gomgoru 
is this still happening with v1.62 ?

**Comment by Gomgoru** [comment]
It's happening with v1.62 as well!
this is the error I get:
> Describe error
> There was a problem parsing the package.

Then it stops adding the package. I know it's very likely I have done something wrong to probably cause this problem to appear, I just don't know what it was, or how to clear it, if its my problem...

**Comment by Gomgoru** [comment]
Well, I just tested v1.62 and it has the same apparent problem, too.

**Comment by raulhaag** [comment]
Try go to settings 》security 》unknow source (disable and enable)
Then disable verify app (and leave it disable perhaps this nop support last signs) 
 check if you have any kind of extra permission enable or disabled

**Comment by xtj-9182** [comment]
also try uninstalling the current version and installing the latest one see if it helps

**Comment by raulhaag** [comment]
closed due non response

**Comment by Gomgoru** [comment]
Sorry for taking so long to let you know what was going on [proper Japanese :bow: bow of inferior to superior.] 

It turns out to be a issue with the *X-plore (:file_folder: file manager)* app and Android 4.4.2 :smirk_cat: 'kitkat'. It was changing the file permissions on the APK file, making it impossible to install. X-plore changed the permissions to make it easier to use the zip library to show the apk content as :open_file_folder: a directory.

Anyway, 

**_Thank You_:exclamation: for your :gift_heart: [ @raulhaag ] and :gift_heart: @xtj-9182 's help.** 

( :weary: I knew it would be something simple or **because of a  :dizzy_face: simple [me!]**.)
