### ISSUE TITLE
Bug report - Jumping to top on manga view

### ISSUE THREAD

**Issue by lenisko** [raulhaag/MiMangaNu#406]
Okay here's the thing...

After reading chapter and closing it we are getting moved to top position on manga view. It's really annoying when someone is starting reading new thing. Best solution would be to save last position and restore it.

Video describe: https://webmshare.com/play/3w0Vq

Android 7.0, Samsung S7 and last version of MMN from Travis builds

**Comment by xtj-9182** [comment]
what android version do you use ?

 I have problems reproducing this on android 7.1. When I do what you did I just get back to the view of chapter 01

**Comment by raulhaag** [comment]
ok the problem comes when rotate manga fragment lost the position and not only on nougat

**Comment by raulhaag** [comment]
check last travis :wave:
