### ISSUE TITLE
Change request - Annoying button position

### ISSUE THREAD

**Issue by lenisko** [raulhaag/MiMangaNu#407]
Position of Delete/Confirm button is really bad.. I mean before it was on center, right now it's at bottom of the screen. When using phone most people have finger on center of screen, and it's kinda hard to press something at bottom.

Video describe: https://webmshare.com/play/omX9E

**Comment by digiwombat** [comment]
They did this already. It was fixed in #398.

You can grab the latest release (1.62) and it should be in there.

**Comment by lenisko** [comment]
@digiwombat Oh.. you're right. Thanks for information!
