### ISSUE TITLE
Italian source

### ISSUE THREAD

**Issue by falybros** [raulhaag/MiMangaNu#41]
Hi
can you add Italian source?
- mangaeden.com
- itascan.info
- bato.to
- ninemanga.com

thank you

**Comment by raulhaag** [comment]
it.ninemanga can be it look like th panish and dont go to be a problem, i'm working on other personal project, just wait for it

**Comment by falybros** [comment]
thank you for your time ;)

**Comment by raulhaag** [comment]
can you translate the values to it?
only the part between ">" and "<" (in first line "List of Manga")

<string name="title_activity_server_listade_mangas">List of Manga</string>
    <string name="title_activity_activity_detalles">Details</string>
    <string name="title_activity_activity_capitulos">Chapters</string>
    <string name="title_activity_activity_lector">Reader</string>
    <string name="title_activity_server_visual_navegacion">Mangas in</string>
    <string name="title_activity_activity_resultado_de_busqueda">Search result</string>
    <string name="action_ajustar_a">Fit to</string>
    <string name="cargando">Loading&#8230;</string>
    <string name="capitulos">Chapters</string>
    <string name="info">Details</string>
    <string name="descargas">Downloads</string>
    <string name="datosde">Details</string>
    <string name="agregando">Adding to database</string>
    <string name="agregado">Manga added</string>
    <string name="iniciando">Loading number of pages</string>
    <string name="agregadodescarga">Manga added to downloads</string>
    <string name="mismangas">My Mangas</string>
    <string name="masmangas">Add Mangas</string>
    <string name="buscandonuevo">Searching for updates </string>
    <string name="busquedanores">The search returned no results</string>
    <string name="listaen">List of Mangas from</string>
    <string name="buscarupdates">Search for updates</string>
    <string name="nobuscarupdate">Don\'t search for updates</string>
    <string name="licencia">Licence</string>
    <string name="esconder">Hide from gallery</string>
    <string name="descargarestantes">Download remaining</string>
    <string name="borrado_imagenes">Images deleted</string>
    <string name="agregar">Add</string>
    <string name="borrar">Delete</string>
    <string name="borrarcap">Delete chapter</string>
    <string name="resetcap">Reset chapter</string>
    <string name="buscarnuevos">Search for updates</string>
    <string name="mas">More</string>
    <string name="escondergaleria">Hide from gallery</string>
    <string name="filtrar">Filter</string>
    <string name="vercomolista">View as List</string>
    <string name="esconder_leido">Hide already read</string>
    <string name="macartodoleido">Mark all as read</string>
    <string name="macartodonoleido">Mark all as unread</string>
    <string name="sentido">Direction</string>
    <string name="finalizado">Status: Finished.</string>
    <string name="en_progreso">Status: Ongoing.</string>
    <string name="encola">(Queued)</string>
    <string name="descargando">(Downloading)</string>
    <string name="descargado">(Downloaded)</string>
    <string name="error">(Error)</string>
    <string name="orden">Order.</string>
    <string name="apachelic">Apache Licence</string>
    <string name="mitlic">MIT Licence and Thanks</string>

**Comment by falybros** [comment]
Ok
```
<string name="title_activity_server_listade_mangas">Lista dei Manga</string>
    <string name="title_activity_activity_detalles">Dettagli</string>
    <string name="title_activity_activity_capitulos">Capitoli</string>
    <string name="title_activity_activity_lector">Lettore</string>AAA
    <string name="title_activity_server_visual_navegacion">Manga in</string>
    <string name="title_activity_activity_resultado_de_busqueda">Cerca risultati</string>
    <string name="action_ajustar_a">Adatta</string>
    <string name="cargando">Caricando&#8230;</string>
    <string name="capitulos">Capitoli</string>
    <string name="info">Dettagli</string>
    <string name="descargas">Scaricati</string>
    <string name="datosde">Dettagli</string>
    <string name="agregando">Sto aggiungendo al database</string>
    <string name="agregado">Manga aggiunto</string>
    <string name="iniciando">Caricamento numero delle pagine</string>
    <string name="agregadodescarga">Manga aggiunto agli scaricati</string>
    <string name="mismangas">Miei Manga</string>
    <string name="masmangas">Aggiungi Manga</string>
    <string name="buscandonuevo">Ricerca aggiornamenti</string>
    <string name="busquedanores">La ricerca non ha generato risultati</string>
    <string name="listaen">Lista dei Manda da</string>
    <string name="buscarupdates">Cerca aggiornamenti</string>
    <string name="nobuscarupdate">Non cercare aggiornamenti</string>
    <string name="licencia">Licenza</string>
    <string name="esconder">Nascondi dalla galleria</string>
    <string name="descargarestantes">Scaricamenti rimasti</string>
    <string name="borrado_imagenes">Immagini cancellate</string>
    <string name="agregar">Aggiungi</string>
    <string name="borrar">Cancella</string>
    <string name="borrarcap">Cancella capitolo</string>
    <string name="resetcap">Resetta capitolo</string>
    <string name="buscarnuevos">Cerca aggiornamenti</string>
    <string name="mas">Altro</string>
    <string name="escondergaleria">Nascondi dalla galleria</string>
    <string name="filtrar">Filtra</string>
    <string name="vercomolista">Mostra come elenco</string>
    <string name="esconder_leido">Nascondi già letti</string>
    <string name="macartodoleido">Marca tutti come letti</string>
    <string name="macartodonoleido">Marca tutti come non letti</string>
    <string name="sentido">Verso</string>
    <string name="finalizado">Stato: Finito.</string>
    <string name="en_progreso">Stato: In corso.</string>
    <string name="encola">(In coda)</string>
    <string name="descargando">(Scaricando)</string>
    <string name="descargado">(Scaricato)</string>
    <string name="error">(Errore)</string>
    <string name="orden">Ordine.</string>
    <string name="apachelic">Licenza Apache</string>
    <string name="mitlic">Licenza MIT e Ringraziamenti</string>
```
I don't remember where I can find every word... can I write here if I find some adaptation mistakes?

**Comment by raulhaag** [comment]
it's here https://github.com/raulhaag/MiMangaNu/blob/master/MiMangaNu/res/values-it/strings.xml
now wait to f-droid update
