### ISSUE TITLE
Update notification stuck (cannot dismiss)

### ISSUE THREAD

**Issue by ehmuzed** [raulhaag/MiMangaNu#410]
Occasionally the "Searching for updates" notification for the automatic updates will hang midway through and not me dismissable or cancelable.
I've encountered this on a fire 8 tablet (2016),  and shield tablet running marshmellow. I've not encountered it yet on nougat on a nexus 5x

**Comment by xtj-9182** [comment]
I only have a nougat device but I'm gonna try and see if I can reproduce it

**Comment by xtj-9182** [comment]
I made some tests on Android 6 & 7 but I couldn't reproduce the issue.
the automatic update notification can be dismissed by clicking on it, if it's not dismissing it's being updated.

If you encounter this again please check your logcat and see if there are any warnings or errors from MiMangaNu. It's possible that the issue is caused by something in our app being unresponsive etc. You can use apps like "Logcat Extreme" or "CatLog" or just use adb to copy your logcat to your PC.

**Comment by raulhaag** [comment]
probably with a try / catch / finally => dismiss notification will work

**Comment by lenisko** [comment]
Had same problem. LogCat is not working for me, guess those are some security enchantments on my SGS7. Implementing some log gathering in MiMangaNu would be great thing. Im using sentry for it.

**Comment by raulhaag** [comment]
last travis probably fix this

**Comment by xtj-9182** [comment]
> probably with a try / catch / finally => dismiss notification will work

@raulhaag 
feel free to add it wherever you think it's necessary.

@lenisko 
that's odd ... I had a SGS7 too and had no problems with logcat output. We use ACRA for crash reports not sure how sentry would help us.

**Comment by lenisko** [comment]
@xtj-9182 Ah I forgot about ACRA. Tanks for letting me know ;-)

**Comment by Zykino** [comment]
I don't reproduce it often but I think most of the time I have it is when I don't have a good internet access. I didn't test the Travis build mentioned, just for an hint on how to reproduce, maybe.
So try to slow the internet connection during your test or fully cut it at specific point of time.

I have a OnePlus 3 stock Marshmallow updated to Nougat (and had the problem on Nougat)

**Comment by xtj-9182** [comment]
@Zykino it's hard for me to test with low wifi. I tried testing by starting an update and then disabling my wifi but the notification will then simply run through and fail to connect to servers, it's not getting stuck for me.

**Comment by raulhaag** [comment]
new version out please confirm if the problem still exist

**Comment by raulhaag** [comment]
reropen if needed
