### ISSUE TITLE
Error while trying to open database

### ISSUE THREAD

**Issue by decripter37** [raulhaag/MiMangaNu#412]
It happened at least five more times. Sometimes I got the error that I wrote on the title, everything disappears and I have to manually readd all.

**Comment by raulhaag** [comment]
This can be cuased by a couple of scenarios:
 * the db is corrupt, caused generally by memory corrupt (the worst scenario just becouse your phone memory are corrupt or memory is full)
*  others app at trying to access the mmn db and make this corrupt (or"cleaning apps" or an alternative clone from this app)
* others.
but nothing to do from here

**Comment by decripter37** [comment]
How I can restore/decorrupt the db? Where is located?

**Comment by raulhaag** [comment]
the db is located on external storage by default (not external sd) /MiMangaNu/dbs/

**Comment by decripter37** [comment]
Thanks, I deleted it and now it works again!
