### ISSUE TITLE
Add new french servers

### ISSUE THREAD

**Issue by Fraulk** [raulhaag/MiMangaNu#416]
[mangakawaii.com](https://www.mangakawaii.com/) and [mangapedia.fr](http://mangapedia.fr/) for the french lector :)

**Comment by xtj-9182** [comment]
I looked at them and I think I can add MangaKawaii.

MangaPedia on the other hand seems like a site that isn't worth the effort in my opinion.

They purposefully disable the right click in their manga reader so you can't view the source. But then again you can disable this by blocking their scripts with no script but even then I can't find the image url.

![shitty french cloudflare site 0](https://cloud.githubusercontent.com/assets/9414008/25895902/30d24026-3582-11e7-85b8-f7f40a1d3e40.png)

taking a look at adblock plus gives me this link

![shitty french cloudflare site 1](https://cloud.githubusercontent.com/assets/9414008/25895914/442b3650-3582-11e7-9787-4a5f7f8b009d.png)

looks like they use some script to encrypt their file paths or something
anyway imo not worth the effort.

I'm gonna add MangaKawaii tho. In a few days ...

**Comment by Zykino** [comment]
Just as a little help for mangapedia (if it's more worth the try):
Once the mange loaded use [F12], then on the upper left of the console you have the element selector.
Click on it then on the image and you'll see that the image is added with a class on the <table> element.

for example for [MajoniAtaeruTettsui](http://mangapedia.fr/lel/MajoniAtaeruTettsui/46/1/1) (choose randomly)
`.image {
    background-image: url('http://mangapedia.fr/project_code/script/image.php?path=hJrWqdiAlJ_LwpJ_ls6hnp542sac2K26nNbYpNmdlLmgmsmq0pyhoLfExKBkp5qRpaDa15yVaZVnkpKh0ps&FileName=00.png&ID=19520630398');
[...]
}`

The class always look to be "image". But on my first try (didn't saved the manga :s) I saw "image1" and "image2" so a JQuery selector for the image should be:
`$("[class^=image]"); // class start with "image"`

I don't know if it's worth the work on your side anyway.

Tell me if you think it's worth that I dig into the JS source codes to find where it comes from.

**Comment by raulhaag** [comment]
@xtj-9182 any progress? just to know, And if u want to know i use firebug for get all information about the page.

**Comment by raulhaag** [comment]
mangapedia have this array on the page easy to parse
					var arrImageData = [["http://mangapedia.fr/project_code/script/image.php?path=sqKpqaWwkaDNxmixpZWArM-amYSTppKGqouWltKQqZ3HqZ-ppMhfaZqTa5FnYF6nz54&FileName=00.png&ID=84103252128",["761","767"]],["http://mangapedia.fr/project_code/script/image.php?path=rqHX1deCkaSbk2SIp5uJq8_Imn-U0WV-dombkqZjpKDDqM3V1ppfbWhgZ2hpZ2emz8w&FileName=01.png&ID=58630301211",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=rs-kpqSulJ6axJOI08iBrKOTmYLE1GWxq7qbmNFhc6HD1pqmo8ZiZ2eRlmiVlV-no5c&FileName=02.png&ID=28145755906",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=rZ_YrKiwkaeZlWeHpcqH29Cam4OUppOFqreXwqNgeZrCps6sp8hfcGZiamdnmGXW0J4&FileName=03.png&ID=23941697119",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=fp3Y2deCwqWfmV-Fo5WzqqPEmYbCoJCzeorIlaZkfJ6TpM7Z1pqQbmxmYmVlZJGfpcg&FileName=04.jpg&ID=46144044883",["761","1100"]],["http://mangapedia.fr/project_code/script/image.php?path=gsqnpaiulaeexZC1o5mC29OUybHHo5OBeofJkqRjdJ6X0Z2lp8ZjcGuSk5VlaWDW05g&FileName=05.png&ID=81170742679",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=sqGnqaeFk6SYkZOE0JiGq9OUnbCWz2CCf7jKl6GTfMvHqJ2ppp1hbWVelmSSaWSm05g&FileName=06.png&ID=67979794312",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=sqCqpaOEkqeax2OwpJmF29CWmLPGoV-Gf7WZx6RndZvHp6ClopxgcGeUZpBma2PW0Jo&FileName=07.png&ID=28989413445",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=rc-m1qyFlZ6gxJCF1Jqyp9TEnbHGomGwfIeZlp9oeczC1pzWq51jZ22Rk2WWbZCi1Mg&FileName=08.png&ID=34303928599",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=rs_V19iuwqCXmpOIoJqy1qKVya-apWCCrInIx86Rd6HD1svX18aQaWRnlmhibpDRopk&FileName=09.png&ID=21903124223",["1600","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=fJ-k2tZ-ltGalJKAosq1q9HHoYOTpWKwqIyZlaCRqJyRppra1ZZkmmdhlWBllZOm0cs&FileName=10.png&ID=64402018045",["1600","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=f82mqquBmaKexZN_oZ2IqqXGoYKW05Ozd4mWxaBodJ2U1Jyqqplna2uSll9kaWalpco&FileName=11.png&ID=45784433158",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=fJ-qramEk6edxWiD0p2C2J6cmIbHoJOze7mZlaBgeZ-RpqCtqJxhcGqSa2OVamDTnqA&FileName=12.png&ID=57810870222",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=hZnZ2Nl9kqGdl1-G05aH2dSZmbKWp2KzfoXGwtKSd8maoM_Y2JVgampkYmaWZGXU1J0&FileName=13.png&ID=10622978415",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=f6LX16auwtOZxJOE08qx2Z_HoICSn2Gxf4yXlaCTfJyUqc3XpcaQnGaRlmSWmY_Un8s&FileName=14.png&ID=95423779012",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=r8rX2qeGlKSfx5Ky0saD1p6ZmLDCopCvp4bJwqOReM7E0c3app5ibWyUlZKVlmHRnp0&FileName=15.png&ID=56614167508",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=ssuppNR9ldGgmZGApcqC2s-bnrGT02WAeLicwqCRfM7H0p-k05Vjmm1mlGBom2DVz58&FileName=16.png&ID=51467736796",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=hMuoqKWylM_MlWKHppW0rdOTzrKTn2KCqorKk6ZmpZuZ0p6opMpimJliZWdpZ5Ko05c&FileName=17.png&ID=95290404451",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=f5ynp6ezmdHKwmOG0siGp56Wyq7D1JWFeoWcmqJhdpuUo52npstnmpePZmaVm2Sinpo&FileName=18.png&ID=28979821112",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=rc7WpKl_wqSZmZOzn8uC2qCVmYXC0mavf7WVwtNhepvC1cykqJeQbWZmlpNin2DVoJk&FileName=19.png&ID=44883235697",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=gZ2nqth-mtHIxpKwoMax1qeVnrKW0pOGf7WelZ9mfJuWpJ2q15ZompWTlZBkkY_Rp5k&FileName=20.png&ID=69552096854",["800","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=rZ6o1auGk9Scw2aG0Jixq6DJzITEo2iFq4yZxNBnqMrCpZ7Vqp5hnWmQaWaUZI-moM0&FileName=21.png&ID=48146465499",["1600","1150"]],["http://mangapedia.fr/project_code/script/image.php?path=r82m16aCxKWemWS1nsu2qaGbobKSopOzrInGwqJkdsrE1JzXpZqSbmtmZ5VimJSeo58&FileName=22.jpg&ID=33289095414",["761","1100"]]];

**Comment by xtj-9182** [comment]
I got swamped with work so I only got around to finish up MangaKawaii now.

I haven't actually worked on MangaPedia :[ 

that said if someone wants to add MangaPedia feel free to do so :D

**Comment by raulhaag** [comment]
mangapedia is realy to slow for me make me crazy waiting response
for me is out

**Comment by raulhaag** [comment]
Hi, @wardijamai0120 i can add (for that i see no filters, to difficult whitout know nothing of the language),  if you can help with the translation of app go to be helpfull  but really don't know how it go to see on RTL disposition

**Comment by raulhaag** [comment]
@wardijamai0120  manga.ae ready for next version
