### ISSUE TITLE
No puedo actualizar la app a 1.63

### ISSUE THREAD

**Issue by Vicelle** [raulhaag/MiMangaNu#417]
Hola! Me encanta la app, pero no puedo instalar esta última actualización. Siempre da el mensaje de "no se instaló la aplicación". Mi celular es un ZTE Maven. 

Estaría sumamente agradecida si me ayudan a resolverlo. 
Gracias!

**Comment by raulhaag** [comment]
Hola perdón por la tardanza, querría saber un par de cosas.
1. Versión de android.
2. Versión actual del App y desde donde la instalaste.
3. Versión problemática y desde donde intentaste instalarla.
Con eso capaz te pueda ayudar un poco.

**Comment by raulhaag** [comment]
Si tenias la version de fdroid y tratas de instalar la de github, te va salir ese error. tenes que quitar esa y instalar la de github

**Comment by Vicelle** [comment]
Tenías razón, la que intentaba instalar era la que me descargó desde la notificación de actualización, que supongo que es la de github. Me instaló perfectamente la de fdroid. Gracias!

Otra preguntita, en qué difieren estas dos?

**Comment by raulhaag** [comment]
la diferencia el la firma, fdroid firma todas las aplicaciones que de su repositorio para garantizar que es el código publicado en el enlace que te dan (una norma de seguridad), estas pueden tardar mas en salir  aunque es un sistema automático lleva un par de días  y la mía que la subo en el momento que la saco a lo máximo 2 días que es el tiempo de búsqueda entre updates dado a la app.

**Comment by Vicelle** [comment]
Aah, vale, gracias por contestar :) 
Cierro el problema~
