### ISSUE TITLE
Not enough feedback on download error

### ISSUE THREAD

**Issue by Nodd** [raulhaag/MiMangaNu#42]
When there is a download error while reading a comic, there is no feedback, and the user is left with a rotating circly. It's only when exiting the "read mode" and going the the download tab that it is possible to see that there was an error.
Si would suggest these changes:
* Warn about the error in a popup
* have the same behavior as when it is not possible to get the number of pages: the user is sent to the chapter list
* append (or prepend) "ERROR" to the title of the chapter having problems.

This problem happens for me in the comic "The Sword of Emperor" from MangaPanda.

**Comment by raulhaag** [comment]
ready on the actual version
