### ISSUE TITLE
JapScan is broken

### ISSUE THREAD

**Issue by lKomus** [raulhaag/MiMangaNu#420]
Selecting mangas and adding them is fine.

But the app cannot download the chapters. It always returns an error as soon as the download starts.

**Comment by raulhaag** [comment]
Tested and working, check again

**Comment by lKomus** [comment]
Yeah it's working again, I'm not sure what happened. There must have been three days where I just couldn't download anything from this source, and the website was working fine too.

Sorry for the non-issue.
