### ISSUE TITLE
Random front image when no image available

### ISSUE THREAD

**Issue by Zykino** [raulhaag/MiMangaNu#421]
On the main page, after following a manga without base image (thank's JapScan) the manga sometimes borrow the front image of an other one.
I better have constantly a "no picture" placeholder than sometime a wrong image for a specific manga.

**Edit:**
![screenshot showing the problem](https://cloud.githubusercontent.com/assets/3809938/26115110/6c04d01e-3a5f-11e7-9c57-5c8901d5089f.png)

**Comment by raulhaag** [comment]
OK the  a recycling view problem, this weekend I will try to fix it

**Comment by Zykino** [comment]
I think it's when you scroll up/down that you can see this the most reliabily

**Comment by raulhaag** [comment]
I recreated this at first, sorry servers I use always has images.

**Comment by raulhaag** [comment]
ready on last travis and for next version
