### ISSUE TITLE
MyMangaNu not glorious fix

### ISSUE THREAD

**Issue by Zykino** [raulhaag/MiMangaNu#423]
Now I have all my "finished" manga showing a double list: one read and the other one as "Télécharger _MangaName_ !".
When I try clicking on it it does not work with the error message:
Error: Could not get the number of pages.

Disclaimer: yes they are late on this manga!
![screenshot showing mi manga nu problem](https://cloud.githubusercontent.com/assets/3809938/26115485/66f9db68-3a60-11e7-8d1a-b15dbe378546.png)

MyMangaNu: v1.63

**Comment by raulhaag** [comment]
As I see they making more changes on they server and a new version go to be needed, the chapters path was changed and that is th reason of duplicated chapters

**Comment by raulhaag** [comment]
Can you share your dB to check differences, etc?

**Comment by Zykino** [comment]
How do I do that? Where do I send it to you (safe on a public github post?)

**Comment by raulhaag** [comment]
really its only have manga information but if you wish send me to raghaag on gmail

**Comment by Zykino** [comment]
But how do I take the database? (I'm not an android dev and didn't saw an option to export the db in the app)

**Comment by raulhaag** [comment]
it's on your externar storage for defaul  /MimangaNu/dbs

**Comment by raulhaag** [comment]
ready for next version
