### ISSUE TITLE
Chaptercounter incorrect

### ISSUE THREAD

**Issue by ManuelH95** [raulhaag/MiMangaNu#424]
Wegen you reload the infopage, the number increases every time. No reset oft the number.

**Comment by raulhaag** [comment]
Any server in special, can't recreate

**Comment by ManuelH95** [comment]
I found this problem at the server mangareader.net

Am 23. Mai 2017 15:34:47 MESZ schrieb Raul <notifications@github.com>:
>Any server in special, can't recreate
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/raulhaag/MiMangaNu/issues/424#issuecomment-303399423

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ManuelH95** [comment]
I also found this bug on SenManga

Am 23. Mai 2017 15:34:47 MESZ schrieb Raul <notifications@github.com>:
>Any server in special, can't recreate
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/raulhaag/MiMangaNu/issues/424#issuecomment-303399423

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by raulhaag** [comment]
ready for next version
