### ISSUE TITLE
App not updating.

### ISSUE THREAD

**Issue by Tasuba** [raulhaag/MiMangaNu#427]
App doesn't have any of the last 2 updates on f-droid and when I try to open the update notification from the app, it crashes.

**Comment by raulhaag** [comment]
I know this problem and I fix it on last version but the updates from github have different sign, I need to add a button like "I use f-droid" to disable this for f-droid  users

**Comment by Tasuba** [comment]
I'm currently still on v1.63 and haven't been able to update as none of the updates have been pushed into f-droid. The latest available update on f-droid is also v1.63

**Comment by raulhaag** [comment]
Yes fdroid take 3 days as least somtimes more than a week

**Comment by raulhaag** [comment]
Fdroid today publish the last version
