### ISSUE TITLE
Enhancement Request: Save Manga Title to Clipboard 

### ISSUE THREAD

**Issue by Gomgoru** [raulhaag/MiMangaNu#429]
This is not a very high 'Need'. It would just speed up some of my online researches. (I'm a very Lazy Person/Software Engineer! With a Very, VERY Short Memory … you know, Bird Brain type: three steps or three words and I've forgotten what I was trying to get acrossed 
… 
excuse me, … I forgot what we were talking about! Uhh where am I by the way? I don't remember a room like this. What do you mean I need to take some medicine! … ) I'm back, AND I DIDN'T HAVE TO WARE THAT FUNNY WHITE JACKET WITH THE FUNNY SLEAVES THAT BUCKLES IN THE BACK! Sorry! Sorry!

__If a button/_menu list item_ were available on the manga title page.__ That would be a big help to me. (and the BIG men in white that are standing around to help us here … Well I've got to go and take my nap now.

**Comment by raulhaag** [comment]
@jordyamc added this, it go to be aviable on next version just taping on the image on the manga information.
👋
