### ISSUE TITLE
TuMangaOnline error

### ISSUE THREAD

**Issue by OnlyAnLector** [raulhaag/MiMangaNu#431]
Hace unos cuantos días, un pequeño error me a estado apareciendo en el servidor de TuMangaOnline, cuando quiero descargar un cap de algun manga no me deja, me da error, y si quiero buscar algun manga nuevo, no me deja, me aparece una ventana negra con varios comandos de Java y de rato desaparece sin  dejarme la opcion de buscar, lo que se me hace más extraño es que solo sucede con mi internet, a que se debera? ojala tenga solucion pues es mi servidor favorito xD

**Comment by raulhaag** [comment]
Yo lo uso y realmente acabo de probar recien descargar un par de capítulos de algun manga ya en mi lista y agregar y andubo todo bien, lo que podrias revisar si tenes espacio.

**Comment by raulhaag** [comment]
por cierto si tenes la version 1.64 actualiza a la 1.65 por que esa si tiene un bug en tmo.

**Comment by OnlyAnLector** [comment]
Tengo la version 1.65 de hecho probé haciendo espacio en mi memoria y nada 
sigue igual

**Comment by raulhaag** [comment]
podes capturar la pantalla del error java? para tener una idea de lo que esta pasando
