### ISSUE TITLE
Bato.to chapters missing 

### ISSUE THREAD

**Issue by s0hvaperuna** [raulhaag/MiMangaNu#434]
Some bato.to series only have a couple chapters properly detected like jojo part 8 where only the 2 latest chapters show (language set to English)

**Comment by raulhaag** [comment]
go to settings and tap on clear all cookies, and reload chapters

**Comment by s0hvaperuna** [comment]
I did that earlier and didn't work, now when I reloaded the app it worked again. I guess it just needed a restart after clearing cookies and logging in
