### ISSUE TITLE
Acciones por rangos de capitulos

### ISSUE THREAD

**Issue by Albrod** [raulhaag/MiMangaNu#435]
Hola, primero que nada queria agradecerte por tan fantastico trabajo.
Ahora continuando con la idea, venia a proponerte que si esta dentro de lo posible agregues para realizar acciones en un rango de capitulos.
Por ejemplo si quiero seleccionar rapidamente del capitulo 100 al 400 de berserk y marcarlos para descargar.
O marcar del 1 al 100 como leidos o no leidos.
Esto seria de gran utilidad.
Saludos

**Comment by raulhaag** [comment]
Hola actualmente si mantienes presionado un capitulo e especial aparece cambia la barra superior y puedes selecionar hasta el principio o hasta el final depende de lo que quieras con las ^ v y aplicarle los cambios a la aplicacion
Saludos y espero que te sirva
