### ISSUE TITLE
Installation stopped after the display of new Accesses needed (none)

### ISSUE THREAD

**Issue by Gomgoru** [raulhaag/MiMangaNu#438]
My installing of version 1.67 stalled after the display of new Accesses for the new APK. Partly. Choosing to continue didn't do anything, while choosing to cancel actually canceled the instillation process.

My machine is a Samsung Galaxy Pro 12.0 Tablet running 'kitkat' Android 4.4.2. 32 GB internal and 64 GB external SD card.

Sincerely, 
Gomgoru

**Comment by raulhaag** [comment]
if youy have the f-droid version you can't install the version from auto updates, the same if you have the github version and you want to install the f-droid, if it's other the problem let me know and screeshot go to be usefull

**Comment by Gomgoru** [comment]
I've been doing some more testing. Looks like it is related to **_SD space!_** If I fill my SDs to full, or nearly full, the I run into several types of problems. _MiMangaNu_ 

- [ ]  does not appear to handle out of memory or out of RAM error very well.
- [ ] mysterious errors while trying to down load new chapters of a manga
- [ ] APK instillation error. Not able to install a APK.
- [ ] _MiMangaNu_ crashes without any appearant cause. 
- [ ] database errors.

You might like to check out every place where an API might return an error of  _**Insufficient Memory**_ or **_Insufficient/Out_of Storage_** or any thing similar

**Comment by raulhaag** [comment]
![imagen](https://user-images.githubusercontent.com/2048339/29968576-a92075f6-8ef2-11e7-94a5-491afd78c00b.png)

i reading app crash reports and there is a not only full disk problem, also reading errors, i use a samsun galaxy tab 3 p5210 but never whitout sd space  all those errors are related to io errors, the ram is released from app but not is instatly collected for the system, at start of the app i have several errors with this but now in the crasshes reports i don't get any error related, and in low memory divice i sugest use the continuos reader that really have a good memory manager and is writed from scratch to load on memory the visible segment, a time ago i thinking on change the paged reader imageview component but no time this days, but i go to implement the catch and a advice when triying to open database.
