### ISSUE TITLE
Continuous reading/big height images and Notification reiceiving

### ISSUE THREAD

**Issue by Zykino** [raulhaag/MiMangaNu#440]
Not sure it's only a continuous reading bug or because "The gamer" have very long images and are not fully displayed.

So I'm in the middle of my reading and suddenly received an SMS.
The location is reset-ed to the top instead of being kept at my current reading point (say 50%).
So I have scroll back the 50% I just read.

Even if I'm already at the beginning of the image there is a little blink of it.

The same thing happen when I let my screen turn of but... It's more acceptable :)

Android 7.1.1

**Comment by raulhaag** [comment]
the proble is the reader seek by page namber to generalize it and not rewrite all for any reader but when a have a litle more time i will try to figure a way to fix it

**Comment by Zykino** [comment]
Is it possible to store the page + height position from the top of the image?

Alternatively you may not rewrite the image after a notification (don't know if you can separate it from an app switch in android)

**Comment by lvjot95** [comment]
On mangahere, mangafox you can read the gamer in splitted mode (non-continuous mode). The translater are are already uploading separate pages.

**Comment by Zykino** [comment]
Thank you but... it's not fixing the problem. Beside that I'm french, I read the manga in French, if it happens to an other manga who is not splitted or referenced in the site you referenced?
You can't rely on "user" input as a "server". Web philosophy apply well here I think.

**Comment by raulhaag** [comment]
Tell me the server and a example to test and try to fix it

**Comment by Zykino** [comment]
MyManga.io the gamer (any page).
May not be a top priority but a nice thing to fix when you have some time :)

**Comment by raulhaag** [comment]
ready for next version, if you want and have the github version you can install the last version on develop from here to test http://mimanganu.byethost5.com/?order=modified&sort=desc&i=1 , only if you have github version (f-droid has other sign=
