### ISSUE TITLE
problema con mi tmo

### ISSUE THREAD

**Issue by xken2x** [raulhaag/MiMangaNu#441]
el servidor de tu manga online presenta continuas fallas, siempre manda error ya sea cuando se buscan actualizaciones de mangas ya agregados o se entra en la pagina principal para ver mas, montare los logs en cuanto esten disponibles

**Comment by ProMisu** [comment]
Yo igual tengo problemas con tumangaonline :/ 
<a href='https://postimg.org/image/opgt4b859/' target='_blank'><img src='https://s6.postimg.org/opgt4b859/Screenshot_2017-09-18-00-16-15.png' border='0' alt='Screenshot_2017-09-18-00-16-15'/></a>

**Comment by raulhaag** [comment]
perdon por la tardanza justo me agarro de vacaciones, ahi ya realice el fix en un rato lo publico y la actualizacion estara disponible dependiendo del lugar de donde la instalaron
