### ISSUE TITLE
App do not want to download even if there is connection

### ISSUE THREAD

**Issue by Zykino** [raulhaag/MiMangaNu#443]
I access internet by WIFI and data.
Often, instead of verifying if there is new chapters to download, MiMangaNu wait for me to switch (on or off) the WIFI.
And I mean a manual switch (going in or out of WIFI range doesn't trigger the search).

The problem is when I'm connected to internet and try to download. MiMangaNu often say me I have no connection until I switch the WIFI button.

**Comment by raulhaag** [comment]
in settings there is a option to ignore internet connections checks to bypass this kind of problem in same divices, tell me if its works for you

**Comment by raulhaag** [comment]
and check if your settings are in only wifi mode to save data usage first

**Comment by Zykino** [comment]
Both options are disabled, I need to enable the first option?

No very clear for a not English native, will try to propose an other EN and FR locales.

**Comment by raulhaag** [comment]
enable the firts switch of connections option, and this disable the internet state check

**Comment by lvjot95** [comment]
turn off your wifi first and then try to download only one chapter with your mobile data, if it starts to download you can turn on wifi and download the other chapters, if it doesn't work there is an issue with the server.
At least for me this trick works.

**Comment by Zykino** [comment]
Setting the first option to "ON I want to disable the internet detection" did the trick.

I think an option shouldn't be "ON to disable", always confuse the user.
