### ISSUE TITLE
Mangahere source bug

### ISSUE THREAD

**Issue by knotchris** [raulhaag/MiMangaNu#445]
As of Yesterday (September 26) Mangahere basically got nuked on this app. I refreshed the homescreen and all the Manga that i had that was sourced from manga here got duplicate chapters which wasn't a big deal but now Mangahere's source in general doesn't work.

**Comment by kalkin19** [comment]
Same issue. Getting a certpathvalidatorexception error for any MangaHere manga I have in my library. Also having issues with MangaEden updates not opening. Havent checked any of the other sites yet

**Comment by hallekamp** [comment]
This issue is not directly related to ssl. Mangahere changed their URLs to omit the protocol ie //www.... instead of https://
It is not fixed in 1.70

**Comment by raulhaag** [comment]
test again the v 1.70 works ok except for the search recently commited
