### ISSUE TITLE
Download errors with mangapanda

### ISSUE THREAD

**Issue by Nodd** [raulhaag/MiMangaNu#45]
I have download errors on there comics, where no chapter can be successfully downloaded:
* The Sword of Emperor
* A Thousand Years Ninetails
* Stravaganza - Isai no Hime
* Full Metal Wing

The 9 first chapters of "Tate no Yuusha no Nariagari" work fine, but the 10th one can't be downloaded.

**Comment by raulhaag** [comment]
The Tuesday whit time I will check this and the feedback on error

**Comment by Nodd** [comment]
Thanks a lot !

**Comment by raulhaag** [comment]
http://www.mangapanda.com/tate-no-yuusha-no-nariagari/10/3
when the server has errors on image uploaded i can´t do anything  but i need to add an feedback like an error image in this cases

**Comment by Nodd** [comment]
Sorry, I did not check on the website. Will do next time !

**Comment by raulhaag** [comment]
added feedback on error while readind in next, check on fdroid in few days

**Comment by Nodd** [comment]
Wonderful ! :)
