### ISSUE TITLE
Aun con problemas mimanga online

### ISSUE THREAD

**Issue by Fliqpy** [raulhaag/MiMangaNu#450]
Ya instale la version 1.68 y ya me permite entrar al servidor pero al agregar cualquier manga no agrega los capítulos solo lo que es el acceso al manga 0 capítulos he intentado borrar cookies y limpiar la base datos. Excelente aplicacion, muchas gracias por tu trabajo.

**Comment by raulhaag** [comment]
si en el momento que lo saque funcionaba pero veo que ahora ya cambiaron algo mas posiblemente mañana me ponga con estos fixes y otros pedidos

**Comment by Fliqpy** [comment]
Muchas gracias por todo el trabajo que haces ya aparecen los capítulos pero no se si el problema se solo mi pero solo agrega 25 capítulos de cualquier manga no importa si tiene mas de 100 capítulos termina agregando los últimos 5 capítulos por favor verifica eso muchas gracias

**Comment by raulhaag** [comment]
Para este servidor cuando se cargan los capítulos se usa la carga rápida para actualizaciones ya que tiene paginación si lo desactivas desde las configuraciones te va a cargar todos los capítulos pero la búsqueda después actualizaciones a ser más lenta así que al final te conviene activarlo de nuevo

**Comment by Fliqpy** [comment]
Lo he intentado la opción de actualización de mangas. Y no me funciona no se que otra cosa podría hacer ya que es molesto que solo aparezcan los últimos 25 capítulos tengo que ir a la pagina web para leer los primeros capitulos

**Comment by raulhaag** [comment]
volvieron a cambiar un par de cosas, estan haciendo cambios, hay que esperar un par de dias que cuando terminen hago el fix final
