### ISSUE TITLE
Japscan and Mangakawaii not working

### ISSUE THREAD

**Issue by Fraulk** [raulhaag/MiMangaNu#452]
For Mangakawaii i think it's caused by the ddos protection. Japscan's navigation is working and new chapters appear but show error every time when i try to read a chapter  : 
![image](https://user-images.githubusercontent.com/25487503/31054783-90bf4c3c-a6ba-11e7-8ff7-68f076145812.png)

**Comment by raulhaag** [comment]
fix ready for next version
