### ISSUE TITLE
Tengo dos problemas

### ISSUE THREAD

**Issue by Ignusdark** [raulhaag/MiMangaNu#454]
Antes que nada muchísimas gracias por el gran trabajo que haces con la aplicación, de verdad que se agradece bastante el poder leer mangas desde el celular.

Pues en sí con la aplicación tengo dos problemas que no sé porqué pasan. El primero es que no se me actualiza desde descarga de la app. O sea, pongo para descargar la nueva versión y todo pero ya que está descargada cuando le doy a instalación al inicio parece que todo bien pero después de un tiempo me sale que no se pudo instalar. Para pasar de la 1.67 a la 1.68 tuve que esperar a encontrar el apk de la actualización por la web para actualizar y ahora para la 1.70 no puedo.

El otro es con el servidor de TuMangaOnline, todo manga de ese servidor no se pueden leer, ni siquiera se encuentran las portadas.

**Comment by raulhaag** [comment]
Hola te paso a explicar de la aplicacion hay dos versiones probablemente tengas la de F-Droid que se toma un tiempo hasta que sale y esa se actualiza desde la aplicacion propia de fdroid (por lo que tendrias que desactivar la busqueda de actualizaciones que son de la version de github), por eso no podes instalar la version de  github (ya que fdroid verifica el codigo con su propia firma y la version de github esta con mi firma propia), acerca de tmo esta casi solucionado totalmente en la v1.70 y ya lista en la version de desarrollo que probablemente saque una version nueva el fin de samana, pero para fdroid le lleva una par de dias mas.
saludos y espero que se entienda

**Comment by Ignusdark** [comment]
Bueno, el primero ya lo solucione cambiandome a la versión de Github, ¡gracias!

Sobre el segundo, ya tengo la 1.70 y el problema con tmo sigue, más específicamente que ni las portadas cargan, y cuando quiero entrar a un capítulo no los descarga:c

**Comment by raulhaag** [comment]
lo prove y esta funcionando bien, decime tu version del sistema para ver si es una problema en especial si no tenes muchas cosas agregados podes intentar borrar la carpeta de mimanganu en el almacenamiento externo que a algunos al cambiar de firma les causa problemas pero eso solo si no te importa empesar de 0

**Comment by raulhaag** [comment]
espera que prove co instalacion desde 0 y si da ese problema

**Comment by Ignusdark** [comment]
Vengo para informar que el problema con TMO se arregló por si soon el día de hoy. No entiendo cómo pero simplemente entre a la app y al buscar nuevos capitulos pues todos los mangas de ese servidor empezaron a funcionar xD. Supongo que era algún problema mío entonces, o no se. 

Igualmente, ¡muchas gracias por traer tan grandiosa app!
