### ISSUE TITLE
Refresh adds chapters already present in list

### ISSUE THREAD

**Issue by M1Russia** [raulhaag/MiMangaNu#456]
Hello,
When I updated my list of manga, it added already present chapters and flagged them "new".
The issue seems to happen only with mangahere and mangafox.

I attached screeshot of the results. 

Is there a way to get back to normal? 

Thanks for the great app by the way

Cheers

![screenshot_20171005-220125](https://user-images.githubusercontent.com/4397343/31251016-e77cbcc0-aa1c-11e7-8f2d-db73510e20a7.png)
![screenshot_20171005-220158](https://user-images.githubusercontent.com/4397343/31251026-ef6f56a4-aa1c-11e7-8f29-c867e0d632d7.png)

**Comment by tempura-san** [comment]
Please see my comment on #455 if it applies to you as well.

**Comment by M1Russia** [comment]
Ok I'll report to you after installing 70.

Thank you

**Comment by tempura-san** [comment]
You're welcome, but please note: even after 1.70 the duplicates will still remain in the database. The easiest way to fix this is to remove and add the Manga once again (or you could fix the SQlite DB on the device - but this is much trickier).

**Comment by tempura-san** [comment]
MiMangaNu version 1.71 is available since 2017-10-18. Could you please check and report back if this issue is fixed by updating to the newer version?

**Comment by M1Russia** [comment]
Hello,
Sorry for the late update, yes it is working fine now.

Thank you very much for your work

Cheers
