### ISSUE TITLE
TuMangaOnline no carga el manga completo

### ISSUE THREAD

**Issue by AyumuMiyazaki** [raulhaag/MiMangaNu#458]
Hola! Gracias por tu trabajo! Me descargué la versión 1.70 y veo que al agregar un manga desde  TuMangaOnline solo carga los últimos 25 capítulos del manga, sabrás a qué se deberá eso?

**Comment by raulhaag** [comment]
si ya esta previsto para la proxima version solo que todabia no esta publicada, si usas la version de github podes instalar la version de desarrollo que tiene la misma firma desde mimanganu.byethost5.com/?order=modified&sort=desc que son las autocompiladas por el sistema travis y con mi firma

**Comment by AyumuMiyazaki** [comment]
Oh genial! Muchas gracias por responder! Sí uso la versión de Github pero esperaré a la versión estable de la próxima versión! Gracias por su esfuerzo!

**Comment by marrokin** [comment]
TuMangaOnline ha cambiado su servicio y ahora en MMN no funciona  :-1:
