### ISSUE TITLE
Mark several chapter as read

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#46]
Is it possible to have a way to mark several manga as read ? Like selecting multiple manga and marking them as read ?

**Comment by raulhaag** [comment]
mmm isn't imposible but long press action already taken for reset an delete, let me think a way to do it, or if you have any idea tellme.

**Comment by Dostoi** [comment]
Or having a button in the option menu, "Mark chapter(s) as read" and when you choose it, you can select chapter just by taping on them, and on the top instead of the regular button (change order and all) there will be a button to confirm and one to cancel.

**Comment by tenebr050** [comment]
Instead of a context menu, you could move all the options to the top actionbar. That is what Google recommends since Ice Cream Sandwich anyway.

**Comment by raulhaag** [comment]
yes as action mode but not sure about compatibility < Honeycomb i will check it

**Comment by raulhaag** [comment]
new commit test when ready on fdroid :smile:
