### ISSUE TITLE
NineManga

### ISSUE THREAD

**Issue by kenshiro55** [raulhaag/MiMangaNu#462]
Hello, 

When I try to read on Ninemanga, a popup with this message is showed:

> Too many errors (Download suspended)
> This may be caused by:
> A connection error
> An error on the server side
> A bad upload, etc
> Try again later

The app works if I try to read on another server. If I try to read on ninemanga website, I don't have any problems.

**Comment by tempura-san** [comment]
@kenshiro55 Is this working in the current version? If so, could you please close this issue? Thx!
