### ISSUE TITLE
Lastest update filter is broken on kissmanga

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#468]
It shows the same result as the popularity filter. With no genre selected.

With the latest version of f-droid.

And I'm glad to see that you're still developing the app after all this time :-)

**Comment by raulhaag** [comment]
Hi, im on it when i have time and lucky for me always when im not have much somebody fork and help me, 2 hours ago tempura-san make a pull request for this.
Good to read you to 👋

**Comment by Dostoi** [comment]
Nice to have people helping you ! (and fast to react too ^^)

**Comment by tempura-san** [comment]
I just had some spare time at hand. So don't rely on me too much. :sweat:

**Comment by tempura-san** [comment]
@Dostoi Does it work as expected now? If so, could you close this issue, please? Thx!
