### ISSUE TITLE
Lock zoom

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#47]
Sometimes the writing are too small to read without zooming for a whole chapter, it will be nice to be able to lock the zoom so it will stay the same for several pages.

**Comment by raulhaag** [comment]
i don't figure a good way to do it :bulb:

**Comment by Dostoi** [comment]
Having an option next to the one to change the size of the picture could be better. If you were wondering on something else I can't help x)

**Comment by scaPEGoatno** [comment]
you can look https://github.com/jparkie/Aizoban for reference to the lock zoom feature(english is so bad...)

**Comment by Johndeep** [comment]
The problem why the zoom level is not saved is that the pages are currently only loaded in memory on the fly, so it'll lose the page configuration after you leave at least two pages. But this saves memory.

So one way (I think a reasonable one) to solve this problem, each manga (or chapter if you like) has to save the zoom state (float maybe?) somewhere, which will be loaded right after loading the page in memory.

Could look into it, seems to be useful for mangas with damn little fonts.

**Comment by raulhaag** [comment]
lock zoom on new vertical reader is base :-P

**Comment by Dostoi** [comment]
You're working hard these days ^^

**Comment by Johndeep** [comment]
Did you also replaced the horizontal reading already, because I saw some new code about R2L- and L2RReader, @raulhaag ?

**Comment by raulhaag** [comment]
@Johndeep not, but the class are ready to do, just thinking in the best way to do, and if there is a way to change while reading

**Comment by Dostoi** [comment]
The app is really perfect now :)
