### ISSUE TITLE
Problem with SenManga

### ISSUE THREAD

**Issue by kenshiro55** [raulhaag/MiMangaNu#475]
Hello,

when I choose SenManga, MiMangaNu 1.71 cannot load the list of titles.

**Comment by raulhaag** [comment]
its ready for next version (but no sure if 100% compatible with the previews one just because they change a couple of things, and i don't have mangas added in my db from there to compare)

**Comment by tempura-san** [comment]
@kenshiro55 Is the problem fixed with the current version? If so, could you please close this issue? Thx!
