### ISSUE TITLE
issue with mangapanda

### ISSUE THREAD

**Issue by Vitelia** [raulhaag/MiMangaNu#479]
When you add a manga from mangapanda, the db chapters table list the chapters as mangareader links.
When mimanganu tries to do an automatic-update to that manga, it adds the correct links from mangapanda, making it a list with double links (a force-update doesn't add those correct links)

Checked just now in v1.72 installed from Fdroid so i don't know if it was already fixed in v1.73. 
Couldn't found anything about it on the issue list.

**Comment by tempura-san** [comment]
Thanks for reporting - the referenced pull request will fix this (1.73 is affected as well).

**Comment by Vitelia** [comment]
Thank you for the quick response!
