### ISSUE TITLE
Delete multiple download in one go if chapter is read

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#48]
Now that we can mark several chapter chapter as read it would be nice to be able to delete multiple downloaded chapter in one time if the chapter is read.
By that I mean only delete the downloaded picture, not really the chapter.

I swear I'll stop bother you at some point ^^

**Comment by raulhaag** [comment]
clean image cache is good idea but i need icons I use already the trash to delete openbook whith a V to mark as read an reset to reset the chapters (plus info 1.19 not out becuase i forget to change the version number in manifest :stuck_out_tongue: )

**Comment by Dostoi** [comment]
I don't know how you can do it then ^^
Too much work x)

**Comment by raulhaag** [comment]
Free space deleting readed manga images can be an option on chapter menu

**Comment by Dostoi** [comment]
Yes it would be nice like that

**Comment by raulhaag** [comment]
ready on the next version

**Comment by Dostoi** [comment]
You're working hard today ^^

**Comment by raulhaag** [comment]
only minor fix no complex, no much time, only the icon are the problem

**Comment by Dostoi** [comment]
You're waiting before updating the android manifest ?

**Comment by raulhaag** [comment]
Writing a couple of things on todo list before the update

**Comment by Dostoi** [comment]
Ok :)
