### ISSUE TITLE
Chapter reader not showing all pages

### ISSUE THREAD

**Issue by lephe** [raulhaag/MiMangaNu#485]
The following issue happens on Android 4.1.2 running Mi Manga Nu 1.73 (installed through F-Droid).

Occasionally, when reading a chapter, some pages are not displayed and the screen remains black until I switch to some other "valid" page. I can still browse through the chapter normally, as if the problematic pages were just black rectangles. I encountered this issue on at least two different servers.

I have tried to re-download the chapters several times, ensuring that there were no issue with the download proper. Browsing the phone's memory (no SD card involved), I found out that the images were at the correct place, with the proper names, and completely valid JPG files.

I can point out specific servers/mangas/chapters if required to reproduce the issue, or try patches on my device (although I have no experience working with Android apps).

**Comment by raulhaag** [comment]
Hi, tray this, got ot settings and set max textute size to 1024, and in the manga change to continuous reader, is probable in old divices to have a low size texture cache, please give a feedback.

**Comment by lephe** [comment]
Yes, it works fine with these settings!

It's just a bit difficult to use since it's a comic with very long pages (standard width, large height) and the continuous reader fits the whole image on the screen, scaling it down a lot. On some chapters, the whole *chapter* fits on the screen because there are only a few, large images. And the zoom is quite unresponsive due to the "chapter image" being even larger.

(But I can stick to this if there's nothing simple to solve the issue with the non-continuous reader.)

**Comment by lephe** [comment]
The new settings have been behaving properly since then, so I'm closing this. Thank you!
