### ISSUE TITLE
Can't download manga from readmanga. Today

### ISSUE THREAD

**Issue by xmithosx** [raulhaag/MiMangaNu#487]
No puedo descargar losnmanga desde readmanga.today dice demasiados errores (descarga suspendida) en el navegador la pagina me va bien, pero al descargar no puedo, el error me salta practicamente de inmediato que abro un capitulo o que le doy a descargar.

**Comment by xmithosx** [comment]
I can not download the manga from readmanga.today, the app says too many errors (download suspended), in the browser the webpage is fine, but when I try to download the app it does not let me, the error jumps me almost immediately that I open a chapter or that I give to download.

**Comment by raulhaag** [comment]
lo probe cuando pueda lo arreglo

**Comment by raulhaag** [comment]
listo para la proxima version

**Comment by xmithosx** [comment]
Gracias!!! Ahora a esperar pacientemente...
