### ISSUE TITLE
Mangahere not working

### ISSUE THREAD

**Issue by GyanPreet** [raulhaag/MiMangaNu#488]
Mangahere hasnt been working for two weeks
It doesnt download it just says couldnt load page count.
Plz fix, i hate to fall behind.
Thank you in advance, for all your hard work fpr leeping this app updated and running.
Dev. You are the best

**Comment by tempura-san** [comment]
This is a duplicate of #481 and should already be resolved for 1.74.
Please check again once the new release is out.
