### ISSUE TITLE
Mangapedia has changed domain name

### ISSUE THREAD

**Issue by Fraulk** [raulhaag/MiMangaNu#489]
So it's not possible to load the chapters
Error name : Could not load page count

**Comment by raulhaag** [comment]
.com to eu?

**Comment by Fraulk** [comment]
Yes

**Comment by tempura-san** [comment]
@raulhaag I'm afraid something went wrong on F-Droid when building 1.74 (see https://f-droid.org/wiki/page/ar.rulosoft.mimanganu#1.74) - just in case people are asking when 1.74 will appear...

**Comment by raulhaag** [comment]
Not sure about the error (they can't download a library) but is from
fdroid side, they dame sometimes retry and others just need to wait to next
release.

**Comment by Fraulk** [comment]
Finally it has changed again to .fr lol
