### ISSUE TITLE
can t see manga from japscan

### ISSUE THREAD

**Issue by tom2411** [raulhaag/MiMangaNu#495]
Hello
I want watch some manga from japscan so for example i take shingeki no kyojin but when a click on a chapiter it print me a windows that tell me that i have a problem
Can you help me ?

**Comment by raulhaag** [comment]
the fix is ready for next version

**Comment by tom2411** [comment]
And when the next version plan to be realese ?

**Comment by raulhaag** [comment]
today and on f droid on 2-4 days

**Comment by tom2411** [comment]
thanks for your answer but I can't see the cover of a manga from japscan in my favourite one.

**Comment by tempura-san** [comment]
JapScan does not provide cover images. At least the plugin does not scan for any.
But this is no recent change - it has been like that for a long time AFAIK.

**Comment by tom2411** [comment]
do you plan to put covers or not, just to don't hope for nothing ??

**Comment by tempura-san** [comment]
Just checked myself, as I do not use JapScan: I do not see any cover image for e.g. http://www.japscan.com/mangas/shingeki-no-kyojin/ - neither for any other Manga as JapScan does not provide them.
What isn't there, can't be added. So there won't be any cover images for JapScan sourced Manga.

**Comment by tom2411** [comment]
Thanks you for all your answer, with those i can close this issue.

**Comment by tempura-san** [comment]
You're welcome.
