### ISSUE TITLE
can't download some chapter 

### ISSUE THREAD

**Issue by tom2411** [raulhaag/MiMangaNu#497]
For some chapter, I can't download them when I try it shows me a error message.
It happen for example on the chapter 121 -> 128 of UQ Holder! and on the chapter 100 of Shingeki no Kyojin.
I take all my manga from Japscan.
Can you help me please ?

**Comment by raulhaag** [comment]
those chapter have this kind of images http://ww1.japscan.com/cr_images/UQ-Holder/121/01.jpg

**Comment by tom2411** [comment]
So we can't do something to have a good images ??

**Comment by tom2411** [comment]
How japscan do to show a good image ??

**Comment by raulhaag** [comment]
They use a css backgroud to rearrange the tiles

**Comment by tom2411** [comment]
Can't we use the same ???

**Comment by tom2411** [comment]
because i see that there are more and more chapter that we can't read for example the last scan of snk.
so it is very frustrating.

**Comment by tom2411** [comment]
Hello there is the problem again we can't access to the chapter.
