### ISSUE TITLE
MiMangaNu cannot download page 10 on NineManga

### ISSUE THREAD

**Issue by kenshiro55** [raulhaag/MiMangaNu#498]
I tried to read a few chapters on NineManga but page 10 failed to load on each of them, it's the indeterminate progressbar that's shown.  Page 11 until the end load fine.

v1.74 F-Droid.

**Comment by tempura-san** [comment]
FYI: @raulhaag fixed this in 41a0ac5dd8b2319df7906cdbd580a86c8cb6ceef so the issue should be gone with the next release (1.76).

**Comment by tom2411** [comment]
When is schedule the release of the 1.76 ??
