### ISSUE TITLE
Connection issues with Mangahere

### ISSUE THREAD

**Issue by GamaXplorer** [raulhaag/MiMangaNu#499]
When i try to access the server it gives me a giant error.
The error starts with: " java.net.ConnectException: Failed to connect to www.mangahere.co/ ..."
I rushed this issue but if necessary i'll provide the full error mensage.

**Comment by tempura-san** [comment]
MangaHere has changed its web presence to http://www.mangahere.cc. This has two implications:

- MiMangaNu cannot connect, as it tries to contact https://www.mangahere.co - which is not serviced ATM (read: down). This is basically what the exception says.
- Older Manga stored in the DB use the host http://www.mangahere.co and as this host is used to fetch the Manga page (and MangaHere redirects to the .cc address) it will find 'new' chapters as the URLs are differing.

@raulhaag For the first, a change of the host to the new one and sticking to `http:` as protocol is sufficient to get it running. The second remains an issue, as new chapters are identified by comparing their URL in the `Chapter` class. So for all MangaHere Manga, MiMangaNu will report new chapters. Would it make sense to compare chapters by the path (i.e. without protocol and host information) only?

**Comment by tempura-san** [comment]
@raulhaag Just another idea: wouldn't it be better to store in the `Chapter` object only the relative path? This seems to be done for some other servers, but not for MangaHere (besides others). At least this should be a guideline for new server additions - for the existing ones a migration scenario would be needed to avoid false addition of 'new' chapters.

**Comment by tempura-san** [comment]
@raulhaag The commit 31d36ebce9070b8d1fb8381d5ffe382a1ddd99de in #500 would be an idea for a transition scenario. If the path is a valid URL, strip off protocol and host, otherwise use it as is (assuming it is already just the path portion).
What do you think?

**Comment by raulhaag** [comment]
@tempura-san relative path are good idea until 2 servers use the same path and it's the unique id for sql instead of the conjunction of path and serverId changes (this may be changed before implement this), database update can be do to already added chapters to save relative paths only
about this error, the https don't working on the server, for the moment, don't know if permanently
