### ISSUE TITLE
No more option menu button

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#50]
With the last version I don't have the option menu button anymore on the main menu.
It can still be accessed with the phone default option button so I don't know if this is done on purpose or not ^^

**Comment by raulhaag** [comment]
The menu a kind forced in passed versions now I make the system default management, in same devices on menu button.  Just in case android version y divice?

**Comment by Dostoi** [comment]
I'm using a wiko cink peak 2 with android 4.1.2

**Comment by raulhaag** [comment]
most of devices with "hard" buttons of meno the os use it as default.

**Comment by Dostoi** [comment]
Ok that must be the reason

**Comment by raulhaag** [comment]
the chapter go to be the same follow the android desing guide
