### ISSUE TITLE
Change the application to the apk version instead of the f-droid version without losing the database

### ISSUE THREAD

**Issue by Fraulk** [raulhaag/MiMangaNu#503]
Updates take too long to appear on f-droid so is it possible to update with the apk and keep the manga database ?

**Comment by tempura-san** [comment]
When switching versions, the old version needs to be uninstalled first. This step will remove also likely remove the MiMangaNu directory (which holds the database). So be sure to make a backup first!
Once the new version is installed, restore the MiMangaNu directory and start the application. All the preferences will be lost, but the Manga list should still be there.

I haven't tried this myself - so once again, please make a backup first! And don't blame me if it should mess things up.

Let me know how it turned out for you in case other people want to do the same. Thanks!

**Comment by raulhaag** [comment]
No backup needed the mimanganu dir on external sd is keeped and if you want
you can make a db backup, only config is lose.

**Comment by raulhaag** [comment]
Db backup is a good idea only just in case

**Comment by Fraulk** [comment]
I did a backup but it says me that there is an error while it add a server to the db on the 1.76
And when i've install the 1.74 it keeps my settings and the db

**Comment by Fraulk** [comment]
Same with the 1.75, and when i update when im on the 1.74 the database error appear

**Comment by tempura-san** [comment]
Could you be more specific on the 'database error'? I wonder what could go wrong.

How did you do the backup/restore process? What steps did you take during the update?

**Comment by raulhaag** [comment]
if you go from fdroid (version 1.74 database version 18) to gh ( version 1.76 database version 20), but if go from gh to fdroid you have to restore the db backup, because databe downgrade is not supported

**Comment by Fraulk** [comment]
I had this when i tried to update to 1.76
And the backup i did was on the f-droid version but it works with the apk version on 1.74
![screenshot_20171225-135849_1024](https://user-images.githubusercontent.com/25487503/34340008-5e8dee9e-e97c-11e7-834c-e2a902028a6f.png)

**Comment by raulhaag** [comment]
can't you get logcat?

2017-12-25 10:06 GMT-03:00 Fraulk <notifications@github.com>:

**Comment by Fraulk** [comment]
how ?

**Comment by tempura-san** [comment]
Here is a short description from the Kodi Wiki:
http://kodi.wiki/view/Android_FAQ#How_can_I_obtain_a_Crash_Log_.28logcat.29

Most likely your device will not be rooted, so you'll need to go via the Android SDK/ `adb`.

**Comment by Fraulk** [comment]
I can't root it and i'm so lazy to do it by the other way so is a video can be suficiently ?

**Comment by Fraulk** [comment]
I did it with another rooted device and there is no error, downloaded first on f-droid deleted it and dl the apk on 1.76 and no error, i paste the backup also no error

**Comment by Fraulk** [comment]
Ok so forget what i said, i don't know how but i fixed it, i'm in 1.76 and the database is working

**Comment by tempura-san** [comment]
Good to hear it is working now - maybe season's luck? :christmas_tree: :smile: 

Unfortunately there is no easy way to get a logcat besides the two ways mentioned above... As many types of database errors map to the same error message displayed in the UI it is hard to find out what could be the problem.

@raulhaag Maybe adding the exception text (not the full trace) to the Toast would help narrowing stuff down in the future?
