### ISSUE TITLE
Mangahere's search results fails

### ISSUE THREAD

**Issue by GamaXplorer** [raulhaag/MiMangaNu#508]
All search results for mangahere are unattainable.

No matter what i've searched for, most of the information is unavailable(n/a) and fails to be added to the database.

**Comment by tempura-san** [comment]
Which version are you using?

In the latest `master` the information is fetched properly, but the server seems to use a similar detection as MangaTown: when downloading a chapter, the pages will 503 after the first 3-5. Some throttling should fix this like for other server.

**Comment by raulhaag** [comment]
confirmed and fixed

**Comment by tempura-san** [comment]
Damn - I misread the headline. Haven't checked the **search** function. Sorry. :sweat: 

@raulhaag nonetheless - to you also see the 503 error code, when downloading complete chapters?

**Comment by GamaXplorer** [comment]
@tempura-san no worries, and thank you and @raulhaag for doing god's work.
