### ISSUE TITLE
 the application closes in the update 1.78

### ISSUE THREAD

**Issue by cawaren** [raulhaag/MiMangaNu#511]
after the update, it closes when you open a chapter and from there you can not reopen again.

**Comment by raulhaag** [comment]
please give me hint, othis is when you try to open the chapter it close the app?

**Comment by cawaren** [comment]
The chapter

**Comment by cawaren** [comment]
Yes,the app closes and when you try to open the chapter again it closes

**Comment by cawaren** [comment]
simply, the application closes when you open a chapter and you can not reopen the same chapter because it closes

**Comment by raulhaag** [comment]
in the chapter name says 0/number of pages?

**Comment by raulhaag** [comment]
about it try to reset chapter (long press and select menu) and on next version a fix go to be made for this not be repeated

**Comment by cawaren** [comment]
Restarting is solved,thank you.
