### ISSUE TITLE
The problem of the css filter of the japscan site

### ISSUE THREAD

**Issue by tom2411** [raulhaag/MiMangaNu#513]
I know that there is a css filter on some chapiters on japscan.com but can t we do something for that ???

**Comment by tom2411** [comment]
Someone can answer me please ??

**Comment by tom2411** [comment]
Because japscan.com it is a good reference. They have also a lot of manga.

**Comment by raulhaag** [comment]
sorry but programing is not magic, css is an script laguage and an implementation is out of any discution, about if it can be done somethin to make those image readable, the response is yes, a post procces on downloaded image can be done but is to much work for a single server.
