### ISSUE TITLE
App Crashing everytime it loads downloaded manga

### ISSUE THREAD

**Issue by GyanPreet** [raulhaag/MiMangaNu#515]
The app is crashing when it loads the downloaded manga. 
If i dont have it saved in my phone then it lets me read it, but if i download the manga and try to open it, the app crashes.
Issue first seen with the new update (1.78)
I would be nice if fixed,to be able to read manga offline.
Thank you,
Good job on the app though, best one out there

**Comment by tempura-san** [comment]
Can you do a `logcat` when the problem happens? Is it only one particular Manga/server or does it happen for any?

**Comment by raulhaag** [comment]
try change read direction (if its solve the fix is ready on next version) posible related to https://github.com/raulhaag/MiMangaNu/issues/511

**Comment by raulhaag** [comment]
test last version and please feeback

**Comment by Gamayun** [comment]
Yep. Happens on 1.78, only when reading direction is right to left. Regardless of server. Changing direction prevents the crash. 
I assume that means the fix is already in the update... Awesome! :)
