### ISSUE TITLE
Problemas al descargar capitulos de readmanga.today

### ISSUE THREAD

**Issue by xmithosx** [raulhaag/MiMangaNu#517]
Hola, al buscar nuevos mangas consigue las actualizaciones, pero al intenter descargar los capitulos la coma de descarga se queda como en espera sin iniciar la descarga y al abrir el capitulo es como si nunca pudiera comenzar, gracias por tu esfuerzo.

**Comment by raulhaag** [comment]
coma de descarga? algún ejemplo de manga / capítulo

**Comment by xmithosx** [comment]
Aparentemente ayer comenzo a funcionr, pero me pasaba por ejemplo con DICE cap 206 y 207, tambien con Hunter x Hunter cap 371, Goblin Slayer del cap 17 al 20 y varios mas...

Aunque no se si fue algo temporal pues ayer todos esos que comento descargaron sin dar error.

**Comment by raulhaag** [comment]
ok cerrando
