### ISSUE TITLE
Add mangadex parser 

### ISSUE THREAD

**Issue by s0hvaperuna** [raulhaag/MiMangaNu#521]
https://mangadex.com has kinda become a replacement for bato.to so it would be nice to have MiMangaNu add a parser that can dl manga from that site

**Comment by raulhaag** [comment]
let me check this in the weekend and see if its viable

**Comment by raulhaag** [comment]
they are currently modifing the paga day to day, if you advert when thiss change finish i will try to add this, i leave this open

**Comment by lenisko** [comment]
looks stable now
