### ISSUE TITLE
F-Droid version still at 1.74

### ISSUE THREAD

**Issue by M1Russia** [raulhaag/MiMangaNu#522]
Hello,

the F-Droid version isn't updated anymore, did you choose to stop with it? 
Should I use directly the apk from here now?

Also thank you so much for continuing to work on mi manga nu, I would be lost without it.

**Comment by raulhaag** [comment]
Check the issue #519

**Comment by M1Russia** [comment]
Oh ok, sorry I didn't search in closed issue.

By the way is there a way to donate and support the app? I don't see a button or link anywhere

**Comment by raulhaag** [comment]
There is not a way for donate, just to demonstrate that there is not any
kind of profit on it,  but thanks
