### ISSUE TITLE
Unas posibles sugerencias 

### ISSUE THREAD

**Issue by AceHeike** [raulhaag/MiMangaNu#523]
•Hola y muy buenas.

Antes que nada quisiera agradecer (ya que es mi primera vez aquí) por este gran proyecto  que ha ido creciendo y evolucionando, adaptándose a los cambios y  mejorando sus funciones con cada actualización, dándole a este grupo de seguidores un lugar donde despejar su mente y alma.
Respecto a lo que quería comentar, es acerca de la posibilidad de añadir un sistema de guardado y sincronización en la nube de los mangas (concretamente los datos que lee la aplicación para mostrar los favoritos que  hemos ido añadido), [algo así como funciona las copias de Whats@pp] con Dropbox o Google Drive. 
Y para terminar y no se haga más largo,  como petición que hago en nombre de varios amig@s que usamos esta grandiosa aplicación es: Podría añadirse esta fuente para la categoría RAW [ http://mangaraw.online  ] ??     Se que ya hay una y conocida por muchos, pero no suelen hacer actualización constante de todo su contenido, o al menos no tan rápido como la que he indicado. 

De antemano muchas gracias por el trabajo y las molestias al tener que leer todo esto,  ánimos con este proyecto y larga vida a  >>  MiMangaNu !!  ☺️

**Comment by raulhaag** [comment]
hola, gracias por los animos que siempre van bien especialmente ya que es de lo unico que nos nutrimos los desarrolladores de código abierto, acerca del sitio de raw, por el momento solo hay uno asi que no hay problemas en agregarlo asi que el fin de semana con suerte y tiempo lo agrego si es viable (lo mas seguro es que si), acerca del auto backup realmente prefiero que se utilizen aplicaciones externas para esto, aunque ha habido varias peticiones sobre esto y quizas algún dia cuando termine las ideas que tengo en mente para la app lo haga

**Comment by raulhaag** [comment]
ya agregue el sitio estara disponible en la proxima version, lo mejor que puede hacer cualquier persona por el proyecto es difundirlo

**Comment by AceHeike** [comment]
Perfecto y gracias por el esfuerzo que pones en ello.
De difundirlo ni te preocupes a todos los que les he mostrado esta app les ha encantado y lo van difundiendo también.
