### ISSUE TITLE
VatotoCom isn't working properly

### ISSUE THREAD

**Issue by Fraulk** [raulhaag/MiMangaNu#524]
Only the first mangas appear when i open the server, when i swipe down the same mangas appear again, same for the research : 

![image](https://user-images.githubusercontent.com/25487503/36225158-10ffc78a-11ca-11e8-90e1-d937fbb12502.png) ![image](https://user-images.githubusercontent.com/25487503/36225218-43411870-11ca-11e8-9894-c9ad340d2eaa.png)
![image](https://user-images.githubusercontent.com/25487503/36225315-9052aafc-11ca-11e8-9bef-7bf5bcf4caec.png)

**Comment by raulhaag** [comment]
enter here and click on load more, as update log says vatoto is not fully functional yet, like the real page

**Comment by Fraulk** [comment]
Batoto seems be back https://bato.to/
