### ISSUE TITLE
V. 1.79

### ISSUE THREAD

**Issue by marrokin** [raulhaag/MiMangaNu#526]
Buenos dias/tardes/noches
Buen trabajo por el esfuerzo y en la manera como se esta llevando el proyecto.

En esta version veo dos problemas no son de mayor relevancia pero si son incomodos para el ux
1. Al hacer click mantener presionada la portada de un manga antes aparexia la opcion de borrar el manga ahora no aparece
2. Al forzar la actualizacion no se refresca la pantalla de portada to entrar en un manga y volver a salir para que aparezcan las actualizaciones.

Por ahora solo esas dos cosas 

De todas formas gracias por este gran esfuerzo 

Exitos!! 👍

**Comment by raulhaag** [comment]
ok,  si cambie un par de cosas en la portada por lo visto se me olvido esa parte implementar, para la v1.80 estara resuelto

**Comment by raulhaag** [comment]
ya arreglado para la proxima version
