### ISSUE TITLE
Búsqueda V1.79 

### ISSUE THREAD

**Issue by lopoles** [raulhaag/MiMangaNu#527]
Hola, felicitaciones por el gran proyecto que están llevando a cavo, es una app muy útil .

Quería notificar un pequeño problema que no es muy grande pero molesta un poco si tienes una gran cantidad de mangas agregados

Antes buscabas un manga en tu propia base de datos, y si te aparecía algún resultado, podías entrar a este, pero en esta actualización ya no te permite entrar al maga encontrado no importa cuantas veces le presiones, y pues bueno, toca ordenar y buscar el manga manualmente entre todos los que tengas.

Era solo eso, espero que puedan solucionarlo, Gracias.

**Comment by raulhaag** [comment]
Hola, ahi lo arregle para la proxima versión
