### ISSUE TITLE
Batoto is back

### ISSUE THREAD

**Issue by Fraulk** [raulhaag/MiMangaNu#528]
Possible to add it again on the server list ? And remove VatotoCom because it never worked lol
https://bato.to/

**Comment by s0hvaperuna** [comment]
that is not the original bato.to. Someone just bought the domain and started uploading their own rips.

**Comment by Fraulk** [comment]
but in the end it works well and the old chapters are present so it would be nice to add it

**Comment by s0hvaperuna** [comment]
https://www.reddit.com/r/manga/comments/82wm43/rmanga_so_i_went_to_the_batoto_doman_just_out_of/
Maybe this will explain why it's not worth it to add that site.

**Comment by Fraulk** [comment]
Ok i see thanks for the response
