### ISSUE TITLE
Unable to find titles on Kiss Manga

### ISSUE THREAD

**Issue by CuZnDragon** [raulhaag/MiMangaNu#530]
I used to have these titles on my listing but the previous update wouldn't start and I had to delete everything and start over and now unable to get these titles.

http://kissmanga.com/Manga/Potion-danomi-de-Ikinobimasu-
http://kissmanga.com/Manga/S-I-D
http://kissmanga.com/Manga/DARLING-in-the-FRANXX
http://kissmanga.com/Manga/Isekai-Yururi-Kikou---Raising-Children-While-Being-an-Adventure--Novel-
http://kissmanga.com/Manga/While-Killing-Slimes-for-300-Years--I-Became-the-MAX-Level-Unknowingly--Novel-

**Comment by CuZnDragon** [comment]
Seem to be getting more that can't be found on Kissmanga but are there through the web site.

**Comment by CuZnDragon** [comment]
Is there anyway to force a complete rescan of a site without losing everything else?

**Comment by CuZnDragon** [comment]
Guess Kissmanga is causing it to fail to get new titles with the click crap they are doing now.

**Comment by raulhaag** [comment]
@CuZnDragon about rescan if per manga no without delete actuals chapters
about the fails i not get what is the problem about that "click crap" the only manga the i don't found is s i d and its for the name

**Comment by CuZnDragon** [comment]
Not sure what the cause but it is like the database of manga available on Kissmanga is not getting updated since the first time I added Kissmanga, after reinstalling.
