### ISSUE TITLE
Can't read dwnloaded manga

### ISSUE THREAD

**Issue by plokm21** [raulhaag/MiMangaNu#531]
i just updated to 1.81 and when i tried to read a downloaded manga from kiss manga i get this error https://i.imgur.com/wB8qUay.png 
and it then crashes 
I've tried it with other manga websites and it still happens

**Comment by raulhaag** [comment]
this is already fixed for next version, it happend only on pre lollipop an not in all version

**Comment by plokm21** [comment]
Okay thanks will wait for the next release.

**Comment by raulhaag** [comment]
if all go well at the end of this weekend go to be ready
