### ISSUE TITLE
Can't read from mangahere

### ISSUE THREAD

**Issue by deify123** [raulhaag/MiMangaNu#533]
Since a few days I cannot read Manga from mangahere on my KitKat 4.4.4 tablet, it always has an "too many errors", but there's no indication which errors.
Yet it works fine on my phone which has Nougat 7.0.
I also don't get any Toasts or other messages saying what could've gone wrong :(
Both devices run 1.82 but the problem was on the tablet pre-update too (1.78, i think)

**Comment by raulhaag** [comment]
hi, from v1.78 its use https and pre lollipop (or m) don't auto update ssl system cert, for next version i added a cert for solve thi issue
