### ISSUE TITLE
Should call detector.getFocusY() in ScaleListener.onScale in ReaderContinuous

### ISSUE THREAD

**Issue by ke-kx** [raulhaag/MiMangaNu#535]
I am testing an automatic Bug detection approach and I _think_ my tool has found a bug in [ReaderContinuous.java](https://github.com/raulhaag/MiMangaNu/blob/master/app/src/main/java/ar/rulosoft/mimanganu/componentes/readers/continuos/ReaderContinuous.java).

In line 28:
` float final_y = (((((screenHeight * nScale) - screenHeight)) / nScale) - ((((screenHeight * mScaleFactor) - screenHeight)) / mScaleFactor)) * detector.getFocusX() / screenHeight;`

I believe that the invocation of `detector.getFocusX()` should be changed to `detector.getFocusY()`, purely on the grounds that the variable is called `final_y`. Would be awesome to get feedback if this is indeed a bug or if you are using `getFocusX()` twice on purpose :)

**Comment by raulhaag** [comment]
yes, it's a bug and now fixed 👍
