### ISSUE TITLE
Can't download mangas from readmanga

### ISSUE THREAD

**Issue by juh9870** [raulhaag/MiMangaNu#537]
Mangas marked as adult can't be downloaded from readmanga.me, it caused by the fact that if you try to open adult maga using url `readmanga.me/<manganame>/vol<X>/<Y>` you will get page with cofirmation that you are adult, but if you try to open it with `readmanga.me/<manganame>/vol<X>/<Y>?mature=1` then all will works fine

**Comment by juh9870** [comment]
`readmanga.me/<manganame>/vol<X>/<Y>?mtr=1` also works fine

**Comment by raulhaag** [comment]
added also fix navigation on server list

**Comment by juh9870** [comment]
Yeah, it works
