### ISSUE TITLE
Broken connection to KissManga

### ISSUE THREAD

**Issue by Yuu1305** [raulhaag/MiMangaNu#538]
Hello there,
it seems like that the app cant establish a proper connection to kissmanga anymore. It can't open up mangalist, update manga, download chapter or covers. Doesnt work on my Samsung S8 (Android 8.0) or my brothers OP5T(Android 8.0). We are using version 1.81 of this app. Same occurs on 1.80. Maybe kissmanga changed sth on their end?

**Comment by raulhaag** [comment]
its a problem with cloudflare already fixed for next version, also added notification for android oreo if you use the github version it useful for updates, when i fix a error on reader i go to publish a new release "1.83"

**Comment by Yuu1305** [comment]
Alright, thanks for the info :)
