### ISSUE TITLE
No Internet connection at all.

### ISSUE THREAD

**Issue by AxezCore** [raulhaag/MiMangaNu#539]
Phone ver. Samsung Galaxy 6s edge
Mimanga ver. 1.82
Android ver. 7.0

As headline states nothing happens when trying to update subs download new chapters or add new subs, it just hangs there, no error messages or anything, but no data transfer happening either.

So far I've tried both with WiFi and 4G with the same lack of results, I've tried uninstalling and reinstalling the app, cleared it's cache but still nothing, so I'm open to suggestions?

As best I can tell it happened after the latest Android update, but mimanga seems to be the only app affected by it.

**Comment by raulhaag** [comment]
you can try disable internet detection on the app settings

**Comment by AxezCore** [comment]
Tried that but it didn't make any difference. Probably just my phone being weird. I've found an app called tachiyomi that does the same, but it'll be a pain to transfer my library to it though.

**Comment by AxezCore** [comment]
Update: it now works again after the 1.83 update, no idea what caused it to suddenly not work.
