### ISSUE TITLE
Can't update to 1.83 on Android 4.0.4

### ISSUE THREAD

**Issue by Setsua** [raulhaag/MiMangaNu#540]
I tried to update to 1.83 on my eReader but it says "Failure [INSTALL_FAILED_OLDER_SDK]".

**Comment by raulhaag** [comment]
that is for a library (at the end not used) that need 16 as min sdk, i go to publish a replace of the release whit the support for this version in 5 minutes, if you have a github version you can update from the app, if you have the fdroid version you need to wait to a new release

**Comment by Setsua** [comment]
Thanks, it's working again. 👍
