### ISSUE TITLE
Add mintmanga.com

### ISSUE THREAD

**Issue by juh9870** [raulhaag/MiMangaNu#545]
Russian site http://mintmanga.com contains mangas that can't be found on other russian sites. Their api and construction is same as readmanga.me so adding them is just copy+paste readmanga class with changing site adress.

**Comment by tempura-san** [comment]
Had some time at hand - happened to be a bit more than that but not too complicated either :smile:
As I am not familiar with Russian I could not test deeply, but the filtering seems to be plausible - from what the returned list shows.

**Comment by tempura-san** [comment]
@juh9870 The server is available since version 1.85 - does it work properly for you? If so, could you please close this issue? Thanks!

**Comment by juh9870** [comment]
Sorry, completly forgot about it.
