### ISSUE TITLE
error con el servidor de TMO

### ISSUE THREAD

**Issue by xken2x** [raulhaag/MiMangaNu#550]
Debido a una actualizacion de la pagina, la pagina de tumangaonline.com ha sido cambiada a tumangaonline.me, y supongo que debido al cambio en como se manejaban las bases de datos dentro de la propia web, se ha roto la compatibilidad con la app, reporto esto, como aviso, y que en el momento que puedas, ¿podrias implementar la compatibilidad con la nueva pagina de tumangaonline?

**Comment by raulhaag** [comment]
En unos días cuando vuelva a casa lo arreglo
