### ISSUE TITLE
ReadComicOnline doesn't work anymore

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#555]
ReadComicOnline is broken right now, you can't scroll through the comic list. I'm getting a error telling me that it failed to connect to the website, when trying to load the list.

**Comment by tempura-san** [comment]
I'm getting a `connect timed out` when trying to list ReadComicOnline. Accessing the page in a desktop browser stays unusually long at the CloudFlare protection which seems to loop for some time (and thus sends the URL interceptors of MiMangaNu in circles IMHO) - maybe it is just a temporary issue?
