### ISSUE TITLE
Can't read last page of chapter in mangas loaded from local storage

### ISSUE THREAD

**Issue by juh9870** [raulhaag/MiMangaNu#556]
In mangas that i loads from local storage i can't read last page of most chapters, pages counter says like 29/30 but when i try to read next page it just shows next chapter. Page scroller also can't reach last page.

**Comment by tempura-san** [comment]
Thanks for reporting - fix added to PR #551.

**Comment by juh9870** [comment]
Should i close issue or wait untill PR merged?

**Comment by tempura-san** [comment]
Please wait until it is merged and confirmed to be working. Just to have some kind of review. 😅
