### ISSUE TITLE
The app closes when you have to upload a large or long image, Problem with Notification.

### ISSUE THREAD

**Issue by ElUserCh** [raulhaag/MiMangaNu#560]
Hello, the app closes when you have to upload a large or long image (it occurs in many manhwas or webcomics where the images are very long eg ReLife), this happened to me in many other sleeve readers. Also the notification of looking for new chapters appears 2 times when I turn on the device and it can not be closed. Sorry for the english I'm using the google translator

**Comment by raulhaag** [comment]
You can try to use the continuous reader that manages the images by segment to free the memory, don't forget to configure on vertical, and in config change max texture size to the minimun.
Sorry if i'm late please make a feedback
