### ISSUE TITLE
KissManga Download Error

### ISSUE THREAD

**Issue by Yuu1305** [raulhaag/MiMangaNu#561]
Since this morning KissManga displays an error when trying to download manga. Is a general problem it seems, not a specific manga. Website works fine, idk if there have been some changes to KissManga' site...

**Comment by jtwpayn** [comment]
Also with me. Able to see new manga unable to download any.

**Comment by raulhaag** [comment]
hi this is anti bot from kissmanga you need to enter from browser whit your ip to any chapter like http://kissmanga.com/Manga/Fairy-Tail/Chapter-545?id=375029 and complete the captcha and the app go to work

**Comment by Yuu1305** [comment]
That worked, yes. But only if you access the site with a computer. On phone i had seen the cloudflare-check-your-browser-thingy but that did not help for the manga app. 
But, now I know what to do; cheers mate :)
