### ISSUE TITLE
Tu Manga Online

### ISSUE THREAD

**Issue by cawaren** [raulhaag/MiMangaNu#564]
Hola.

Se que talvez no sea culpa de la aplicacion, sino de los cambios en el servidor hace un tiempo, pero hay varios mangas, que al agregarlos no tinene ningun capitulo, aunque en la pagina si esten, talvez para ver si se podia arreglar esto que ha causado molestias desde la actualizacion del servidor y la app.

Gracias.

**Comment by raulhaag** [comment]
ejemplo serian utiles en este caso

**Comment by cawaren** [comment]
Sucede mas que todo con muchos one-shots, como Kimi Hayate, Ilya, La historia de los héroes que regresan a casa..., y tambien otros que ya estaban agregados antes de la actualizacion, que si funcionaban como Love Live: Yuri Idol.

**Comment by raulhaag** [comment]
ahi arregle los de los one shot o mas bien de no chapter list para la próxima versión
