### ISSUE TITLE
[Request] Add Indonesian Source

### ISSUE THREAD

**Issue by sekedus** [raulhaag/MiMangaNu#565]
Hello, Please add Indonesian sources.

source list:
- http://mangaku.in/daftar-komik-bahasa-indonesia/
- https://neumanga.tv/manga
- https://www.pecintakomik.com/daftar-manga/?list
- http://mangaindo.web.id/manga-list-v052/
- http://www.mangacanblog.com/daftar-komik-manga-bahasa-indonesia.html
- https://komikcast.com/list/
- https://westmanga.info/manga-list/
- https://mangashiro.net/daftar-manga/?list

Thank you

**Comment by raulhaag** [comment]
Hi @sekedus  im go to add a source for indo, if you can translate the app to your language go to be usefull

**Comment by raulhaag** [comment]
added neumanga.tv to v 1.87

**Comment by sekedus** [comment]
I will try, but it might take a long time because I'm a little busy.

how can i help translation?

**Comment by raulhaag** [comment]
the easy way is translate this and upload 
https://github.com/raulhaag/MiMangaNu/blob/master/app/src/main/res/values/strings.xml
other more complicated is download the Android studio, clone the project and open res/values/strings.xml then click on open editor (right up a the editor), then click on the icon of a world with a plus sign and select your langauge, then  you can use the editor to assist you on the tranlate, after that you can make a pull request with your language on it

**Comment by sekedus** [comment]
Well, I'll do my best.
