### ISSUE TITLE
Changing download directory nuked database

### ISSUE THREAD

**Issue by GamaXplorer** [raulhaag/MiMangaNu#566]
While trying to change the download directory and having copied the files, none of my subscribed items apeared in the database.
Switching back to the default directory and copying the database back to it didnt prove any results.

I fear this might have been a mistake on my part, of maybe not copying the database files before changing directory, but my memory leaves me uncertain if this is indeed the case.

Is this a common error or a misshap on my part, and, most of all, is there a fix to this?

**Comment by raulhaag** [comment]
check if a mimanganu subdirectory is created on desire new location, all the data need to be on this subdirectory on its respective subdirectories, like /dbs
on dbs if you have the app since long time database backup can be there to restore something.

**Comment by GamaXplorer** [comment]
@raulhaag

>check if a mimanganu subdirectory is created on desire new location

It seems that's what the problem was.
I belived the directory folder to be ~/mimanganu and not the directory where the folder was located. I'm now able to access the old database without problem.

But i am still unable to change directory to where i intended.
Is MiMangaNu unable to read/write to the external sd?

Thank you for your cooperation.

**Comment by raulhaag** [comment]
check this https://github.com/raulhaag/MiMangaNu/issues/494
