### ISSUE TITLE
Can't update the Japscan server

### ISSUE THREAD

**Issue by Fraulk** [raulhaag/MiMangaNu#567]
After the update all the old chapters are now readable but updates are still not done, so its impossible to read the most recent chapters. I already cleared cache and cookies, deleted and added again the server

**Comment by raulhaag** [comment]
fixed for version 1.89

**Comment by romifly794** [comment]
Me too, but in my said error in every chapter! And when I want update said error for read data base, I don't understand what happen because in update 1,86 this work very well . Is my phone? Or something I do wrong?

**Comment by raulhaag** [comment]
@romifly794  perhaps, out of space?
