### ISSUE TITLE
Add 'fdroid' flavour without GMS

### ISSUE THREAD

**Issue by licaon-kter** [raulhaag/MiMangaNu#569]
Looking at https://github.com/raulhaag/MiMangaNu/commit/17c7edfc9a5e362584a8e3698244cd29655a81f1 you've added these libs for some SSL/CA stuff?

This [breaks](https://f-droid.org/wiki/page/ar.rulosoft.mimanganu/lastbuild) the F-Droid builds as GMS are not open-source libs.

Could you separate them with a flavour?

If the SSL/CA stuff is needed and was fixed in a newer Android version maybe we can raise `minSdkVersion` for this flavour only?

**Comment by raulhaag** [comment]
really don't know how, different branch, or gradle config that let me change dependence and add a dummy gpservices,

**Comment by licaon-kter** [comment]
Yes, something.

Again, what's the need exactly?

**Comment by raulhaag** [comment]
now i crated a branch caled flavors, you know whit the normal github and fdroid flavors, i can merge this on the master but first i need to know if there is a way to inform on fdroid to the system compile this flavor

**Comment by licaon-kter** [comment]
We'll modify the metadata accordingly, from `gradle=yes` to `gradle=fdroid` 👍

**Comment by raulhaag** [comment]
ok then i merge this to master

**Comment by raulhaag** [comment]
@licaon-kter so nothing more needed from miy side?

**Comment by licaon-kter** [comment]
Nope, already updated here: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/ar.rulosoft.mimanganu.txt and builds ok

Thanks

**Comment by raulhaag** [comment]
Thank to you 👋
