### ISSUE TITLE
Tu manga online (otra vez :b)

### ISSUE THREAD

**Issue by L-felix** [raulhaag/MiMangaNu#570]
Ya había pasado en anteriores updates, creo que es por cambio de servidores, en fin. Recibo error casi al instante cuando descargo un nuevo capitulo de casi todos los mangas que tengo agregado en tu manga online(si es que no todos no me he tomado la paciencia de intentarlos todos ya que es el principal que uso)

**Comment by raulhaag** [comment]
mira el issue #568 para ver el progreso
