### ISSUE TITLE
Sugerencias y reportes

### ISSUE THREAD

**Issue by marrokin** [raulhaag/MiMangaNu#571]
Seria muy util para los usuarios poder hacer sugerencias y reportar errores desde la misma aplicacion para evitar salir de ella

**Comment by raulhaag** [comment]
A primera vista seria util pero seguro representaria un bombardeo para un desarrollador con poco tiempo y dificil de filtrar, tanto asi que la cuota de acra en tracepot me dura unos dias (aunque mayormente por los clones desactualizados), ademas necesitaria poner un server para manejar las solicitudes o un correo todo eso no mejoraria y a la larga ni lo chequearia.
