### ISSUE TITLE
Problema con Leomanga

### ISSUE THREAD

**Issue by Nathancr87** [raulhaag/MiMangaNu#572]
Buenas noches. ¿Qué ocurre con el servidor Leomanga? No me aparecen las imágenes de los mangas, ni me permite buscar nuevos como tampoco descargar capítulos, ni tampoco me aparece en el buscador de Google. ¿Lo han capado? ¿Sabéis que ha pasado?

**Comment by raulhaag** [comment]
parece estar caido no se si sera momentaneo o permanente, o si se les vencio el host ya que estamos a primeros dias de mes

**Comment by edgarMejia** [comment]
Hace unos días se había caído también, pero aparecía en google... Hoy ni eso.

**Comment by rs3mk** [comment]
lo mas raro es que borro su facebook

**Comment by Nathancr87** [comment]
Tal vez haya capado del todo. Que es lo que me temo...

**Comment by celciusb** [comment]
Al parecer les borraron el dominio desde raíz, osea su empresa de registrado. Seguramente fue por denuncias... ya me paso con esa empresa. Así que... RIP Leomanga hasta mediados del año que viene (o más)

**Comment by rs3mk** [comment]
Una empresa muy buena para registrar dominios es https://njal.la de los creadores del sitio de torrent publico TPB. 

leomanga.com esta registrado en godaddy y parece estar activo:

Domain Name: leomanga.com 
Registry Domain ID: 1933778880_DOMAIN_COM-VRSN 
Registrar WHOIS Server: whois.godaddy.com 
Registrar URL: http://www.godaddy.com 
Updated Date: 2018-05-29T23:30:11Z 
Creation Date: 2015-05-29T19:28:13Z 
Registrar Registration Expiration Date: 2019-05-29T19:28:13Z 
Registrar: GoDaddy.com, LLC 
Registrar IANA ID: 146 
Registrar Abuse Contact Email: abuse@godaddy.com 
Registrar Abuse Contact Phone: +1.4806242505 
Domain Status: clientTransferProhibited http://www.icann.org/epp#clientTransferProhibited 
Domain Status: clientUpdateProhibited http://www.icann.org/epp#clientUpdateProhibited 
Domain Status: clientRenewProhibited http://www.icann.org/epp#clientRenewProhibited 
Domain Status: clientDeleteProhibited http://www.icann.org/epp#clientDeleteProhibited 
Registry Registrant ID: Not Available From Registry 
Registrant Name: Hugo Berreta Sosa 
Registrant Organization: LeoManga 
Registrant Street: Vilarderbo 
Registrant City: Montevideo 
Registrant State/Province: 
Registrant Postal Code: 11800 
Registrant Country: UY 
Registrant Phone: +598.26016660 
Registrant Phone Ext: 
Registrant Fax: +598.26016660 
Registrant Fax Ext: 
Registrant Email: leomangaweb@gmail.com 
Registry Admin ID: Not Available From Registry 
Admin Name: Hugo Berreta Sosa 
Admin Organization: LeoManga 
Admin Street: Vilarderbo 
Admin City: Montevideo 
Admin State/Province: 
Admin Postal Code: 11800 
Admin Country: UY 
Admin Phone: +598.26016660 
Admin Phone Ext: 
Admin Fax: +598.26016660 
Admin Fax Ext: 
Admin Email: leomangaweb@gmail.com 
Registry Tech ID: Not Available From Registry 
Tech Name: Hugo Berreta Sosa 
Tech Organization: LeoManga 
Tech Street: Vilarderbo 
Tech City: Montevideo 
Tech State/Province: 
Tech Postal Code: 11800 
Tech Country: UY 
Tech Phone: +598.26016660 
Tech Phone Ext: 
Tech Fax: +598.26016660 
Tech Fax Ext: 
Tech Email: leomangaweb@gmail.com 
Name Server: LADY.NS.CLOUDFLARE.COM 
Name Server: RICK.NS.CLOUDFLARE.COM 
DNSSEC: unsigned 
URL of the ICANN WHOIS Data Problem Reporting System: http://wdprs.internic.net/ 
>>> Last update of WHOIS database: 2018-09-08T21:00:00Z <<<

**Comment by raulhaag** [comment]
nada que hacer desde mi parte, removido provicionalmente, reabrir si es necesarios
