### ISSUE TITLE
Hide "Find App updates" when installed from stores

### ISSUE THREAD

**Issue by licaon-kter** [raulhaag/MiMangaNu#573]
Eg `packageManager.getInstallerPackageName(packageName)` would get you what app installed your APK, and when the result is `org.fdroid.fdroid` or `com.android.vending` or `com.github.yeriomin.yalpstore` or `com.dragons.aurora` you should not bother looking for updates as those apps take care of that.

**Comment by raulhaag** [comment]
Ok better than look for fdroid sub fix or flavor, I will change it.

**Comment by licaon-kter** [comment]
F-Droid can't handle suffix (unless you also tag with suffix IIRC), hence it gets removed on build: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/ar.rulosoft.mimanganu.txt#L634

**Comment by raulhaag** [comment]
there is it, i will see if it works on next update
