### ISSUE TITLE
Impossible to reaf cbr cbz files

### ISSUE THREAD

**Issue by B4rabbas** [raulhaag/MiMangaNu#575]
Hello, when I choose from folder I can't open my cbr/cbz files. Please fix it.
Thanks.

**Comment by raulhaag** [comment]
this kind of files are not supported, only support uncompresed images on their owns folthers for chapter

**Comment by B4rabbas** [comment]
Could you implement cbr/cbz to your app ?

**Comment by raulhaag** [comment]
cbz could be, but too many changes are needed

**Comment by B4rabbas** [comment]
You could replace perfect viewer if you implemant theses ones. Could be perfect
