### ISSUE TITLE
Kissmanga error.

### ISSUE THREAD

**Issue by jtwpayn** [raulhaag/MiMangaNu#576]
Hello,
I'm unable to download any manga from kissmanga anymore. Attempted to update the cookie for catpcha it didn't work.
Thanks for this great program.
Regards

**Comment by raulhaag** [comment]
Fast fix not app sida, you can add this line to host file on your pc 
87.121.98.205 kissmanga.com
then enter to the site from navigator and then enter on a chapter, after that resolve the captcha

**Comment by raulhaag** [comment]
PD: after next update you go to need to remove this line.

**Comment by jtwpayn** [comment]
Started working again thanks.

**Comment by raulhaag** [comment]
just leave thi open just in case anyone is searching for the same, i will close it before next update
