### ISSUE TITLE
Error al Cargar datos desde Readmanga

### ISSUE THREAD

**Issue by xmithosx** [raulhaag/MiMangaNu#578]
Que tal, primero que nada y como de costumbre muchas gracias por el trabajo...

Desde hace unos días la app esta presentando lentitud extrema, no se si es el indice o el api de conexión (asumiendo que exista uno) el hecho es que tanto para buscar actualizaciones de manga, como para descargar capítulos, esta Extremadamente lento al punto de no terminar...

**Comment by raulhaag** [comment]
Hola ReadMangaToday está usando en este momento cloudflare después de 30 min o 1 hora pide el recrear las cookies de cf este tarda al menos 5 seg más lo que la consulta normal.
