### ISSUE TITLE
Update download status when redownloading

### ISSUE THREAD

**Issue by Nodd** [raulhaag/MiMangaNu#58]
If there saw an error downloading a chapter, it is marked as such in the download tab. However if I redownload the chapter afterwards and it works, it is still marked as an error.
You can test it by disconnecting the wifi while downloading for example.

I think that I don't have the last version (not uploaded yet on Fdroid yesterday) so it may have been corrected since.

**Comment by raulhaag** [comment]
cheked. i go to how to fix it.

**Comment by raulhaag** [comment]
fixed on next version
