### ISSUE TITLE
Add New Site and Fix NeuMangaTV

### ISSUE THREAD

**Issue by BambooKids** [raulhaag/MiMangaNu#580]
Please add a new Indonesian server: https://mangashiro.net and https://komikcast.com
and please repair the NeuMangaTV server that cannot display the entire chapter.
Thanks

**Comment by raulhaag** [comment]
neuManga its working (like it servers) if in some mangas its don't display the entire chapter please post a example to test (because i test with a random manga and i lost the time)

**Comment by BambooKids** [comment]
![screenshot_2018-10-04-22-39-36](https://user-images.githubusercontent.com/20338201/46485799-9fcb1880-c826-11e8-911b-9740b927e012.png)
Chapter Not Found

**Comment by BambooKids** [comment]
Oops my mistake, i forget to press "+" at corner bottom right. And now please add a new Indonesian server: https://mangashiro.net and https://komikcast.com...
Thanks
