### ISSUE TITLE
Error al descargar de TMO

### ISSUE THREAD

**Issue by AyumuMiyazaki** [raulhaag/MiMangaNu#582]
Hola! Instalé la nueva versión pero da errores de descarga para tmo, incluso me muestra notificaciones de error al actualizar la base de datos de ese servidor! Cada vez que reinstalo, detengo la aplicación (supongo que a eso te refieres con "matar", forzar la detención) pero el problema persiste. Sería bueno una opción para realizar una nueva actualización de la base de datos, si es posible! Gracias!

**Comment by raulhaag** [comment]
@AyumuMiyazaki cual version de tenes (github / android) que sistema, desde que version actualizaste, si podes agregar nuevos sin problemas y provarlos

**Comment by AyumuMiyazaki** [comment]
Hola! Uso una kindle tablet con un SO basado en KitKat, la app me estaba funcionando y siempre actualizaba allí, la última versión que tuve antes de la 1.90 fue la 1.87 y lo actualicé porque estaba presentando el problema con tmo! Puedo agregar apks sin problemas!

**Comment by AyumuMiyazaki** [comment]
Mira, aquí te paso una imagen donde aparece la notificación de actualización de la base de datos finalizada junto con la notificación del SO del error de la actualización!
![screenshot_2018-10-11-10-09-03_kindlephoto-1129099](https://user-images.githubusercontent.com/13038856/46810390-94a04d00-cd3e-11e8-9f13-db26e0cabf0d.png)

**Comment by AyumuMiyazaki** [comment]
Hola! Te actualizo! Luego de instalar la versión de pastebin y que tampoco me sirviera, decidí realizar una instalación limpia, así que borré toda la carpeta de la app y procedí a instalar con la que tienes para descarga aquí en github, agregué de nuevo algún manga de lo que tenía por tmo y ahora sí sirvió y cargó, probé con otro y también, quizá de mi lado había algún archivo corrupto en la carpeta! 
Igual gracias por responder! :D

**Comment by edgarMejia** [comment]
Yo tengo un error al descargar y es que en series largas, la descarga siempre da error en el capitulo 30 aproximadamente, el server responde con un error 400.

**Comment by edgarMejia** [comment]
He probado con Boku no Hero Academia y One Punch-Man.

**Comment by raulhaag** [comment]
@edgarMejia lo tuyo es que llegaste al limite del anti leech tenes que esperar un rato y poner reintentar en el download manager o tratar de bajar no tan masivamente
