### ISSUE TITLE
How to add new manga server

### ISSUE THREAD

**Issue by joielechong** [raulhaag/MiMangaNu#584]
Is there any documentation for adding new manga server to MiMangaNu. I'm trying to adding a new server but didn't know how to start.

Thank you.

**Comment by raulhaag** [comment]
hi just extend this class (https://github.com/raulhaag/MiMangaNu/blob/master/app/src/main/java/ar/rulosoft/mimanganu/servers/ServerBase.java) and read on it there is a how to in it, made by one contributor (sorry to him don't remember exaticaly who) not me but usefull, also i just added en new indo server for next version "mangashiro.net".

**Comment by raulhaag** [comment]
@joielechong  also you can be helpfull for you if read similar server implementation on the same folther

**Comment by joielechong** [comment]
Thank you @raulhaag and @tempura-san  :+1: :+1: :+1:

**Comment by tempura-san** [comment]
@joielechong You are welcome - I hope it helps. :sweat_smile:
If you run into troubles or need clarifications, please let me know.
I would also suggest to add and test the new implementation using the automated Robolectric test suite. Check other servers and add your new one in https://github.com/raulhaag/MiMangaNu/blob/master/app/src/test/java/ar/rulosoft/mimanganu/TestServers.java.

Godspeed! :+1:
