### ISSUE TITLE
Unexpected URL en TMO

### ISSUE THREAD

**Issue by Fliqpy** [raulhaag/MiMangaNu#587]
Al querer abrir descargar un caso de manga aparece eso y no se puede entrar al servidor. Muchas gracias por todo su trabajo.

**Comment by raulhaag** [comment]
cambiaron la pagina a tmofans.com un fix estara disponible en la proxima version

**Comment by kiandas74** [comment]
quisiera saber cuando estara disponible la nueva version con el fix de tmo, muchas gracias por todo el esfuerzo.

**Comment by romifly794** [comment]
Lo esperamos con pronto!!!! Muchas gracias!!!

**Comment by Nathancr87** [comment]
Buenas. Se sabe algo de cuando saldrá la nueva versión con el fix de TMO? Muchas gracias por todo el trabajo que hacéis.

**Comment by Andrelumier** [comment]
Llevo tiempo usando tu app, gracias por crearla, la amo...

**Comment by raulhaag** [comment]
Ahi subi la actualizacion saludos 👋
