### ISSUE TITLE
bloqueo de la actualizacion y descarga de manga en distintos servidores

### ISSUE THREAD

**Issue by kallius** [raulhaag/MiMangaNu#589]
Hola, excelente proyecto lo sigo hace bastante tiempo y no he tenido mayores dificultades hasta la última actualización que me entrego F-droid, actualmente estoy con la versión 1.91 y desde que se actualizo a esta parte me percate que no estaba actualizando, pensé que podría ser un problema de servidor pero al tratar de revisar en uno distinto me sale "CLEARTEXT communication to (servidor de mangas) not permitted by network security policy", claro es un bloqueo de seguridad pero se a estado generando a la mayoría de los sitios en español, no a si en algunos otros de otras procedencias.. por si pudieras revisar.
Por otra parte gracias por tu gran trabajo ;)

**Comment by raulhaag** [comment]
@kallius necesitaría mas información del sistema, cleartext es un problema de ciphers, y es relacionado con tu versión del sistema, ademas de eso te aconsejaría probar la versión de github si es que tienes google play services que se encarga de obtener e instalar certificados para los distintos sitios ya que en fdroid esta capada esta opción

**Comment by raulhaag** [comment]
@romifly794 Romina lo tuyo es distinto y proviene del hecho de que tmo pone limite a las peticiones por tiempo y si tenes muchos en ese servidor vas a notar que en cierto punto se queda parada la actulización, pero en realidad solo esta esperando que el tiempo necesario pase.

**Comment by raulhaag** [comment]
@kallius version del sistema mas que nada y queria saber si la v1.90 te funcionaba bien

**Comment by kallius** [comment]
@raulhaag ok, en todo caso estaba en el documento pero es versión 9 de android "pie" y la v1.91 me funcionaba bien pero actualice a la v1.92, aunque el bloqueo de ciphers continua activo.

**Comment by raulhaag** [comment]
prodes probar este a ver si no tenes problemas 
https://www.mediafire.com/file/dk7v94cq1e6yumo/app-github-release.apk/file

**Comment by raulhaag** [comment]
[app-github-release.zip](https://github.com/raulhaag/MiMangaNu/files/2593394/app-github-release.zip)
@kallius  proba este y decime si te funciona

**Comment by kallius** [comment]
@raulhaag listo instale y actualice la lista.. y funciono todo ok, se actualizaron todos los mangas pendientes en los servidores con bloqueo, ademas ingrese a los otros servidores identifique con el mismo bloqueo he ingresaron sin dificultad... gracias por tu trabajo ;)

**Comment by raulhaag** [comment]
ok el fix estara en la proxima version para los usuarios de android pie :wave:

**Comment by kallius** [comment]
@raulhaag hola de nuevo mira me acabo de dar cuenta que al momento de efectuar la descarga de los capítulos hace error 
![screenshot_20181119-002507](https://user-images.githubusercontent.com/45053665/48684991-9efa0600-eb8a-11e8-916e-be987ab0504b.png), para que le des una mirada que tal vez es por el mismo motivo

**Comment by raulhaag** [comment]
[app-github-release.zip](https://github.com/raulhaag/MiMangaNu/files/2595258/app-github-release.zip)
proba esta version que corrige una cosa de ninemanga y heavenmanga
