### ISSUE TITLE
App crash when cancelling a download

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#59]
Happens only when the chapter is downloading, not when the chapter is downloaded.

**Comment by raulhaag** [comment]
missitraslation problem = (

**Comment by Dostoi** [comment]
"missitraslation " ?

**Comment by raulhaag** [comment]
missing traslation of a massage

**Comment by Dostoi** [comment]
Ho ok :)

**Comment by Dostoi** [comment]
Good too
