### ISSUE TITLE
Problema con el servidor mangafox

### ISSUE THREAD

**Issue by Fliqpy** [raulhaag/MiMangaNu#590]
Hola, muchas gracias por tu arduo trabajo, tengo problemas con este servidor, no carga la informacion al querer accesar, es el unico que tiene este problema, ademas de que que al salir cuando esta esperando respuesta, bloque a el acceso de los demas servidores e inclusive la descarga de mangas.

**Comment by raulhaag** [comment]
Hola seria util si pudieras compartir tu db porque como cambio a fanfox hay varios cambios en la página no se si va a ser directo la actualizacion del server

**Comment by Fliqpy** [comment]
Oh ya veo, eses el problema, a que te refieres db?

**Comment by raulhaag** [comment]
base de datos esta en la la carpeta que crea mimanganu

**Comment by Fliqpy** [comment]
[mangas.zip](https://github.com/raulhaag/MiMangaNu/files/2612596/mangas.zip)
es este no?

**Comment by raulhaag** [comment]
si esa misma ahora veo que puedo hacer

**Comment by raulhaag** [comment]
mmm solo tenes mangas de TMO no mangafox?

**Comment by Fliqpy** [comment]
Lo que pasa es que perdí el celular con la base datos anterior, así que estoy agregando de nuevo los mangas que tenia antes a un nuevo celular, pero no puedo agregar de mangafox por ese problema
