### ISSUE TITLE
Japscan has changed domain name again

### ISSUE THREAD

**Issue by Fraulk** [raulhaag/MiMangaNu#591]
japscan.cc  to  http://www.japscan.to/

**Comment by raulhaag** [comment]
hi also all the site has changed i go to try to get it for next version if you can share your database to ensure about the paths are the same

**Comment by Fraulk** [comment]
[mangas.db.24.bak.txt](https://github.com/raulhaag/MiMangaNu/files/2703656/mangas.db.24.bak.txt)
ok, thanks for the response

**Comment by raulhaag** [comment]
this weekend  a new version with the changes go to be published, thank to the db the already added mangas (at least all i try are compatible)
