### ISSUE TITLE
software navigation keys are hidden

### ISSUE THREAD

**Issue by Peridon** [raulhaag/MiMangaNu#594]
I changed phone to new one (huawei smart p 2019, android 9 pie) and it only has software navigation keys. These are hidden when reading probably due to fullscreen mode, so i can't quickly use them. There is option to show titlebar in read mode, can other one be added to always show navigation keys.

**Comment by raulhaag** [comment]
on setting you can set Hide actionbar and hide sensitive scroll... you get something like this out of full screen
![screenshot_1545651227](https://user-images.githubusercontent.com/2048339/50398483-b2365d80-0756-11e9-9f57-b325f8b8e79e.png)
or if you want on full screen you can show statubar also on settings
![screenshot_1545651234](https://user-images.githubusercontent.com/2048339/50398507-e27dfc00-0756-11e9-9bc0-2ec9a497c68d.png)

**Comment by Peridon** [comment]
Thanks for the quick reply and merry christmas. i mean these buttons in the image specifically

https://m.imgur.com/gallery/lT5tL6d

**Comment by raulhaag** [comment]
that is hide sensitive scrollbar on setting

**Comment by Peridon** [comment]
no, i mean the android back, home and tasklist buttons.

**Comment by raulhaag** [comment]
if you see the first image you can set up for readein out of full screen sowing navigation icon on bottom and only add the progress

**Comment by Peridon** [comment]
It is a problem since progress bar takes reading space and causes unintentional jumping of pages if reading one handed. However I found a workaround for this, setting android system navigation to gestures instead of navigation buttons. The downside is that drawers in apps only work in the top 1/3 of screen and below it is back gesture.
