### ISSUE TITLE
Error "Error" when attempting to open PDF from local storage

### ISSUE THREAD

**Issue by Matthew-Maclean** [raulhaag/MiMangaNu#595]
When trying to open a pdf from local storage, I get an error with the text simply "Error". A couple things come to mind:

- Does this app support PDF? If it does not then maybe the error should be "This app does not support PDF" or something to that effect.

- The PDF is large (~80mb), that may be too large for this app, then the error message should be "PDF too large", or similar.

- Maybe it's just an error, in which case it should probably be fixed.

the PDF I am trying to open is valid and can be opened and viewed on other apps on the same phone.

Thanks.

**Comment by raulhaag** [comment]
pdf are not supported from the app only images on folthers
