### ISSUE TITLE
Weird page order when pages are not named with just numbers

### ISSUE THREAD

**Issue by Matthew-Maclean** [raulhaag/MiMangaNu#597]
I don't know how this app orders it's pages, but it seems that if the names are not simple numbers (eg. "1.jpg"), then the order can get messed up in a seemingly random way, even when other apps can still properly order the pages alphabetically. For example, I made a simple test manga with two chapters:

[Chapter 1](https://i.imgur.com/IwhHQkm.jpg)

[Chapter 2](https://i.imgur.com/cGu5pv2.jpg)

As you can see, my file manager can properly order these pages so that they are "1", "2", "3", even when the names are in the common "Volume x page y" format, rather than the simple number format. But when I import these into the app, this is what I get

[Chapter 1, page 1](https://i.imgur.com/pIucJJw.jpg)

It's page 3!

[Chapter 2, page 1](https://i.imgur.com/TT56eji.jpg)

This is ordered correctly.

**Comment by raulhaag** [comment]
the best way to order is on a directory structure
/manga or comic name/chapter name(number)/numerate  images
sorry but not only get the same way that app order the download data

**Comment by Matthew-Maclean** [comment]
Ah too bad, thanks for the info though
