### ISSUE TITLE
Strange things in the option of selected chapter

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#60]
When selecting a chapter by long pressing it and going to the option menu I have strange things

![screenshot_2015-04-04-14-27-33](https://cloud.githubusercontent.com/assets/7694864/6992579/f3006dca-dad6-11e4-98f0-3d4be0425ba7.png)

**Comment by raulhaag** [comment]
missing traslation :-P

**Comment by Dostoi** [comment]
Ok ^^

**Comment by Dostoi** [comment]
So what are these options supposed to be ?

**Comment by raulhaag** [comment]
select all, select none, marc as readed, delete images , reset chapter delete chapter

**Comment by Dostoi** [comment]
Ok thanks

**Comment by Dostoi** [comment]
The delete images is only for selected item ?

**Comment by raulhaag** [comment]
yes all options are for selected items

**Comment by raulhaag** [comment]
cant you translate this to fr
´´xml   
<string name="borrar_imagenes">Delete images to free space</string>
    <string name="seleccionar_todo">Select all</string>
    <string name="quitar_seleccion">Select none</string>
    <string name="quitar_descarga">Can\' remobe active download</string>

**Comment by Dostoi** [comment]
<string name="borrar_imagenes">Supprimer les images pour libérer de l'espace</string>
    <string name="seleccionar_todo">Tout sélectionner</string>
    <string name="quitar_seleccion">Ne rien sélectionner</string>
    <string name="quitar_descarga">Impossible de supprimer le téléchargement en cours</string>

**Comment by Dostoi** [comment]
Don't hesitate to ask me to check the translation of new things before updating the app if you need ;)

**Comment by Dostoi** [comment]
I'm still having the same issue for the first phrase

**Comment by Dostoi** [comment]
It's good now :)
