### ISSUE TITLE
Slow updating in newer versions

### ISSUE THREAD

**Issue by MtnDewritos** [raulhaag/MiMangaNu#602]
Since 1.91, updating manga from kissmanga seems to not be threaded properly, I did some tests since I had noticed slowness in updates since that version and similar speeds regardless of amount of update threads. Since I've been using kissmanga almost exclusively for a long time now I've had these problems since 1.91.
I decided to do an apples to apples comparison between a few versions on my old phone, with 64 manga mostly from mangahere and some from kissmanga.

version: time taken
1.90: 25s
1.91: 65s
1.92: 45s
1.95: 35s.

From my testing I got a bit surprised because it didn't mirror my experience with my tablet that I use for reading normally, however I did notice something interesting: some manga took a lot longer than others. So I decided to lump everything from kissmanga at the top and it was way slower at the start compared to once it got to the mangahere manga. Then for reference I decided to test my tablet using version 1.95, it took 80 seconds to get to manga nr 64 and on it I've used kissmanga exclusively, changing number of update threads from 4 to 8 changed nothing regarding speed (on a 10 core device). Another odd side effect I've noticed is that getting into the reader takes significantly longer while updating, at least twice as long as normal, which might be related somehow.

**Comment by raulhaag** [comment]
hi. that is true. since those version there is a part of code that lock the execution to prevent 4/8/10/n excutions o cfi(cloudflare interceptor) at time and prevent a ip block for a time, the execution of this code take from 5 to 10 seconds and is not and only to get a cookie to acces to de site, and that is how it takes almost same time, on other servers also if make request to many requests in a short time the same happends, and not to simply make balance of it, but i still searching a good place to change  that excution lock.

**Comment by raulhaag** [comment]
can you test this? this version implements a pre check for server. it still need a polish on the other sides to ovoid the multiple execution of cfi but in chapter initialitation and get list that go to be stncronysed.
[app-github-release.zip](https://github.com/raulhaag/MiMangaNu/files/2825646/app-github-release.zip)

**Comment by MtnDewritos** [comment]
Sorry for not responding in a timely manner, I don't check my github account often, only reason I checked back here was to report a new issue with kissmanga again. Since version 1.96 everything has been working as expected (up until today that is), I didn't really check the time but updating was sped up multiple times compared to before with the same 100+ manga (almost exclusively kissmanga).
