### ISSUE TITLE
Kissmanga search and filtering is broken

### ISSUE THREAD

**Issue by MtnDewritos** [raulhaag/MiMangaNu#603]
1. When doing a search on kissmanga it gets stuck loading forever and going back and then selecting a manga from the default list also leads to infinite loading until the app is restarted after trying to search. 

2. Trying to use any of the filters does nothing to the list of manga that's displayed, if a manga is selected after attempting to use a filter and you then going back results in a white screen, going back and then into kissmanga again returns it to normal.

**Comment by raulhaag** [comment]
fixed to next release today or tomorrow
