### ISSUE TITLE
Error de la App

### ISSUE THREAD

**Issue by SoldadoZT** [raulhaag/MiMangaNu#605]
Acabo de actualizar a la version 1.96 pero algo pasa cuando quiero ver si hay actualizaciones de mangas disponibles la App se cierra al empezar la busqueda.

**Comment by raulhaag** [comment]
un poco mas de  información como server, dispositivo, versión del sistema, etc.

**Comment by raulhaag** [comment]
Hola no te preocupes encontre el problema, esta relacionado con la version de java que use, olvide que los dispositivos mas viejos nos soportan algunas propiedades del lenguaje de los ultimos años, lo mas probable que en el transcurso del dia publique la actualizacion

**Comment by SoldadoZT** [comment]
pense que el problema era mi celular tuve que volver ala version anterior gracias por responder.

**Comment by dnmodder** [comment]
Mismo problema, en la pantalla de inicio al intentar buscar actualizaciones de todos los mangas se me cierra, si entro en un manga y busco actualizaciones ahí todo bien.

**Comment by raulhaag** [comment]
prueben la v 1.97

**Comment by dnmodder** [comment]
Funciona correctamente la v1.97
