### ISSUE TITLE
Some server not work

### ISSUE THREAD

**Issue by borrougagnou** [raulhaag/MiMangaNu#606]
Hi ! Some server in the list didn't work:

[FR] MangaKawaii --> Could not extract manga name
[EN] View Comics --> empty?!?

**Comment by raulhaag** [comment]
fixed forn next version, for sure before this long weekend finish.

**Comment by borrougagnou** [comment]
Okay, thx,
now I see Japscan not working (maybe because they have DDoS-protection)
