### ISSUE TITLE
Error on chapter initialization (0) one one-page chapters

### ISSUE THREAD

**Issue by Matthew-Maclean** [raulhaag/MiMangaNu#608]
I'm getting the error "Error on chapter initialization (0)" when attempting to download one-page chapters. The server works fine and the updates work fine, but I cannot actually download the chapters.

**Comment by raulhaag** [comment]
please server and manga to test

**Comment by Matthew-Maclean** [comment]
The server is MangaHere
The manga is "Tomo-chan wa Onnanoko!"

**Comment by raulhaag** [comment]
fixed for next version, most possible before carnaval end.
