### ISSUE TITLE
Error on chapter initialization (4)

### ISSUE THREAD

**Issue by auz-jsm** [raulhaag/MiMangaNu#610]
Some mangas' chapters can't be downloaded. Multiple mangas are affected but the affected servers are MangaHere and FanFox (since these are the only servers I'm using). 

After submitting this report, I might revert back to v1.97

**Comment by raulhaag** [comment]
Can you especify chapter and manga?

**Comment by auzajj** [comment]
Walk on Water (ch. 21 & 22)
Whale Ears (ch. 13)

These are only I've noticed.

**Comment by raulhaag** [comment]
ready

**Comment by auz-jsm** [comment]
El problema se resolvió. Gracias
