### ISSUE TITLE
Kissmanga broken again

### ISSUE THREAD

**Issue by MtnDewritos** [raulhaag/MiMangaNu#611]
Today I recommended to a friend of mine to use kissmanga because it's been working great since 1.96 and has overall good quality, he added some manga and started downloading some chapters and suddenly started getting a CAPTCHA related error, browsing kissmanga in a web browser we didn't run into any CAPTCHAs. 

Later today I tried checking on my tablet, while I didn't have any problem downloading chapters, trying to access the server resulted in an infinite loading loop and trying to update manga resulted in it seemingly being stuck in an infinite loop, but after doing something else for a few minutes I noticed that it had progressed from just a loading bar to something like nr 60, but was stuck there, also it didn't seem to find any updates even though I'm fairly certain there should be some since I last used the app (there usually are).

Note that all the old problems with kissmanga were fixed in 1.96, which is the version I used, I also tried updating to the latest version (1.99) but these new problems persisted.

One thing I have noticed is that I sometimes run into kissmangas "The site is under maintenance. Please come back later." message in one of my web browsers (but not the other ones strangely). I'm not sure if that's what it's returning now when the app tries to access the website in some scenarios but not in others for some strange reason.

**Comment by raulhaag** [comment]
If you get that message open a chapter on browser and fill the captcha. after that all go to work, also cfi is not working until next version to bypass cloudlare ddos
