### ISSUE TITLE
[Serveur broken] Japscan

### ISSUE THREAD

**Issue by Kyrela** [raulhaag/MiMangaNu#612]
Siret, but i really think that japscan is broken. I can't download chapter, and can't access to the manga list of the server. Is it local ? I hope yes.
Thanks for attention !

**Comment by raulhaag** [comment]
fixed on next version, singles changes on japsscan and cfi, check for the version 1.100 on a couple of minutes

**Comment by esmoak** [comment]
@raulhaag what does CFI stand for?

**Comment by Kyrela** [comment]
Really, really, thanks you !

**Comment by borrougagnou** [comment]
Japscan again not work

**Comment by Kyrela** [comment]
I confirm

**Comment by raulhaag** [comment]
new version fix cfi again

**Comment by raulhaag** [comment]
@esmoak cfi is CloudFlareInterceptor if a site use this ddos system them need this to get the specific cookie and acces to site
