### ISSUE TITLE
Una Pregunta

### ISSUE THREAD

**Issue by Credits125** [raulhaag/MiMangaNu#613]
¿En ésta aplicación agregan sitios para ver hentai en español? Es que tengo varios sitios para que los agreguen, no e podido encontrar ninguna aplicación, y no me gusta leer desde los sitios por que hay mucha publicidad.

**Comment by Kyrela** [comment]
I'm okay with this. I really think that add a +18 category is a good thing, starting with the famous hentai2read.com . But, they have to stay hidden while a +18 option isn't activated.

**Comment by raulhaag** [comment]
Realmente no lo tengo pensado por el momento, ni a futuro.

**Comment by Credits125** [comment]
Piénsalo a futuro 👍

**Comment by scese250** [comment]
Te recomiendo que uses EhViewer, es una galería de hentai, también tiene en español.
