### ISSUE TITLE
[Request] Add Arabic sources

### ISSUE THREAD

**Issue by yshalsager** [raulhaag/MiMangaNu#614]
Hi, is it possible to add some Arabic sources to the app?
Here are some examples (ordered by best)

- https://www.manga.ae/
- https://www.on-manga.me/
- http://www.gmanga.me/
- https://mangag.me/
- https://www.shqqaa.com/manga/

**Comment by raulhaag** [comment]
Hi i already added manga.ae and that was no easy to me knowing nothing about arab languaje, check it on server list

**Comment by yshalsager** [comment]
@raulhaag thanks, I tried it and it's working perfectly.
Please consider adding more sources if possible.
BTW, where can I translate the app into Arabic?

**Comment by raulhaag** [comment]
if you have Android studio, just clone and add new language using the translation tool, and then make a pull request.
in other case i can add a copy of english version renamed to be taken and edited throw github and after that  you can make a pull request all on github page.
