### ISSUE TITLE
bug founded in Mangafox + another strange bug with Japscan

### ISSUE THREAD

**Issue by borrougagnou** [raulhaag/MiMangaNu#617]
## Version information
MiMangaNu  `1.101-github`

## MangaFox
Mangafox posses some "Chapter" who doesn't exist...
he take all manga below the "`You May Like`" part... and try to download but fail...
eg: Chichi chichi manga (https://fanfox.net/manga/chichi_chichi/)

### bug when I decide to "clean all cookie"
All cookie, same the cookie for bypass cloudflare have been cleared, so, I can't access to JapScan again...

### bug with manga reception
in Japscan, Idk what's happen but begin to: "Prison School 39 VF" I have some bug:
**in the website**, I don't have any problem: [Prison School JapScan](https://www.japscan.to/manga/prison-school/)
**but in MiMangaNu**, I have a message (approxymately translated)
```
Prison School 39 VF: Hana la revancharde (Error)

Too many errors (Download Suspended)
this may be due to:
- Connexion error
- Server error
- Bad download, etc...
Try later

OK  | TRY AGAIN
```
I clicked on "Remove picture to free up space" but nothing change
(for information I use the same IP address, and the same mobile phone to experiment this bug, just I use web browser, and MiMangaNu)
Okay this bug continu anytime...

## Change MiMangaNu language ???
I don't found in parameters something for change the language of MiMangaNu...

**Comment by raulhaag** [comment]
about the language, its takes the system language.
about japscan, the servers time ago publish the images scrambled and transform its throwg a css code, you go to find some chapters that contains this kind of images example(https://c.japscan.to/lel/Prison-School/39/01.jpg).
about fanfox, need a other fix, next version

**Comment by borrougagnou** [comment]
I edited my first message, okay for language,

and for your link, I have "Cloudflare Access Denied" :/

**Comment by raulhaag** [comment]
image cap![imagen](https://user-images.githubusercontent.com/2048339/55234572-355dc880-520a-11e9-9ff6-4317877b44a8.png)

**Comment by borrougagnou** [comment]
![image](https://user-images.githubusercontent.com/10796546/55237327-36a2eb80-5232-11e9-9b67-05df00e1b51f.png)

I have that with my phone and my computer same if my ip are different idk why...

but yes ! the picture is weird, I think, If I remember I know somebody can recreate the full image.

--

second thing, about "clean all cookie", do you have any idea how to prevent they remove cookie for anti-ddos?
or maybe system for add our "own" cookie,
idk :/

**Comment by borrougagnou** [comment]
@raulhaag for you: https://github.com/borrougagnou/unscrambled

you can convert that into your programming language

**Comment by borrougagnou** [comment]
Japscan again down... maybe you can found another thing for japscan

**Comment by borrougagnou** [comment]
Fix CFI for next update...
japscan again down

**Comment by borrougagnou** [comment]
I edited my repo, they know exist a JAVA version:
https://github.com/borrougagnou/unscrambled

you can found the algorithm at L.90 here:
https://github.com/borrougagnou/unscrambled/blob/master/java/unscrambled/src/gui/PhotoFrame.java

I hope this time my algo is useful for you, if not, say me why please

**Comment by raulhaag** [comment]
about japscan i go to make new cfi fix today, about the images of thos chapters, the main problem is where to do it and a big reestructuration is needed also a check for when if it present and when not, its a major rework to only a few chapters from a server, its a cost/benefits balance and the time i have

**Comment by borrougagnou** [comment]
Ha ! okay :/
because it isn't complicate, the "scrambled" image use `<canvas>` element, not the other:


![image](https://user-images.githubusercontent.com/10796546/56098109-4f332700-5efd-11e9-8d1c-a47ba52390ba.png)

![image](https://user-images.githubusercontent.com/10796546/56098119-6bcf5f00-5efd-11e9-8416-c2b921d915d8.png)

**Comment by borrou** [comment]
okay to back at this problem,
I found an idea:

I don't understand all the program, but maybe a good part.

you need to edit your __manga.db__ file and add 2 new column in `mangas.capitulos` :
- revuelto (bool/int)
- error (text)


### Revuelto
This column will indicate if we need to reuse "Init" download or if we can use "ReDownloadImage"

in JapScan for example,
the `revuelto` column indicate if we reuse  this function: https://github.com/raulhaag/MiMangaNu/blob/master/app/src/main/java/ar/rulosoft/mimanganu/servers/JapScan.java#L104 or no.
Each time when we request a download/re-download, they check if `revuelto` is true/false, if it's true he need to pass into that, if no he don't need, he can use "ReDownloadImage" directly


### Error
By default, this column is empty.
if an image isn't correctly downloaded they add the pict number into this column,
it work like `extra` column so

eg in JapScan again:
I have 5 pict (01.jpg -> 05.jpg)

if we have 03 and 04 they can't to be downloaded but other are okay
they add into error column: `https://c.japscan.to/<LinkToTheChapter>/<nb>/|03.jpg|04.jpg`
with that, this pict can be downloaded another time

**Comment by borrougagnou** [comment]
Japscan add now for almost each chapter a scrambled element...

if you can add my algo
(here: https://github.com/borrougagnou/unscrambled/blob/master/java/unscrambled/src/gui/PhotoFrame.java#L102)
\+ a regex if he detect `<canvas>` element or not
>scrambled image
![image](https://user-images.githubusercontent.com/10796546/58521977-af84dc00-81be-11e9-9b41-c9aaf0988b03.png)

>not scrambled image
![image](https://user-images.githubusercontent.com/10796546/58522130-43ef3e80-81bf-11e9-82c5-c6b505949bdd.png)


I won't refuse

**Comment by raulhaag** [comment]
Hi i addad all the code needed to make this work (i found a easy way https://github.com/raulhaag/MiMangaNu/commit/aed8c09853b44c524c9b7a66aa56cfabad1e1853#diff-34ab865f91cf6fad1fe75a674bcc04d2) but the unescramble not working correctly so take a look at it if you want https://github.com/raulhaag/MiMangaNu/commit/aed8c09853b44c524c9b7a66aa56cfabad1e1853#diff-34ab865f91cf6fad1fe75a674bcc04d2
also they use a different js for scrambeled and unescrambeled images so no more canvas on source, this is also taken in account

**Comment by raulhaag** [comment]
fixed the l90 problem

**Comment by borrougagnou** [comment]
@raulhaag HO ! WOW Why you have posted the "unscrambled" system into "master branch" + into 1.07 versions ???

it's isn't tested at 100% !!!
and as I see: each picture unscrambled have a little bug !
you have a "dark line" at the latest column !


and for my part, all scrambled picture are correctly fixed, so IDK where did you find scrambled pict with my algo wasn't usefull :/

**Comment by raulhaag** [comment]
Hi the adatation from your version is here (i can say it really different they way that you can do same thing over canvas)
https://github.com/raulhaag/MiMangaNu/blob/master/app/src/main/java/ar/rulosoft/mimanganu/utils/PostProcess.java
i didn't note tha collum on my test but perhaps its need thist same part for x  
```java
if (y > maxH - 200) {
            a = new Rect(0, y, maxW, maxH);
            rstImage.drawBitmap(myImg, a, a, null);
}
```

**Comment by raulhaag** [comment]
y found a example and tested the idea and yea that fixed ;-), so check the master and test it, or it go to be on next release

**Comment by borrougagnou** [comment]
okay :p I prefer test before you release

**Comment by borrougagnou** [comment]
oh yes ! it work now ! that's cool :p
but it's weird because he's slow for download :/
it isn't possible to "download all pict" and after convert ?

maybe I need to check that :/

**Comment by borrougagnou** [comment]
@raulhaag I have this error with japscan :/
![image](https://user-images.githubusercontent.com/10796546/59527718-a85b0f00-8edc-11e9-9c6e-a888fe4eb433.png)

for a "normal" pict without scrambling :/
![image](https://user-images.githubusercontent.com/10796546/59527877-11db1d80-8edd-11e9-8d17-9918d690d156.png)

receive:
https://c.japscan.to/lel/My-Wife-Is-A-Demon-Queen/81/|01.jpg|02.jpg|03.jpg|04.jpg|05.jpg|06.jpg|07.jpg|08.jpg|09.jpg

**Comment by borrougagnou** [comment]
Any idea what's happen ?

**Comment by raulhaag** [comment]
Still happend? i open that manga/chapter and work well

**Comment by raulhaag** [comment]
about the postprocessor order, if you need to wait to all download finish to read it the feel was horrible, planed as part of download just to be execute only once and the reader don't have the chance of block it for trying to load this without unescrambled, also take account o this "pp" take extra use of memory and processor so is needed.

**Comment by borrougagnou** [comment]
I receive this error again 3 days ago, but that all

and yes :/ you're true 

PS: KissManga down

**Comment by borrougagnou** [comment]
I would like to close my issue but I don't have finish the test and I have... uhm... how say... lots of manga from different serv for different test

But atm the preprocess work perfectly and I don't see picture with weird square into MiMangaNu
I wait, continu to check myself and listen here if somebody post about a manga who have a scramble picture or not

+ now I have a fiber so, it's a inconveignant because I can't replace myself by a people who use bad ADSL (like me before) and check about performance
