### ISSUE TITLE
any plans for a windows version?

### ISSUE THREAD

**Issue by likehelly** [raulhaag/MiMangaNu#619]
either a normal program or even a windows store app?

**Comment by auz-jsm** [comment]
There's a program I know that can download/fetch images from manga sites. The name of the program is HakuNeko S [formerly HakuNeko] (the one in sourceforge). 

But please support @raulhaag if he has a plan to make Windows environment based one. (Hope this comment don't violently against the author)

**Comment by raulhaag** [comment]
Hi @likehelly no plans to made a windows version for now, 
@auz-jsm  don't worry is not a competition, so no problem.
