### ISSUE TITLE
I can not read manga from my device

### ISSUE THREAD

**Issue by Reek0** [raulhaag/MiMangaNu#622]
Hola.

He colocado los mangas en la memoria del dispositivo y en la memmoria externa, reconoce la carpeta, pero la aplicacion no los lee, me dice "error" cuando los abre.

Pense que seria por la extension del archivo, asi que probe con .ZIP y .CBZ, pero sigue diciendo "error" cuando los abre.
_________________________________________

Hi.

I have placed the sleeves in the memory of the device and in the external memory, it recognizes the folder, but the application does not read them, it says "error" when it opens them.

I thought it would be because of the file extension, so try with .ZIP and .CBZ, but keep saying "error" when you open them.

**Comment by raulhaag** [comment]
hi for the monment not supportes cbz(not cbr) but really i planning to add but no to much time to do

**Comment by raulhaag** [comment]
cbz support added for next version, cbr was kepped appart due speed problems on old devices

**Comment by clach04** [comment]
I can confirm reading a CBZ works in v1.106 using the "FromFolder" option (it reads successfully from external SD) :)
