### ISSUE TITLE
No puedo descargar ni ver en VerComics

### ISSUE THREAD

**Issue by Nathancr87** [raulhaag/MiMangaNu#623]
Buenas noches. He actualizado a la última versión pero cuando quiero acceder a un cómic, sea cual sea, Marvel, DC, entre otros, en el servidor VerComics, no me permite ni ver ni descargar. 

Muchas gracias.

**Comment by raulhaag** [comment]
si alrededor del martes de esta semana issue(la pagina donde se publican las imagenes) agrego el forzar que las respuesta a las conecciones sean gzip el fix ya esta listo desde entoces solo que no hice un release ahora lo publico, si usas github vas a poder actulizar ahora, sino por fdroid 2 o tres dia con suerte
