### ISSUE TITLE
Mangas ocultos

### ISSUE THREAD

**Issue by marrokin** [raulhaag/MiMangaNu#626]
Buenos dias.

Se deberia poder proteger mangas con una contraseña 
Segun categorias o generos o mangas especificos

Agradezco su atencion y excelente trabajo

**Comment by raulhaag** [comment]
en la proxima version va a haber un sistema de vaults 
![Screenshot_1557324649](https://user-images.githubusercontent.com/2048339/57382192-d84b2000-7182-11e9-8bd5-9d80b38a24b4.png)
![Screenshot_1557324673](https://user-images.githubusercontent.com/2048339/57382214-e305b500-7182-11e9-90b9-2efa01a3567f.png)
![Screenshot_1557324690](https://user-images.githubusercontent.com/2048339/57382227-e731d280-7182-11e9-9f5e-f0064ca20626.png)
![Screenshot_1557324706](https://user-images.githubusercontent.com/2048339/57382233-ea2cc300-7182-11e9-8839-0fe4da1721e8.png)
![Screenshot_1557324716](https://user-images.githubusercontent.com/2048339/57382236-ec8f1d00-7182-11e9-909c-56c2e2548ae7.png)
