### ISSUE TITLE
TMO con problemas 

### ISSUE THREAD

**Issue by SoldadoZT** [raulhaag/MiMangaNu#627]
No me deja abrir el capitulo me tira error, pero los que ya había leído cuando los abro si me cargan

**Comment by raulhaag** [comment]
acabo de probarlo y me carga bien intenta de nuevo cerrando la app

**Comment by raulhaag** [comment]
o fíjate que no hayan retirado el manga de la página de tmo que me paso con un par

**Comment by SoldadoZT** [comment]
Gracias pude solucionarlo cerré la app y reinicie mi móvil y se arreglo
