### ISSUE TITLE
1.106

### ISSUE THREAD

**Issue by jtwpayn** [raulhaag/MiMangaNu#630]
Hello, with this update, it's freezing on startup. Have to uninstall and reinstall to be able the open it. If I select " hide read" or stop and restart the app it freezes again until I reinstall. I tried to go back to previous version but got an error that the database was corrupted. I will provide any help I can. But you'll have to instruct me on how to provide any logs you need. 

Thanks for all the work.

**Comment by raulhaag** [comment]
Share from your db folder the last backup

**Comment by jtwpayn** [comment]
Current
https://www.dropbox.com/s/3ivq1nzf2a4k95f/mangas.db?dl=0
Last backup
https://www.dropbox.com/s/9ckp1i36avub4at/mangas.db.27.bak?dl=0

**Comment by raulhaag** [comment]
Hi, install the last version and force close,  delete currehttp://bit.ly/lisTa-IPTVpreMUIMntil your huge db is backed up and updated to last version on a s8 it takes arround 1 minute of logo waiting. Also check your free space

**Comment by raulhaag** [comment]
Hi, install the last version and force close, delete current db and journal, copy and rename your 27 backup as mangas.db, open mmn app and wait until your huge db is backed up and updated to last version on a s8 it takes arround 1 minute of logo waiting. Also check your free space.

**Comment by jtwpayn** [comment]
Will do thanks.

**Comment by jtwpayn** [comment]
That didn't resolve the issue. I took it another step further and deleted the whole app directory and did a clean install. Everything is working now but seems sluggish. Takes a few seconds now to start or exit a manga to the primary screen. Any actions take a while too such as changing the sort. Definitely still usable but if you want anything from my current install please let me know.
