### ISSUE TITLE
Add list of supported sites to README

### ISSUE THREAD

**Issue by klntsky** [raulhaag/MiMangaNu#633]
As for now it is not clear which domains are supported, which are available but broken, etc.

Having a table containing this information would be extremely helpful for people who want to decide whether this app is suitable for them or not.

**Comment by auz-jsm** [comment]
Oopss, I understand it the other way! Sumimasen!

So you mean is like an indicator in the app's server lists (which are functional and which are not)?

**Comment by raulhaag** [comment]
@klntsky the list on the app in theory must be fully functional, i run test automated but not all the time if  i found a error i fix it or if some user found and post it i try to recreate and fix, but as you need to note this development is only on my free time not a 24/7 so an updated list must be a waste of time for me. but now im thinking on make a single fragment for automatic test from app
@klntsky i will keep the list you make ;-)
