### ISSUE TITLE
agregar leomangas.com

### ISSUE THREAD

**Issue by DarkGerZ** [raulhaag/MiMangaNu#635]
Hola me gustaría sugerir un servidor de manga en español https://www.leomangas.com/, lo encontré y opino que es un buen servidor.

**Comment by raulhaag** [comment]
la version anterior de leomanga estaba pero cuando dejo de estar disponible lo quite y ahora solo veo 14 mangas solamente por lo que no creo que valga la pena agregarlo por el momento quizas en un futuro si crece si.
