### ISSUE TITLE
Add MangaRock

### ISSUE THREAD

**Issue by borrougagnou** [raulhaag/MiMangaNu#642]
If I have time maybe I will start to create a new mangalist
after if someone want begin this project before me, you can (because I'm not sure when I will start....)

## API
you can found how API work here for someone want begin
#### Python language:
https://github.com/italomaia/mangarock.py

#### Go language:
https://github.com/bake/mangarock/blob/master/mangarock.go

#### Go language:
https://github.com/bake/mri/blob/master/mri.go

#### JS language
https://github.com/bake/mri.js/blob/master/src/index.ts

## API Latest Release
https://api.mangarockhd.com/query/web401/mrs_latest

just, prevent me when you begin

**Comment by aelisya** [comment]
You can abandon this idea mangarock is shutting down
https://mrcomics.com/

**Comment by borrougagnou** [comment]
ow... okay
so I close this ticket, thank for the information
