### ISSUE TITLE
Some news to do (with Japscan)

### ISSUE THREAD

**Issue by borrougagnou** [raulhaag/MiMangaNu#645]
I don't have time ATM so if someone want fix that:

## improvement:
`japscan.to` become `japscan.co`

### error :
issue info: https://github.com/raulhaag/MiMangaNu/issues/641

problem with some manga chapter like: 
https://www.japscan.to/lecture-en-ligne/jagaaaaaan/39/1.html
or https://www.japscan.co/lecture-en-ligne/sekai-oni/44/1.html

### how to fix :
need to fix android algo here: https://github.com/raulhaag/MiMangaNu/blob/master/app/src/main/java/ar/rulosoft/mimanganu/utils/PostProcess.java

original algo (work perfectly): https://github.com/borrougagnou/unscrambled/blob/master/java/unscrambled/src/gui/PhotoFrame.java#L102)

**Comment by raulhaag** [comment]
@borrougagnou 
those 2 pages lead to 
![imagen](https://user-images.githubusercontent.com/2048339/65880283-ee42c280-e367-11e9-87f3-c5c1da6deb91.png)

**Comment by borrougagnou** [comment]
Retry now, it's just a bug because they change her domain

**Comment by raulhaag** [comment]
that still happends or can close?

**Comment by borrougagnou** [comment]
oh ! its weird, the image work perfectly now .-.
but I don't see any commit who someone fix that
