### ISSUE TITLE
Game

### ISSUE THREAD

**Issue by marrokin** [raulhaag/MiMangaNu#646]
Hola buenas tardes, se me ocurrio que la aplicacion debería tener algun sistema de logros
Por ejemplo logros como
Mangas leidos
Mangas terminados
Mas descargados
Y cosas por el estilo

**Comment by raulhaag** [comment]
Desde mi punto de vista es demaciado desarrollo y uso de recursos para algo que no contempla el objetivo de la aplicacion y que de que me sobrara el tiempo lo invertiria en mejoras en la misma, quizas parezca media aburrido pero es mi opinion
