### ISSUE TITLE
The application is slow

### ISSUE THREAD

**Issue by Gintokisakat** [raulhaag/MiMangaNu#648]
Hello, the application when leaving a manga takes too long.
I don't know if it is for restoring my sleeves from an earlier version or what causes it
If this happened to anyone and he could solve it, I would appreciate it if he told me how to fix it

**Comment by Gintokisakat** [comment]
The problem is present when the option to hide read mangas is activated

**Comment by borrougagnou** [comment]
Ho yeah ! Good deduction, I though the problem is my network connexion or something like that but no !

**Comment by raulhaag** [comment]
please add device spects and a aproximation of ammount of mangas

**Comment by raulhaag** [comment]
please try this version (it still in debelopment but you can try if this works for you) and make a feedback
[Uploading app-github-release.zip…]()

**Comment by Gintokisakat** [comment]
> please try this version (it still in debelopment but you can try if this works for you) and make a feedback
> Uploading app-github-release.zip…

Hi, I tried the trial version. There is a notable improvement in loading time, it has a small delay when returning from a manga but nothing compared to before
