### ISSUE TITLE
Backup of the manga list

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#65]
Ok so I'm going to bother you again ^^

I end up using the app almost full time to read manga, so if I want to know where I am on a manga to be able to read it with my computer or anything else than the app, I need to look in the app.
But the thing is, if I loose my phone, or if it crash, I'll loose the list of my manga and where I was.

So I was wondering if it were possible to export the list of manga I'm reading with info as the manga name, the scan site, and the last chapter mark as read ?
If you can save this file on the phone, I'll be able to synch the repertory with the save with my computer and always have this list on my computer too in case.
having this as an option and being able to choose the repertory would be great !

I already lost all my manga list in the past and it was a trouble to be able to find all of them back.

**Comment by raulhaag** [comment]
ín your petition there is two different export tipes:
* export the db as if to import i case of divice change, etc.
* export the db to be readable from any site (cvs is an output plausible option).
the first only readable with any sqllite db manager
what you want?

**Comment by Dostoi** [comment]
The first can only be used with the app ?
I would find it better if it can be used by everyone so maybe the second one

**Comment by Johndeep** [comment]
Here another fine tuning, with the #99 patch, the database of the entire manga collection will be saved in the MiMangaNu/ folder too, so the database will survive an app uninstall.
Furthermore, now it is possible to just move the manga folder onto another device, the newly installed app will automatically recognize the database.

**But beware!!** If this patch and all together will be updated, you have to move the database from earlier version from data/data into the MiMangaNu/ folder!! Sorry if this is necessary.. but it will get better..

**Comment by Dostoi** [comment]
Perfect :)

**Comment by Johndeep** [comment]
Sorry for making wrong hopings, but it seems that I have to remove this change, because
1. This only works in debug mode, I didn't know and
2. This would lead to vast problems for people, who would update the program and wonder that all the list are gone.

Let us try to work on an import/export function instead, it's safer and more straight forward.

**Comment by Dostoi** [comment]
It's the same in the end don't worry ;)

**Comment by raulhaag** [comment]
is ready see /MiMangaNU/dbs/ 
there is the backup since 1.34 :wave:

**Comment by Dostoi** [comment]
How often does it work (and what exactly does it save ?) ?
It would be nice to know about this feature in the app somewhere (and be able to generate one if you want to save everything before a wipe or to switch to another phone)

**Comment by Johndeep** [comment]
Well, it should always work (and it saves the mangas.db right into the "MiMangaNu" folder).
It will automatically detect, if an old database is present and will save this into the work folder.
After starting the app, you maybe notice a short restart, where the app successfully got the old database copied into the new folder.

You can browse the "MiMangaNu" folder to see, if there is the database (it should also be bigger than only 32KB, if there is any manga stored, just ignore the journal file by the way). If so, you can then safely reset the app without loosing the manga database.

**Comment by Dostoi** [comment]
I'm just not sure what's in it. The manga list, the read and unread chapter for each manga, and also the picture for those who where downloaded ?
And it saves every time I make a change in what I mentioned above ?

**Comment by Johndeep** [comment]
Hmm, to try to put it simple, it's like the entire (yes, manga, read, unread, etc.) storage is moved into the work folder. So the app works with that database, not the one in the old storage anymore.

If you have updated to 1.34 and started it already, you can just wipe the app data, but don't touch the MiMangaNu folder. If you want to be suuuper sure, just move the MiMangaNu folder from another "new" device and check out what you want to know.

**Comment by Dostoi** [comment]
Ho perfect then.
Thanks for the work both of you :)
