### ISSUE TITLE
Lag cuando se activa "Ocultar leídos" / Lag when "Hide read" is activated

### ISSUE THREAD

**Issue by Zaissei** [raulhaag/MiMangaNu#650]
Buenas.

Primero de todo, gracias por compartir tu trabajo.

En cuando al "fallo"... aparece cuando se activa la opción de "ocultar leídos". Tener esa opción activada hace que cuando quieres volver (mediante la flecha superior izquierda o presionado "atrás" del dispositivo) a la pagina principal, desde un manga o desde "Configuraciones", haya un retraso de ~5-8 seg. por lo demás funciona con normalidad (oculta los leídos). El simple hecho de activar la opción ya tiene lag.
Si esta opción no esta activada funciona todo muy fluido.

He probado a reinstalar la aplicación pero sigue con el fallo.

Si no recuerdo mal, el fallo apareció cuando se añadieron las bóvedas.

Estaría agradecido si pudieras solucionarlo.

Un saludo y gracias.

__________________________________________________________________________________________
Translated by DeepL . . .
__________________________________________________________________________________________

Hi.

First of all, thank you for sharing your work.

As for the "bug"... it appears when the "hide reads" option is activated. Having this option activated means that when you want to go back (using the upper left arrow or by pressing "back" on the device) to the main page, from a Manga or from "Settings", there is a delay of ~5-8 sec. otherwise it works normally (hides the read). The simple fact of activating the option already has lag.
If this option is not activated, everything runs very smoothly.

I tried reinstalling the application but it still fails.

If I remember correctly, the bug appeared when the vaults were added.

I would be grateful if you could fix it.

Greetings and thanks.

**Comment by raulhaag** [comment]
podrias compartir la db y especificaciones del dispositivo para tener una idea del entorno, porque las puebas con mi cel tablet es practicamente instantanea la transicion

**Comment by Zaissei** [comment]
Buenas.

Aquí esta la db:
[https://www.dropbox.com/s/z47mthvyizokr3a/mangas.db?dl=0](url) Dropbox
[https://drive.google.com/open?id=1sdflt_oO7H13VkkYZoZx1rphL1bOeHW4](url) GoogleDrive

Las especificaciones del dispositivo:
**Xiaomi Mi 8**
 - Snapdragon 845
   GPU Adreno 630
- 6 GB RAM

Y un pequeño clip con el problema:
[https://www.dropbox.com/s/pdgbriro0focjiy/MMN.mp4?dl=0](url)

Un saludo y gracias.

**Comment by raulhaag** [comment]
Hola creo que ya esta listo un error mio fijate si esta version de prueba te funciona bien
[app-github-release.zip](https://github.com/raulhaag/MiMangaNu/files/3804187/app-github-release.zip)

**Comment by borrougagnou** [comment]
It work !

**Comment by Zaissei** [comment]
Perfecto
Mil gracias!

**Comment by borrougagnou** [comment]
@Zaissei close issue ?

**Comment by Zaissei** [comment]
@borrougagnou Okay
@raulhaag Un saludo y gracias
