### ISSUE TITLE
problemas con esninemanga

### ISSUE THREAD

**Issue by kallius** [raulhaag/MiMangaNu#651]
hola.
resulta que llevo unos días sin que se actualicen algunas de las series que sigo y de casualidad me he dado cuenta que el problema radica en esninemanga, ya que no actualiza ni descarga nuevos capitulos. he probado otro servidor con la mismo manga y si le descargo.
bueno eso, espero que ayude, gracias por el trabajo ;)

**Comment by raulhaag** [comment]
listo para la proxima version

**Comment by kallius** [comment]
Listo actualizado y OK, gracias 😉
