### ISSUE TITLE
Mangaeden need account for some manga

### ISSUE THREAD

**Issue by borrougagnou** [raulhaag/MiMangaNu#652]
Hi !

not for all manga but some I don't know why, Mangaeden request to be logged

Like Aka Akatoretachi no Monogatari
If you click on the first chapter he say we need to be connected :/
https://www.mangaeden.com/en/en-manga/aka-akatoretachi-no-monogatari/

**Comment by raulhaag** [comment]
Ready for next version, also you go to need a account :-$

**Comment by borrougagnou** [comment]
Okay ! No problem

**Comment by borrougagnou** [comment]
Mangaedenlt ???

**Comment by raulhaag** [comment]
also have the some system (checked in some mangas) and it extends the mangaeden class, also you can use the same credentials. 
make a feedback is all works ok or not

**Comment by borrougagnou** [comment]
Okay for me it work now without problem !
👍
