### ISSUE TITLE
can't download from TMO

### ISSUE THREAD

**Issue by kiandas74** [raulhaag/MiMangaNu#653]
after the last actualization I can't download from TMO, there's no problem to add new chapters and mangas to my galery but, when I try to download a new chapter it takes a long time trying to donwload a it end ends in error.

**Comment by borrougagnou** [comment]
I understand why, it because cloudflare + recaptcha
![IMG_20191106_020107](https://user-images.githubusercontent.com/10796546/68259158-63757780-0039-11ea-9332-37e2068ce672.jpg)

**Comment by kiandas74** [comment]
oh, I see, what's the solotion, becauese the majority of my mangas are from this server and I want to continue reading.

**Comment by borrougagnou** [comment]
You have 3 choice:
- read online until the update
- wait an update and do nothing or continu with manga you have
- read from multiple server (like me and lots of people here)

**Comment by raulhaag** [comment]
@kiandas74 tmo esta cambiando ya van 2 fixes que hago pero sigue, te recomendaria que no lo uses por ahora hasta que publique una nueva version ya tengo lista la estructura para ne tener que actualizar la app cada vez que esto pasa pero siguen cambiando por lo que no lo estoy publicando.
@borrougagnou  lucky for me i don't see any captcha

**Comment by raulhaag** [comment]
ahi publique una nueva version que puedo donde el script se carga del repo y lo puedo actualizar sin necesidad de que lo haga con la aplicacion

**Comment by borrougagnou** [comment]
:o fast !
But not work for me unfortunately 
I don't see the list 🤔

**Comment by Danielcastro502** [comment]
Hola amigo no sé cómo solucionar sobre la nueva actualización y no entiendo muy bien esta página tiene otro medio para contactarte  para que me ayudes

**Comment by Danielcastro502** [comment]
☹️

**Comment by raulhaag** [comment]
@borrougagnou  in your case you need to use the normal page from your browser a couple of days and it go to remove the captcha, or if you don't have fixed ip change it.
@Danielcastro502 todo contacto es por este medio, si bajaste la v1.112 y al accesar a la pagina no te aparece que mostro borrougagnou con solo reinicial la aplicacion la modificacion de hoy a la mañana tendria que funcionar

**Comment by borrougagnou** [comment]
Okay, I check that

**Comment by Danielcastro502** [comment]
No me deja instalar la nueva versión

**Comment by raulhaag** [comment]
Si tenes la versión de fdroid tenes que desintalarla porque ellos la compilan con su propia firma y no te va a dejar instalar esta o esperar un par de días a que este disponible ahí, igual la db no se pierde solo algunas customizaciones que podes hacer backup antes de desinstalar y retire después de instalar la nueva

**Comment by Danielcastro502** [comment]
Pero si desinstalo esa versión se pierde los mangas que  tengo guardado?

**Comment by raulhaag** [comment]
La db (la información de los mangas) no se pierde a menos que la borres manualmente todo esto esta en la carpeta de MiMangaNu

**Comment by Danielcastro502** [comment]
Bro muchas gracias ya puedo leer mangas de lo agradezco

**Comment by kiandas74** [comment]
thanks, I have already donwload the new version and is all ok.
