### ISSUE TITLE
Crash in the english servers

### ISSUE THREAD

**Issue by Axggdamer** [raulhaag/MiMangaNu#654]
When I make a search in the english servers in my leeco x526 the app crashes with the version 1.112 (I see my problem in the past act) 

Sorry for the english im mexican :D

**Comment by raulhaag** [comment]
Habla en español que es mi idioma nativo, ¿cual servidor?¿Todos o alguno en especial?

**Comment by borrougagnou** [comment]
More information ?
something to reproduce that ?
what english server ?
android version ?

**Comment by raulhaag** [comment]
@borrougagnou that is the question

> 
> 
> More information ?
> something to reproduce that ?
> what english server ?
> android version ?

**Comment by Axggdamer** [comment]
Tengo android 6.0.1 con un snapdragon 652 y 3gb de ram, los servers son Mangapanda, mangareader, mangaeden, tadd y readmangatoday

**Comment by raulhaag** [comment]
probe un par de esos y va bien algun termino en especial? tenes la posibilidad de hacer un logcat?

**Comment by raulhaag** [comment]
O probar esta version que genera un archivo txt en la carpeta de MiMangaNu/logs en caso de que se cierre la app inesperadamente.
[app-github-release.zip](https://github.com/raulhaag/MiMangaNu/files/3814987/app-github-release.zip)

**Comment by Axggdamer** [comment]
Este es el log que genero
[06-11-2019--09-31-39.txt](https://github.com/raulhaag/MiMangaNu/files/3815356/06-11-2019--09-31-39.txt)

**Comment by raulhaag** [comment]
ok eso ayuda en un rato te subo una version para que pruebes

**Comment by raulhaag** [comment]
ahi esta es un error de api level que no me advirtio el compilador ahí esta, avisame como te va con esta versión.
[app-github-release.zip](https://github.com/raulhaag/MiMangaNu/files/3815512/app-github-release.zip)

**Comment by Axggdamer** [comment]
Ya funciona perfecto gracias por tu atencion tkm <3

**Comment by raulhaag** [comment]
Gracias a vos por continuar con el feedback, saludos y cierro este issue
