### ISSUE TITLE
reenable the suport to esmanga an add suport to bato.to

### ISSUE THREAD

**Issue by xken2x** [raulhaag/MiMangaNu#66]

**Comment by raulhaag** [comment]
Esmanga tuvo problemas con su servidor y están subiendo todo de nuevo con un sistema diferente por lo que no concuerda con la versión anterior estoy esperando que se mejore para agregar un soporte nuevo y bato.to es muy errático y no se ajusta al modelo de sitio aunque hace un tiempo que tengo en mente agregarlo, pero tendría que modificar unas cuantas bases con lo de múltiples idiomas y su forma tan especial.

**Comment by xken2x** [comment]
Thanks forma the answer!!!

But i like the suport to batoto,and i can help you with your proyect, tell me if i can help you with anything what you can need un the future
