### ISSUE TITLE
Acceso directo

### ISSUE THREAD

**Issue by marrokin** [raulhaag/MiMangaNu#661]
Poner en el icono de la aplicacion acceso directo a
Buscar capitulos
El ultimo leido
Dos o tres favoritos

**Comment by raulhaag** [comment]
Agregado para la proxima version para android 7.1 o superior ultimos leaidos y con la posibilidad de arrastrar y dejar el icono de acceso en el escritorio

**Comment by raulhaag** [comment]
y por supuesto si tu distribucion de android lo soporta no como miui <-<

**Comment by marrokin** [comment]
Tambien si es posible con click sostenido en el manga que aparezca crear acceso directo en la pantalla principal

**Comment by raulhaag** [comment]
@marrokin agregado y esa es compatible con android antiguos por lo visto 4.3.1 que tengo virtual y funciono lo mas bien, tambien lo hizo en xiaomi :-D, tambien corregi un error que havio con el giro y reinicio de la app cuando se lanzaba desde shortcuts y va a estar en la proxima version
