### ISSUE TITLE
Boton de no buscar descargas

### ISSUE THREAD

**Issue by Axggdamer** [raulhaag/MiMangaNu#662]
En la nueva version 13 este boton que digo no funciona y los busca por igual, mi celular es un leeco le 2 con 3gb de ram y 32 de rom

**Comment by raulhaag** [comment]
No buscar descargas los marca como finalizados pero si en configuraciones esta activado la opcion de incluir mangas finalizados busca igual, fijate si este es tu caso

**Comment by Axggdamer** [comment]
Ya vi que no es esto, de verdad el boton de no buscar descargas no funciona y los busca por igual D:
