### ISSUE TITLE
Faltan capitulos

### ISSUE THREAD

**Issue by Axggdamer** [raulhaag/MiMangaNu#663]
Siguen los problemas en servers, ahora hay mangas que se saltan desde el 18 al 100 cuando en la pagina oficial de cada server no es asi, este problema lo he visto con mangas de TMO pero ni idea de que pase, espero que lo arreglen porfavor, esta es la mejor app de manga que existe actualmente

**Comment by raulhaag** [comment]
ejemplo de manga?

**Comment by Axggdamer** [comment]
Jojolion, los de hellsing, Nichijou (este ultimo antes de la act tenia todos los caps disponibles)

**Comment by raulhaag** [comment]
entra y fijate, igual ya hay un fix para el problema de la v anterior que en realidad es que falta el primero y los numeros de capitulos estan desfasados en 1
https://tmofans.com/library/manga/9503/nichijou

**Comment by Danielcastro502** [comment]
En mi caso se repiten los cap o no salen completos cuando actualizo mangas
