### ISSUE TITLE
Desaparecen los capitulos por si solos

### ISSUE THREAD

**Issue by Axggdamer** [raulhaag/MiMangaNu#664]
Esto es muy extraño de explicar, estaba leyendo un cap cuando de repente salgo del lector y PUM! desaparecen los ultimos 7 capitulos que habian salido y despues entro a otro manga de mi lista y PUM! desaparecieron los 900 capitulos de one piece

**Comment by raulhaag** [comment]
tenes la opcion ocultar leidos activado?

**Comment by Axggdamer** [comment]
si y me siento estupido u-u
