### ISSUE TITLE
Error al entrar a cualquier manga

### ISSUE THREAD

**Issue by Gintokisakat** [raulhaag/MiMangaNu#665]
Al entrar a cualquier manga la aplicación crashea, probé eliminar el caché y la data pero nada.

Mi dispositivo es un moto e4 plus con Android 7.1.1

**Comment by Gintokisakat** [comment]
Trate también desinstalando la app pero cuando reinstalo la última versión vuelve a dar el error

**Comment by raulhaag** [comment]
podes buscar en la carpeta de MiMangaNu una llamada logs y compartirlos para ver que esta pasando

**Comment by raulhaag** [comment]
test this version if works
[app-github-release.zip](https://github.com/raulhaag/MiMangaNu/files/3828732/app-github-release.zip)
