### ISSUE TITLE
V1.115 Failed to connect to raw.githubuser...

### ISSUE THREAD

**Issue by ElTrinidad** [raulhaag/MiMangaNu#669]
Hola. Primero de todo felicitarte por crear una aplicación para leer manga totalmente libre de publicidad.

El problema es que, desde que se actualizó a la última versión, me aparece este mensaje cuando intento descargar un manga alojado en TMO: "Failed to connect to raw.githubusercontent.com/127.0.0.1:443"

Mi versión de android es 7. Pero, la versión anterior, aunque fallasen las cabeceras, sí que podía leerlos y descargarlos.

**Comment by raulhaag** [comment]
Parece un error de conección algo te manda al localhost(127.0.0.1) puede ser algún bloqueador  posiblemente que el host esté modificado o vpn en tu dispositivo, esta versión usa script remoto para actualizar los cambios en vez de sacar  nuevas versiones todo el tiempo

**Comment by ElTrinidad** [comment]
> Parece un error de conección algo te manda al localhost(127.0.0.1) puede ser algún bloqueador posiblemente que el host esté modificado o vpn en tu dispositivo, esta versión usa script remoto para actualizar los cambios en vez de sacar nuevas versiones todo el tiempo

**Comment by ElTrinidad** [comment]
Lo he comprobado todo y no hay ningún problema de redirección, tampoco uso ningún VPN. Pero, me estoy encontrando que, desde España, están capando el acceso a varios sitios donde se pueden ver series y películas. Imagino que han hecho lo mismo con el servidor de TMO, aunque los otros servidores funcionan correctamente.

Aún así, puedo acceder a la página de TMOfans y leerlos. Es muy extraño.

**Comment by raulhaag** [comment]
Chequea si podes acceder desde el celular a este sitio 
https://raw.githubusercontent.com/raulhaag/MiMangaNu/master/js_plugin/22_1.js

**Comment by ElTrinidad** [comment]
No, no me deja. Me dice el navegador que no lo encuentra.

**Comment by ElTrinidad** [comment]
Tampoco me deja en el pc. Puede que sea mi proveedor de internet.

**Comment by ElTrinidad** [comment]
Ya sé por qué:

"raw.githubusercontent.com bloqueada por autoridad judicial desde España https://www.meneame.net/m/Retuit/raw-githubusercontent-com-bloqueada-autoridad-judicial-desde "

Pues está bloqueada desde hace 48 horas. El tiempo desde que me sale el mensaje.

De todas formas, gracias por las sugerencias.

**Comment by raulhaag** [comment]
Lo que podes intentar es usar opendns o algo por el estilo no estoy seguro de que funcione pero no esta de más intentarlo

**Comment by raulhaag** [comment]
Igual para la próxima voy a ver si utilizo alguna alternativa

**Comment by ElTrinidad** [comment]
Acabo de probar cambiando el protocolo de DHCP a IP estática con la DNS que sugieren los tweets y tampoco funciona.

Nada, en España nos quedamos aislados. Y luego hablan de China...

Gracias por tu trabajo. Si en el futuro encuentras una alternativa que no puedan capar, estaré expectante.

Un saludo

**Comment by raulhaag** [comment]
Consulta, si tratas de bajar la app desde releases te deja? O bloquea

**Comment by ElTrinidad** [comment]
Me deja descargarla. Ahí no hay problema.

**Comment by raulhaag** [comment]
Si no te importa te voy a pedir después cuando esté en casa un par de pruebas para sacar una versión que funcione en españa

**Comment by raulhaag** [comment]
O mañana que ya debe ser tarde en España

**Comment by ElTrinidad** [comment]
Ok, Gracias. Espero que no muy tarde por la diferencia horaria. Aquí ahora son las 23:30h.

**Comment by ElTrinidad** [comment]
Prueba, y si no estoy durmiendo, te hago las pruebas que necesites.

**Comment by raulhaag** [comment]
si estas sino mañana podes probarla si funciona y te va a decir que hay una version nueva (en realidad es la que esta publicada actualimente) si podes probar si la descarga (no te va a dejar instalarla porque marque esta version como posterior pero lo que me interesara es si descarga)
[app-github-release.zip](https://github.com/raulhaag/MiMangaNu/files/3838694/app-github-release.zip)

**Comment by ElTrinidad** [comment]
Afirmativo. Me ha dejado descargarla. Pero no he probado a instalarla por lo que has comentado.

**Comment by ElTrinidad** [comment]
La he instalado y ahora sí que funciona perfectamente. Puedo abrir y descargar lis de TMO sin problema.

Eres un genio. Muchas gracias.

**Comment by raulhaag** [comment]
Lo que quiero que pruebes es si descarga cuando te dice que hay una actualización

**Comment by raulhaag** [comment]
Desde la app

**Comment by ElTrinidad** [comment]
Perdona, no te había entendido.

Sí que muestra que hay actualización disponible, sí que la descarga, y no la instala. Tal y cómo habías comentado.

**Comment by raulhaag** [comment]
Joya, es todo lo que necesitaba saber mañana veo si saco una versión para para que puedan leer los usuarios de España
Saludos y gracias por el feedback.

**Comment by ElTrinidad** [comment]
Gracias a ti por tu currada.

Saludos

**Comment by Danielcastro502** [comment]
Hola. Cuando intento abrir un cap sale (error)

**Comment by raulhaag** [comment]
@Danielcastro502  si no estas en España reinicia la app y deberia funcionar de nuevo sino podes usar la de prueba que postie en este hilo

**Comment by ElTrinidad** [comment]
@raulhaag 

Hola. La versión de prueba que colgaste ayer, no realiza correctamente la búsqueda de nuevos capítulos. Se queda todo el rato en "buscando nuevos mangas".

Te lo comento por si tienes que realizar algún ajuste, antes de publicar la nueva versión.

**Comment by Danielcastro502** [comment]
Disculpa las molestia bro parece que era problema del mismo  tmo

**Comment by Danielcastro502** [comment]
Y cuando puedo AGG sale sin caps

**Comment by raulhaag** [comment]
Ya esta una nueva version @ElTrinidad tenes que bajarla manualmente por que la version figura igual a la que tenes

**Comment by ElTrinidad** [comment]
@raulhaag 

Muchas gracias. Acabo de descargarla, instalarla y probarla. Busca nuevos capítulos, descarga correctamente las cabeceras y se pueden leer perfectamente. Eres la hostia.

Saludos
