### ISSUE TITLE
Option to choose download location

### ISSUE THREAD

**Issue by Ferk** [raulhaag/MiMangaNu#67]
In my phone the mangas get downloaded in the internal memory instead of the SD card (in recent versions of android the internal memory is sdcard0 and external memory sdcard1). This causes my storage space to run out very easily when I download a long manga.

It would be nice if either the sd card was selected by default when available or at least an option was given to be able to choose a different location.

**Comment by raulhaag** [comment]
No problem, but the user need to move the content, righ now i{m working on big changes adapting to new features of lollipop an this go to take a time, just in case, can you tell me the divice and the os version?

**Comment by Ferk** [comment]
Thank you, this app is really nice for reading while commuting, it's basically the only thing I use for reading manga now.

My device is a Xiaomi Redmi 1S, running Android 4.4.4
