### ISSUE TITLE
Error TMO

### ISSUE THREAD

**Issue by SoldadoZ** [raulhaag/MiMangaNu#670]
No me carga ningun capitulo de TMO ni me deja actualizar para ver si hay mas capitulos voy al dia con todas las actualizaciones de la app

**Comment by Danielcastro502** [comment]
Hola descargue la última versión la 1.116 pero sale error al intentar ver un capítulo y no me deja AGG nuevos mangas

**Comment by SoldadoZ** [comment]
Ya me carga los capitulos pero el problema de actualizar para ver si hay capitulos nuevos persiste

**Comment by Gintokisakat** [comment]
> Ya me carga los capitulos pero el problema de actualizar para ver si hay capitulos nuevos persiste

Hola cómo hiciste para que te cargen?

**Comment by xVlade00** [comment]
A mi tambien me pasa lo mismo. TMO parece predispuesto a causarle inconvenientes a Raulhaag. Ojala se arregle pronto para que deje de darle dolores de cabeza al desarrollador

**Comment by raulhaag** [comment]
El problema fue el programador que no cambio un uno por un dos y ya deberia estar funcionando Ups....  reinicien a app

**Comment by Tapo669** [comment]
Discúlpenme por mi ignorancia pero a qué se refiere con reiniciar la app...la cierro y la vuelvo a abrir? :(
