### ISSUE TITLE
Buscar nuevos mangas

### ISSUE THREAD

**Issue by Nathancr87** [raulhaag/MiMangaNu#673]
Buenas tardes.
Cuando inicio la aplicación e inicia la búsqueda de nuevos mangas se queda un rato como cargando y cuando empieza solo cuenta uno o dos y se lleva mucho tiempo sin avanzar a los otros. Es algún problema? Es cosa nuevamente de lo de TMO? la gran mayoría los tengo allí por el tema de los nombres en los capítulos.

Muchas gracias por todo el trabajo que haces.

**Comment by raulhaag** [comment]
Al iniciar el proceso enpieza checkeando y validando si hay cloudflare en caso de haber son 5 seg extra por server que lo tenga activo luego TMO permite cierto numero de consultas por minuto por lo que agregrue un bloqueo de hilo y un descanzo entre consulta de un par de segundos por eso parece un avance lento, pero es para evitar el bloqueo.

**Comment by Nathancr87** [comment]
Muchas gracias por el trabajo 😜
