### ISSUE TITLE
Bloqueo aplicaciones externas TMO

### ISSUE THREAD

**Issue by RZRT** [raulhaag/MiMangaNu#675]
Hola!
Estuve leyendo otros 2 hilos abiertos sobre problemas con TMO pero en ellos reportaba solo error al cargar un manga, en mi caso aparece una imagen indicando el bloqueo a aplicaciones externas (con un sello de Banned)
Adjunto imagen

Gracias por cualquier info referida! 
![Screenshot_20191120-082116](https://user-images.githubusercontent.com/57990310/69235203-9f4b2980-0b6f-11ea-8335-9a44f1b72f77.png)

**Comment by raulhaag** [comment]
reinicia la aplicacion y resetea los capitulos con este mensaje que ya esta funcionando

**Comment by RZRT** [comment]
Gracias por la respuesta ultra rápida, no me funciono reiniciando ni eliminando los mangas, directamente reinstale y ahí si todo perfecto! Gracias!

**Comment by raulhaag** [comment]
@RZRT  para futuros cambios, reiniciar es cerrarla y si quede en memoria (se ve en la lista de recientemente usadas) tambien cerrarla ahi

**Comment by RZRT** [comment]
Si, lo sabía, la cerré desde las aplicaciones recientes, incluso luego desde el administrador de aplicaciones force la detención, pero continuaba mostrándome el mismo error, por eso hice lo que te comenté más arriba. Te agradezco el tiempo y los comentarios! Tu app es genial, se aprecia tu trabajo y soporte! Gracias!
