### ISSUE TITLE
Mangas que no se pueden agregar a TMO 

### ISSUE THREAD

**Issue by Josking28** [raulhaag/MiMangaNu#678]
Es un problema que lleva un tiempo, hay mangas que no se agregan correctamente de tmo, no sale ni la carátula ni los capítulos de mangas cómo: killing me / killing you, Fate Stay Night heaven feels y otros mangas de la saga fate.

**Comment by kiandas74** [comment]
tambien me pasa lo mismo y quisiera saber porque sucede

**Comment by raulhaag** [comment]
arreglado para la nueva version probablemente que salga mañana

**Comment by Josking28** [comment]
Ya está arreglado, gracias.

**Comment by Josking28** [comment]
@raulhaag los capítulos se agregan pero no se pueden descargar, intenté con otros mangas y si descargaban.

**Comment by raulhaag** [comment]
reinicia y reintenta en cinco min que recien subi un fix

**Comment by Josking28** [comment]
Ya se puede, gracias.
