### ISSUE TITLE
Problema con ReadManga?

### ISSUE THREAD

**Issue by xmithosx** [raulhaag/MiMangaNu#679]
Hola, desde ayer por la tarde, no puedo ni descargar Mangas ni buscar, el proceso de búsqueda se da casi que inmediatamente, y de los capítulos que ya tenia detectados pero que no había descargado, cuando le doy iniciar me sale el siguiente mensaje: "Attempt to invoke visrtual methos 'int java.lang.String.length()" on a null object reference.

Mi duda de que sea con ReadManga es porque me pasa con TODOS los mangas que tengo cargados, todos desde ese server, pero desde otros server no.

**Comment by raulhaag** [comment]
ya tengo listo un fix de cloudflare que sirve para todos los sitios que tienen este problema

**Comment by xmithosx** [comment]
Perfect.... resuelto gracias hombre...
