### ISSUE TITLE
problems with tusmangaonline

### ISSUE THREAD

**Issue by Sheiko222** [raulhaag/MiMangaNu#68]
I cant add mangas from tusmangaonline in this version.

**Comment by raulhaag** [comment]
arreglado para la próxima version

**Comment by raulhaag** [comment]
lo arregle pero están haciendo actualizaciones en el sitio por lo que lo tengo que volver a hacer, voy a esperar un par de días para hacerlo de nuevo a ver si terminan

**Comment by Sheiko222** [comment]
Dale, gracias.

**Comment by raulhaag** [comment]
listo pero el servidor les esta funcionando bastante mal por lo que tira bastantes timeout  por lo que no funciona como debería, por otro lado los patrones ya están corregidos, son correctos y estaran disponibles en la próxima versión que mañana después de probarla un poco voy a publicar si va bien.
