### ISSUE TITLE
kissmanga completely broken as of today.

### ISSUE THREAD

**Issue by MtnDewritos** [raulhaag/MiMangaNu#680]
Trying to open a new chapter from kissmanga or go to the kissmanga server gives the error: Attempt to invoke viritual method 'int  java.lang.String.length()' on a null object reference

Searching for updates also takes no time at all compared to when kissmanga worked a couple of days ago and leads to no new chapters found (I use kissmanga  almost exclusively for over 200 manga).

**Comment by raulhaag** [comment]
test last version

**Comment by MtnDewritos** [comment]
Works great now
