### ISSUE TITLE
JapScan server is not accessible

### ISSUE THREAD

**Issue by Whydraz** [raulhaag/MiMangaNu#681]
Since today, impossible to do anything.
Viewing toast "Attempt to invoke visrtual methos 'int java.lang.String.length()" on a null object reference" each time I try to get manga or search.

I saw similar issues on other servers (kissManga, ReadManga).

**Comment by raulhaag** [comment]
fix on new release

**Comment by Whydraz** [comment]
Resolved ! Thank you :)
