### ISSUE TITLE
Es posible agregar Manga/Comics offline?

### ISSUE THREAD

**Issue by fbutte** [raulhaag/MiMangaNu#683]
Hola chicos, pregunto esto ya que es una característica que tiene Tachiyomi y sería genial poder tenerla acá. Ya que MMN es más activa por lejos.
Y asíi poder unir los mangas online y los cómics offline en una sola app.
Saludos!

**Comment by raulhaag** [comment]
Hola @fbutte  si te referis a desde archivos por offline tenes la opcion en + ultimo en la lista se encuentra from folder que es para seleccionar un directorio
