### ISSUE TITLE
Migrar manga desde Tachiyomi hacia MiMangaNu

### ISSUE THREAD

**Issue by cvalenciaec** [raulhaag/MiMangaNu#684]
Possible?

**Comment by raulhaag** [comment]
no hoy script preparado ni nada y de hecho no conosco su ordenamiento y la estrutura de db que usan (si es en carpeta de app o dir publico) por lo que no y no pienso en el desarrollo ya que llevaria mucho tiempo por cada server que se tendria evaluar 1 a 1
