### ISSUE TITLE
Buttons at the top are invisible

### ISSUE THREAD

**Issue by onurtag** [raulhaag/MiMangaNu#69]
Buttons at the top are invisible on the current white background 
Images here: http://imgur.com/a/Mg038 
On the second image I took the screenshot while tapping the button

Also it would be nice if we could set a default orientation in the options menu "Portrait" or "Landscape" etc.

Thanks for this great app.

**Comment by raulhaag** [comment]
that error come from google appcompat-v7 22.0.0, i go to force the compilation whit the old (21.0.3) next version go to be fixed. 
about to the orientation go to be able son only on the reader and perhaps an option to mantein awake.
