### ISSUE TITLE
error en multiples servidores, en español

### ISSUE THREAD

**Issue by kallius** [raulhaag/MiMangaNu#690]
hola, yo de nuevo por acá les comento que no estoy seguro si desde la ultima actualizacion, que ya fue hace unos días, pero en lo particular me di cuenta que que hara unos 4 dias que si bien se actualizan los mangas y aparecen los nuevos, no se puede descargar, lance el diagnostico incluido en la aplicación y por lo menos me marco error en los principales servidores en español, tmo, heaven, esnine, kumanga tambien, entre otros que si bien no salen en rojo, si estan en amarillo.
espero que les sirva el aviso.
sin mas saludos ;) gracias por su trabajo

**Comment by raulhaag** [comment]
Hola te comento como funciona esa parte de la app 
ROJO: algún error de listar series / buscar / episodios / imagenes y estas ultimas tambien descagar.
Amarillo: Son advertencia sobre si usa path relativo o si algún valor sigue por defecto (pero sigue siendo 100% funcional).
Verde: server totalmente standarizado funcionando bien.
Pero la selecion de manga para probar es aleatorio asi que por ejemplo MangaHeaven y Kumanga pueden dar error ya que tienen bastante contenido caido. Ademas TMO esta en cambios continuos para evitar el uso de su pagina y esninemanga todabia no saque una version con el fix

**Comment by kallius** [comment]
a ok.. entonces a esperar, yo en lo particular uso esnine y claro como comentaba si se actualiza cuando hay nuevo capitulo, pero al momento de descargar da error, no es probado los demas, pero si algo me di cuenta de lo que comentas arriba de como hace la prueba. 
bueno eso gracias, Saludos ;)
