### ISSUE TITLE
Stop using other language than english

### ISSUE THREAD

**Issue by aelisya** [raulhaag/MiMangaNu#693]
i'm asking this because of that, we english or other language cannot see if a request is already done, because we can't check on it because of the language wall.

And using google translate to check on all issue is very VERY annoying

**Comment by raulhaag** [comment]
https://github.com/raulhaag/MiMangaNu/issues/1
if you read this you go to note that the app was originaly in spanish also some first configuration string still on spanish to no lose this, if you create any issue than already exist in other language i will not get mad, so go on.
