### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by marrokin** [raulhaag/MiMangaNu#694]
Seria bueno tener un grupo en discord donde podamos ver temas mas especificos y organizados con relacion al desarrollo de la apk, y agregar un boton que redirija hacia discord

**Comment by scese250** [comment]
Yo te digo que van a bombardear al desarrollador con preguntas y otras tonterías, mejor es la comunicación por este medio.

**Comment by raulhaag** [comment]
@marrokin creo que va a pasar exactamente lo que dice @scese250
