### ISSUE TITLE
Error al descargar mangas

### ISSUE THREAD

**Issue by AyumuMiyazaki** [raulhaag/MiMangaNu#695]
Hola, no sé si solo me pasa a mí, pero deshace hace como 3 días para acá no puedo descargar ningún capítulo de ningún manga por ningún servidor, los pongo a que descarguen, dice "en cola" (a pesar de que está solo ese capítulo descargando) y luego dice "error", otra cosa que ocurre es que quise abrir un nuevo capítulo de un manga alojado en tmo y solo me aparece que tiene una pág (que tampoco me descarga), ya probé haciendo una instalación limpia pero habiendo restaurado un backup que hice de los mangas que había guardado, y ya probé borrando el manga de mi lista y volviéndolo a agregar. Gracias!

**Comment by raulhaag** [comment]
Hola @AyumuMiyazaki  por lo visto solo a vos, seria bueno informacion del dispositivo/sistema, que revices el espacio y los permisos. que pruebes reiniciar desde el menu de la app y iniciar la descarga de algun otro servidor.
Por lo que comentas de en cola, en este estado se encuentra hasta que se inicializa la información del capítulo por lo que si no pasa de obtener el número de páginas y/o imagenes no pasa al estado descargando. Otra cosa TMO esta bastante inestable por los cambios asi que te recomendaria hacer las pruebas con otro servidor

**Comment by AyumuMiyazaki** [comment]
Bueno, siempre lo he usado desde una kindle hdx 2013 y no me había dado este tipo de problemas hasta ahora, el manga que no descarga está alojado en heavenmanga, trataré con otro servidor o si no, volveré a hacer una instalación limpia sin hacer backup de la lista que tengo!

**Comment by AyumuMiyazaki** [comment]
Update: hice lo que dijiste de probar con otros servidores, quitando el hecho de tmo y su inestabilidad, kumanga, para mangas en español, y kissmanga, para mangas en inglés, funcionan perfectamente, parece que heavenmanga está presentando problemas!

**Comment by Zaissei** [comment]
Buenas,
Yo también tengo el mismo problema que @AyumuMiyazaki. TMO actualiza los capítulos nuevos sin problemas, pero a la hora de descargar el capítulo, pone "0/1" donde va el número de páginas y no lo descarga.
En heaven manga, no carga la lista de mangas al querer añadir uno nuevo.

Mi dispositivo es un Xiaomi mi 8.
Saludos.

**Comment by raulhaag** [comment]
@AyumuMiyazaki heaven manga va a estar funcional nuevamente en la proxima versio

**Comment by AyumuMiyazaki** [comment]
Vale! Gracias!
