### ISSUE TITLE
No Buscar Actualizaciones // No Check for Updates

### ISSUE THREAD

**Issue by Zaissei** [raulhaag/MiMangaNu#696]
Buenas,

La opción de "**No Buscar Actualizaciones**" no funciona correctamente. A pesar de seleccionarla y marcar el **estado** de ese manga como **finalizado**, sigue incluyéndolo en la búsqueda de nuevos mangas. Incluso diría que al cabo de unos cuantos reinicios vuelve a poner el estado en "En Progreso", es decir que no te mantiene la opción. 

La opción de "**Incluir mangas finalizados**", la tengo **desactivada**.

He probado de activarla ( Incluir mangas finalizados ) y reiniciar ( forzar cierre y borrar de recientes, y también reinicio rápido ), desactivarla y volver a reiniciar, pero sigue igual.
También he probado de marcar como finalizado en diferentes fuentes ( TMO, ESNineManga, ... ), pero tampoco, los busca todos.

**Busco actualizaciones de mangas manualmente** (deslizando hacia abajo), no se si tendrá algo que ver.

Porque supongo que si marco un manga como finalizado ( No Buscar Actualizaciones ), tiene que salir reflejado en numero total que sale en la barra de notificaciones, no?. 

**Ejemplo**: Tengo 200 mangas y marco uno como finalizado, en la barra de notificaciones toca aparecer: "Buscando Nuevos Mangas 1/199" ?

**Mi dispositivo** es un Xiaomi Mi 8.

PD: Aunque no es necesario estaría bien una confirmación de actualizar cuando deslizas hacia abajo, ya que ha veces haciendo scroll rápido busco nuevos mangas sin querer 😆.

Un Saludo y gracias por tu trabajo.

_________________________________________________________________________________________________________

Translated by DeepL . . .

_________________________________________________________________________________________________________

Hi,

The "**Not Check for Updates**" option does not work properly. Despite selecting it and marking the **status** of that manga as **completed**, it still includes it in the search for new manga. I'd even say that after a few restarts it puts the status back to "In Progress", meaning that it doesn't keep the option. 

The option of "**Include completed mangas**", I have it "**deactivated**".

I have tried to activate it ( Include finished tasks ) and restart it ( force closing and deleting recent ones, and also quick restart ), deactivate it and restart it again, but it remains the same.
I have also tried to mark as finished in different sources ( TMO, ESNineManga, ... ), but not, all of them are searched.

**I look for manga updates manually** (Scroll Down), I don't know if it has something to do with it.

Because I suppose that if I mark a manga as finished ( No Check for Updates ), it has to be reflected in the total number that comes out in the notification bar, right? 

**Example**: I have 200 mangas and I mark one as finished, in the notification bar it appears: "Searching for New Mangas 1/199" ?

**My device** is a Xiaomi Mi 8.

PS: Although it's not necessary, it would be nice to get an update confirmation when you scroll down, since I've sometimes scrolled down to look for new mangas without wanting to 😆.

Greetings and thanks for your work.

**Comment by raulhaag** [comment]
listo para la próxima versión / ready for next version

**Comment by raulhaag** [comment]
acerca de pd se mas cuidadoso :-P

**Comment by Zaissei** [comment]
Okey, muchas gracias!! 
PD: Lo intentaré jajaj

Saludos

**Comment by Zaissei** [comment]
Perfecto con la última versión, gracias!

Saludos.
