### ISSUE TITLE
Imagen no encontrada 

### ISSUE THREAD

**Issue by Danielcastro502** [raulhaag/MiMangaNu#697]
Hola. Cuando intento leer un manga me sale esta imagen 
![Screenshot_20200114-212912](https://user-images.githubusercontent.com/57425209/72399880-77aeb280-3715-11ea-8d02-d2db699f298f.png)

**Comment by raulhaag** [comment]
reinicia la app en 5 min y reinicia el capitulo y  cuando haya errores en tmo usa el tema ya abierto
