### ISSUE TITLE
Unable to make any screenshot while using MiMangaNu 

### ISSUE THREAD

**Issue by MrSlowSheep** [raulhaag/MiMangaNu#698]
When I try to screenshot while having MiMangaNu opened I will just get a notification saying "Couldn't capture screenshot". 
If I try to record the screen the app will just be black.

Is this a bug or an intentional choice?
I downloaded MiMangaNu from F-Droid.

EDIT: I am using Xiaomi Mi Mix 2S, MIUI Global 11.0.4

**Comment by raulhaag** [comment]
Hi, that is intentional, the same function that hide the content on app windows, lock the screenshots, if you go to settings you can enable and disable this feature(second option).

**Comment by MrSlowSheep** [comment]
Ah I understand. Fixed, thank you!

Il giorno gio 16 gen 2020 alle ore 12:26 Raul <notifications@github.com> ha
scritto:

**Comment by MrSlowSheep** [comment]
Ah I understand. Fixed, thank you!
