### ISSUE TITLE
"New" on Latest Chaps. on MangaTown

### ISSUE THREAD

**Issue by Hae14** [raulhaag/MiMangaNu#700]
-the Word 'new' gets Added on the Title of the Latest Chapters..
it's Not Much of a Problem. Just Look at it when u have Time..
it Doesn't Happen to All.. i Guess it's Just Popping on the Newly Added Mangas on MangaTown.

**Comment by raulhaag** [comment]
ready for next version 👋

**Comment by Hae14** [comment]
ok,'-)
#thanks

**Comment by Hae14** [comment]
ok,'-)
#thanks
