### ISSUE TITLE
App skipping to last page when changing to new chapter

### ISSUE THREAD

**Issue by Melferas** [raulhaag/MiMangaNu#702]
When I'm reading and reach the last page of the current chapter, next time I swipe I change to the next chapter, but it's skipping to the last page of that new chapter instead of the first one, making me display the page bar to read from the beginning.

Continuous reader.
Left to right swiping.
Screen on.
Portrait mode locked.

Version is latest from FDroid 1.121.

**Comment by raulhaag** [comment]
hi @Melferas the continuous reader almost need ea complete rewrite and i don't have the time and concentration (really need many days only for this) to do it for the moment, sorry but it need to wait a time.

**Comment by Melferas** [comment]
Ah alright good to know, I'll just use the normal one meanwhile. Thanks.

**Comment by raulhaag** [comment]
i made not a complete rewrite, only a few improves for next version, please give a feedback after the release
