### ISSUE TITLE
No carga ninguna página de manga

### ISSUE THREAD

**Issue by Josking28** [raulhaag/MiMangaNu#703]
Llevo un par de horas queriendo buscar un manga pero ningún servidor me carga, ya busqué por el navegador para ver si era un problema de la página y cargó correctamente, solo puedo descargar capítulos de mangas que ya tengo agregados.

**Comment by Pompinchu** [comment]
x2 , lo volví a descargar después de 3 meses (abandone por el problema de TMO) y ahora no funciona ninguno 

Arreglen porfa
