### ISSUE TITLE
How can i help with Russian translation?

### ISSUE THREAD

**Issue by sprainbrains** [raulhaag/MiMangaNu#707]
I'm using this app no longer but i saw many strings without translation.
How can i help you with it?

**Comment by raulhaag** [comment]
Hi the easy way is using android studio translation tool and make a pull request https://developer.android.com/studio/write/translations-editor?hl=en#open
other way mora manually but not need to download nothing is go to here https://github.com/raulhaag/MiMangaNu/blob/master/app/src/main/res/values/strings.xml to see the full set of strings and make an edition here https://github.com/raulhaag/MiMangaNu/blob/master/app/src/main/res/values-ru/strings.xml editing on web browser and adding the missing strings from the first, but go to be a hard work,

**Comment by sprainbrains** [comment]
> Hi the easy way is using android studio translation tool and make a pull request https://developer.android.com/studio/write/translations-editor?hl=en#open
> other way mora manually but not need to download nothing is go to here https://github.com/raulhaag/MiMangaNu/blob/master/app/src/main/res/values/strings.xml to see the full set of strings and make an edition here https://github.com/raulhaag/MiMangaNu/blob/master/app/src/main/res/values-ru/strings.xml editing on web browser and adding the missing strings from the first, but go to be a hard work,

Thanks. Got it,

Why are you didn't use a collective translation service like **weblate**?

**Comment by borrougagnou** [comment]
Because it take a long time to translate all in 115 languages + some people use also Google Translate...
after if you want to go in this direction, also, good luck...

**Comment by raulhaag** [comment]
@sprainbrains only because all those thing take extra time

**Comment by sprainbrains** [comment]
> @sprainbrains only because all those thing take extra time

of course i understand it.



> Because it take a long time to translate all in 115 languages + some people use also Google Translate...
> after if you want to go in this direction, also, good luck...

I will try to do something in this direction...
The simples way is translate only one file.
