### ISSUE TITLE
Descarga de otro manga

### ISSUE THREAD

**Issue by Sotom98** [raulhaag/MiMangaNu#709]
Qué tal amigo, primero agradecerte por el trabajo que haces por nosotros... y pues, mencionarte que cuando descargo un capítulo de un manga, descarga el de otro manga. Me pasó con Murenase Shiiton Gakuen y otro más, cuando descargué su último capítulo, resultó ser el de otro muy diferente ¿Le ha pasado a alguien más?

**Comment by raulhaag** [comment]
errores de tmo tienen su hilo especial ahi subi un fix reinicia en 5 min y borra lo agregado con ese cambio en tmo y cualquier otro problema relacionado con el servidor por favor usa ese hilo para no generar mas issues del mismo tema
