### ISSUE TITLE
Downloading mint manga doesn't work

### ISSUE THREAD

**Issue by Zhbert** [raulhaag/MiMangaNu#716]
Recently, downloading manga from the mintmanga site has stopped working. When you click on a Chapter, it shows a spinning blue circle and that's it. The site itself is working in the browser, the problem is not in the network.

**Comment by raulhaag** [comment]
Hi @Zhbert  the fix is ready for next version since it use the same structure as readmanga.me
👋

**Comment by Malva29** [comment]
A mi las descargas tampoco me funciona

**Comment by Zhbert** [comment]
> Hi @Zhbert the fix is ready for next version since it use the same structure as readmanga.me

Thanks =)
