### ISSUE TITLE
Pasar mangas de a otro dispositivo

### ISSUE THREAD

**Issue by Danielcastro502** [raulhaag/MiMangaNu#717]
Hola bro. Cambiaré de dispositivo móvil y quiero pasar la app pero con todo los mangas e bovedas que tengo guardadas como le hago por que tengo demasiados para buscarlos 1 por 1, gracias

**Comment by raulhaag** [comment]
@Danielcastro502  solo ejecuta la opción respaldar preferencias del menú de configuración, copias la carpeta mimanganu al nuevo dispositivo y instala y ejecuta la app, dale los permisos y después en configuraciones restaurar preferencias
