### ISSUE TITLE
API Detectando mal la cantidad de paginas

### ISSUE THREAD

**Issue by xmithosx** [raulhaag/MiMangaNu#721]
Hola, primero que nada espero que tu y los tuyos estén bien en este confinamiento / cuarentena...

Desde ayer la aplicación me esta presentando un falla, entiendo que puede deberse a un problema en la API pero no lo tengo claro.

El problema en si es que se están cargando solo 4 paginas de cada capitulo.

**Comment by xmithosx** [comment]
Me esta pasando en Readmanga.today por cierto...

**Comment by raulhaag** [comment]
En realidad estamos con más trabajo que nunca, recien hoy despues de 3 semanas voy a tener un dia y medio libre, ahi esta arreglado para la proxima version

**Comment by xmithosx** [comment]
Pues si, te entiendo perfectamente, también soy del área y ha sido una locura... pues gracias ahora a esperar ese Release xD

**Comment by xmithosx** [comment]
Perfecto, ha sido solucionado.
