### ISSUE TITLE
bug busqueda de nuevos capitulos manualmente

### ISSUE THREAD

**Issue by J0TTAp** [raulhaag/MiMangaNu#728]
Hola, el caso, explicare con imagenes que es mas facil

### **1) Darle a buscar**

![Screenshot_20200422-102859](https://user-images.githubusercontent.com/57441600/80003524-c8f1df00-8486-11ea-89db-9453384d5c47.png)

### **2)Click en este mensaje**

![Screenshot_20200422-102909](https://user-images.githubusercontent.com/57441600/80003653-f3439c80-8486-11ea-92d3-43d99818e019.png)

**### 3) Mirar como se queda pillado, ya que no esta buscando, y no deja volver a buscar**

![Screenshot_20200422-102922](https://user-images.githubusercontent.com/57441600/80003739-0fdfd480-8487-11ea-981e-d7e5595234ca.png)

Para volver a buscar, tengo que cerrar la aplicacion y darle otra vez a buscar. es un poco molesto
Por si acaso dejo algunos datos extra:

version de mi manga nu: v1.128-github
Android: 8.1.0
Dispositivo: Honor 7s

Saludos, me encanta la aplicacion

**Comment by raulhaag** [comment]
Hola, cuando clickeas la notificacion esta se cierra hasta que no cambia el estado del progreso no se vuelve a abrir, pero sigue corriendo el proceso en el fondo, por eso no te deja volver a lanzarlo, tenes que esperar a que se termine (lo que tendria es que hacer es el bloqueo de la notificacion para evitar confuciones igual que cancelar tambien toma un tiempo hasta que se extingen los hilos ya lanzados)
