### ISSUE TITLE
Chapter duplication issue after updating

### ISSUE THREAD

**Issue by TheSniperFan** [raulhaag/MiMangaNu#73]
Hello.
I noticed that sometimes the chapters in a manga get duplicated.

I have a manga that had 78 chapters. After the 79th chapter was released, the list now has chapters 1-78, then all chapters again (1-79) marked as new.

Here's a screenshot of the issue:
![bug](https://cloud.githubusercontent.com/assets/9803861/8024188/ca90d650-0d2a-11e5-8884-933b1a6b6091.png)

**Comment by raulhaag** [comment]
Can you send me a copy of db file? The only explication could be the path changed because there are unique on dB no other idea

**Comment by TheSniperFan** [comment]
Sure. Where can I find this file?

**Comment by raulhaag** [comment]
Only if you divice is rooted in /data/data/ar.rulosoft.mimanganu

**Comment by TheSniperFan** [comment]
Here you go.
https://drive.google.com/open?id=0B5AHtBX-WDUFek5Wa2MtblJaTDA&authuser=0

**Comment by raulhaag** [comment]
![error](https://cloud.githubusercontent.com/assets/2048339/8026452/696bda92-0d4c-11e5-976d-1196cdd5e69a.jpg)
They change the paths (removing "1.html" at the end) nothing to do, or no good ideas from me, a few bads.

**Comment by TheSniperFan** [comment]
I see. I'll clear it by hand then. If it happens again, I'll think of a fix.
Thanks for looking into it.
