### ISSUE TITLE
Problema cuando marcas como leído o no leído//Bug when you mark as read or unread 

### ISSUE THREAD

**Issue by Zaissei** [raulhaag/MiMangaNu#731]
Buenas,
Desde las últimas actualizaciones, cuando marcó un capítulo o varios de un manga (manteniendo pulsado) y quiero hacer una de las siguientes cosas se cierra la app. 
-Marcar como leído
-Marcar selección como no leído
-Marcar selección como leído y borrar imágenes

En cambio si lo hago sin marcar ningún manga, marcar todo como leído y marcar todo como no leído funcionan correctamente. 

Además las opciones de borrar imágenes y Reiniciar no hacen nada.

Si puedes darle un vistazo.
Mi dispositivo es un Xiaomi mi 8

Gracias y un saludo.
_______________________________________________________
Translated by deepl
_______________________________________________________

Hi there,

Since the last updates, when you marked a chapter or several of a manga (by holding down) and want to do one of the following things the app is closed. 
 
-mark as read

-Mark selection as unread

-Mark selection as read and delete images

On the other hand, if I do it without marking any manga, marking everything as read and marking everything as unread works correctly. 

Also the options to delete images and Reset do nothing.

If you can take a look at it.
My device is a Xiaomi mi 8

Thank you and a greeting.

**Comment by raulhaag** [comment]
si tenes la ultima version deberia generaun archivo de log del error en el directorio de la app, si lo bsubis voy a poder tener mas informacion sobre el problema

**Comment by Zaissei** [comment]
Buenas,
Los he subido a una carpeta de Dropbox,
https://www.dropbox.com/sh/byq13whougtkitl/AABQVRwt7x8YgUu18-lj0oesa?dl=0

**Comment by Zaissei** [comment]
@raulhaag 
Arreglado, funciona perfectamente en la última versión. Gracias!
