### ISSUE TITLE
Error while trying to open database! in freshly installed application.

### ISSUE THREAD

**Issue by XaviFP** [raulhaag/MiMangaNu#736]
Mi Manga Nu version: 1.129 (installed from F-Droid)
Android version: 10

In a new installation after giving the application the storage permission it asks for, it displays the error message "Error while trying to open database!" at the bottom of the screen. 

https://github.com/raulhaag/MiMangaNu/blob/0a61fc57b68994887dcc7772b0a383fff5842da6/app/src/main/java/ar/rulosoft/mimanganu/componentes/Database.java#L138

And when going in into settings, I get the following exception:
 ```
java.lang.NullPointerException: Attempt to get length of null array
at ar.rulosoft.mimanganu.PreferencesFragment$calcStorage.doInBackground(PreferencesFragment.java:774)
at
ar.rulosoft.mimanganu.PreferencesFragment$calcStorage.doInBackground(PreferencesFragment.java:758)
at
```
https://github.com/raulhaag/MiMangaNu/blob/master/app/src/main/java/ar/rulosoft/mimanganu/PreferencesFragment.java#L773

These errors happen every time I reach the "main" view or the settings view.
Uninstalling and reinstalling yields the same behavior.

If there's more info needed I'll be glad to help as much as I can :-)

**Comment by raulhaag** [comment]
Hi, the fix is the same, only a really unnecesary android update of security (so secure that can be bypased adding a line to the manifest 🤦)  
Thanks for notify i didn't tested on Q

**Comment by XaviFP** [comment]
No worries! Thanks for your work, it's really appreciated :-)
