### ISSUE TITLE
The app stopped working since yesterday

### ISSUE THREAD

**Issue by Axggdamer** [raulhaag/MiMangaNu#739]
I was thinking about read some manga because I was bored but suddenly At the moment of download a simple chapter  nothing happened, It got stucked on the load screen.

This morning that I tried to download something  else, It was not working, then I tried of wipe all of the data which has something to do with the app and reinstall it.

Now the surprise is that the app cannot enter to the servers on the list (It also get stucked in the load screen with that circle spinning on the screen), firstly It was only KissManga and after 1 hour any of the servers works properly.

My phone is a leeco le 2 with android marshmallow.

I hope that I did not interrupt your activities.

**Comment by Memix1984** [comment]
I've had the exact same problem as well. Don't worry you aren't alone. Either way we'll just have to wait on the dev because I unfortunately did the same thing and deleted all my available Manga. So much regret.

**Comment by raulhaag** [comment]
Same device, anyupdates?

**Comment by Axggdamer** [comment]
I have installed and uninstalled the app too many times (because this the best app for manga regardless of this sudden bugs) and now the app seems to be good but the servers still the same, nothing is charging at all.

**Comment by raulhaag** [comment]
device, os, update, free space

**Comment by Axggdamer** [comment]
Sorry for the stupid explanation XDD, my device is a Leeco x526, android
Marshmellow 6.0.1 with EUI, an snapdragon 652, 12.81 gb avaible and the
last update of mimanganu (1.130)

**Comment by raulhaag** [comment]
@Axggdamer can you make any logcat?, did you try to check permission?

**Comment by Mtkmanjaro** [comment]
@raulhaag any update for Android 10 I have an error in the last build can't open the database, i send you a log

**Comment by Axggdamer** [comment]
> @Axggdamer can you make any logcat?, did you try to check permission?

This is my logcat
https://drive.google.com/file/d/1SDpXz-ydb2pY8NGtu0mT88dJZf-yIySz/view?usp=drivesdk

**Comment by raulhaag** [comment]
@Mtkmanjaro for android 10 is ready on next update

**Comment by raulhaag** [comment]
@Axggdamer seen like you don't give to the app the permission or any app lock them for the db or dir

**Comment by Mtkmanjaro** [comment]
@raulhaag thanks mate, i really appreciate your hard work,

**Comment by Axggdamer** [comment]
> @Axggdamer seen like you don't give to the app the permission or any app lock them for the db or dir

Sorry for not responding the thread recently but... what permission are you refering to? english is not my first language and sometimes I do not understand the technicial language plus I could not find anything about what you said.

**Comment by Furanbelius** [comment]
from google translate
I do not know if it is related, but for some days the update of the search for new chapters has been really slow, it takes hours to complete. Most of my list is from kissmanga, a couple of weeks ago this did not work and was fixed in the latest version; Is kissmanga very difficult to work with? Should I use other servers?
I have the error on a tablet with android 8.0.

**Comment by raulhaag** [comment]
check last update

**Comment by Furanbelius** [comment]
> check last update
Works for me, thxs!

**Comment by Axggdamer** [comment]
Now even the app download the chapters properly, muhas gracias :D, I had changed the app until you could fix something but It was not the same experience, Let me close the thread
