### ISSUE TITLE
the app crash in the version 1.27 

### ISSUE THREAD

**Issue by xken2x** [raulhaag/MiMangaNu#75]
The app crash in the moment than i open it, and i cant come back to the versión 1.26, this problem is of 3 days ago, i havent the root permisions and cant copy the db archive of the app, help!

Extra:
I have a long list of manga in spanish and english and i cant lose it!!!

**Comment by raulhaag** [comment]
info of device and os version? to thiks don't need db.
if you can use any logcat tool and filtrate (using mimanganu) the error message go to be usefull to find the problem?

**Comment by xken2x** [comment]
the information is:
ilium pad e10si
intel atom x86
android 4.2.2
1gb of ram
8 gb of storage
ps:
the problem only pass in the version 1.27 and i aprecciate if you can launche the version 1.28 with the correction of the bug in submanga

**Comment by xken2x** [comment]
the programs to do log of the system need root and the tablet cant be rooted of no way

**Comment by raulhaag** [comment]
try it http://android.stackexchange.com/a/208
i use an x86 tablet and work ok.

**Comment by xken2x** [comment]
by the way, when will be new version?

**Comment by xken2x** [comment]
I/ActivityManager(  443): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=ar.rulosoft.mimanganu/.ActivityMisMangas} from pid 11157
I/ActivityManager(  443): Start proc ar.rulosoft.mimanganu for activity ar.rulosoft.mimanganu/.ActivityMisMangas: pid=12662 uid=10129 gids={50129, 3003, 1015, 1023, 1028}
E/AndroidRuntime(12662): 	at ar.rulosoft.mimanganu.componentes.Database.getMangasFromCursor(Database.java:210)
E/AndroidRuntime(12662): 	at ar.rulosoft.mimanganu.componentes.Database.getMangasCondotion(Database.java:191)
E/AndroidRuntime(12662): 	at ar.rulosoft.mimanganu.componentes.Database.getMangas(Database.java:183)
E/AndroidRuntime(12662): 	at ar.rulosoft.mimanganu.FragmentMisMangas.cargarMangas(FragmentMisMangas.java:142)
E/AndroidRuntime(12662): 	at ar.rulosoft.mimanganu.FragmentMisMangas.onResume(FragmentMisMangas.java:130)
W/ActivityManager(  443):   Force finishing activity ar.rulosoft.mimanganu/.ActivityMisMangas
W/ActivityManager(  443): Activity pause timeout for ActivityRecord{21399f00 u0 ar.rulosoft.mimanganu/.ActivityMisMangas}
I/WindowState(  443): WIN DEATH: Window{213f9e18 u0 ar.rulosoft.mimanganu/ar.rulosoft.mimanganu.ActivityMisMangas}
I/ActivityManager(  443): Process ar.rulosoft.mimanganu (pid 12662) has died.



this is the output of the logcat

pd:
how i can save the list of mangas in the app???

**Comment by Dostoi** [comment]
The next version will be in two days I guess if F-Droid is as long as usual

For saving the list of manga see #65

**Comment by raulhaag** [comment]
whiout root you can try this http://stackoverflow.com/a/17177091 (use as packege name ar.rulosoft.mimanganu)
about the error look like can't acces to the database or create the query (perhaps disk full, an error  reading or skip same updates) try to free space on internal memory (not the sd card)

**Comment by xken2x** [comment]
run-as: Package 'ar.rulosoft.mimanganu' is not debuggable

this is the error that the console returns now

**Comment by xken2x** [comment]
y have 400mb of free space in the internal storage, this cannot be the problem
