### ISSUE TITLE
Every 50th chapter on Mangahere is missing

### ISSUE THREAD

**Issue by manokara** [raulhaag/MiMangaNu#78]
I checked if that happened on more than one manga, and it did. Chapter 50, 100, 150, ... of any manga (on Mangahere) does not show up on the list. Deleting and adding again does not solve the problem. I checked in their site and it was there, so the problem is definitely in the app side.

I wonder if that's just me, though, for whatever reason. Thanks for this app, it's small and functional :)

**Comment by manokara** [comment]
Oh btw, I'm using version 1.27 from FDroid. Can't tell if current revision has that already fixed, will try to build it tomorrow.

**Comment by Dostoi** [comment]
I tried one randomly too and I'm having the same issue

**Comment by raulhaag** [comment]
fixed

**Comment by manokara** [comment]
It's still the same here... Did it work for you, @Dostoi?

**Comment by raulhaag** [comment]
in the next version 1.29, current 1.28 was pushed the same day that you present the issue

**Comment by manokara** [comment]
Oh, I see, my bad. Thanks :)

**Comment by raulhaag** [comment]
working now??

**Comment by manokara** [comment]
Yes, perfect. I just was expecting the missing chapters to be ordered alphabetically but, that's asking too much, hehe. Nothing that a little rearranging in the DB can't solve, if there were working root methods for my phone...

Thanks again :)
