### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by manokara** [raulhaag/MiMangaNu#80]
It would be nice if the app had a service checking for new chapters. Actually, it's a must-have :P Then in the settings you could choose to check every day, every 2 days, week, etc.

**Comment by Dostoi** [comment]
:+1:

**Comment by raulhaag** [comment]
looking for the best way to do this i found an option to a running service all the time, go to see if i can make that work ;-)

**Comment by raulhaag** [comment]
almost ready, testing whitout problem and without and service running all the time, i can say if averithing go good this weekend i send the last version to publish :-D

**Comment by manokara** [comment]
Great! :D

**Comment by raulhaag** [comment]
just push, in one o two days check it
