### ISSUE TITLE
Adding small explanation for the lock screen sleep and lock rotation

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#81]
it would be more user friendly if you could add a small text when you press those button to explain to the new user what he's doing and maybe add those option in the option menu

**Comment by raulhaag** [comment]
ok i will leave you a few string to translate then :-P

**Comment by Dostoi** [comment]
Thanks ^^
And there's one missing already, for the UI Settings, it's not in the file

**Comment by raulhaag** [comment]
added to the next version, can you translate the lastest strings?
https://github.com/raulhaag/MiMangaNu/blob/master/app/src/main/res/values-fr/strings.xml

**Comment by Dostoi** [comment]
I was on holiday, I couldn't translate it earlier. I'm on it now :)
