### ISSUE TITLE
Pages missing from download

### ISSUE THREAD

**Issue by dar5hak** [raulhaag/MiMangaNu#82]
Hi, I'm using version 1.29. I downloaded two chapters for later reading, and the status showed "Downloaded", but some pages were missing from the download. I even checked the file manager. They were not downloaded at all.

While reading these chapters, the app tried to load them from the server.

This happened for:
- page 10 in Naruto Gaiden 9
- pages 10 and 11 in Fairy Tail 442

both from MangaPanda.

Could you have a look?

**Comment by raulhaag** [comment]
Just go to settings and set the error tolerance to 0 and them  restart and download again and on this error the app go to stop download

**Comment by dar5hak** [comment]
I set the error tolerance to 1, which is minimum. The missing-page problem has reduced, but still happens occasionally.

**Comment by xken2x** [comment]
please, close the thread if the problem been solved
