### ISSUE TITLE
Auto update only when the wifi is on

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#86]
Is it possible to add an option to auto update only when the wifi is on ?

**Comment by raulhaag** [comment]
possible not in short term, adding extra permision, etc

**Comment by Dostoi** [comment]
Ok no problem

**Comment by Zykino** [comment]
Yeah it could be good to have this option. At if auto-update will occur with no internet connection wait until internet is enabled. (Waiting for WiFi is even better of course)

**Comment by xtj-9182** [comment]
> possible not in short term, adding extra permision, etc

so I implemented this and I needed the ACCESS_NETWORK_STATE permission however this is a normal permission on Android 6 so it requires no user interaction and on lower android versions it shouldn't hurt I think.
