### ISSUE TITLE
Manga Source

### ISSUE THREAD

**Issue by Sheiko222** [raulhaag/MiMangaNu#89]
Since StarKana is dead, you can use mangareader.net or mangaeden.com. It's only a suggestion.

**Comment by Johndeep** [comment]
Not only StarKana is dead, it seems that KissManga currently has a different IP than hardcoded in the source, so MiMangaNu can't find the site anymore (for now at least).

This made me think if you could at least separate all the manga sources, which is apparently "hardcoded" into the app, out to scripts, like lua, scheme or whatever comes in mind for being easy but powerful. It would make the sources much more flexible, if manga sources or the websites changes their adress or even API.

It would be awesome and practical, if there is a way to select or deselect the sources. Because there are sources, not everyone likes (because i.e. quality) or can use (i.e. can't read english or spanish).

**Comment by Johndeep** [comment]
By the way, is there a reason why only KissManga seems to have a fixed IP address written into the source? I mean, all the other sources seems to "get" the source rather than "post"ing it..

**Comment by raulhaag** [comment]
Because they kick you if dont you use a browser using cloudflare, etc

**Comment by Johndeep** [comment]
Hmm, that's unfortunate.. so that's the reason for cloudflare Error 1003, meh..
By the way, is there a chance to have bato.to in the source list? Would be nice..

**Comment by Sheiko222** [comment]
I noticed KissManga's problem,I thought it was a temporary problem.

**Comment by raulhaag** [comment]
fixed kissmanga on next version, advice me when english sources are bad because i don´t use them, about bato.to is to irregular, mangareader.net only list for now on next version ready i go to post the fixes and add this night

**Comment by Johndeep** [comment]
Thank you for fixing kissmanga, still have stuffs to read on that source. ^^"
As this is still about manga source, mind to add a german source, in this case <b>wiemanga.com</b>, it also has the cloudflare thing like kissmanga by the way.

Well, about the advice, all the current English sources (except StarKana) are good enough, some just make bold shrinking or watermarking, which isn't that bad (still bugs you sometimes, if you're aware of it). Therefore the suggestion about an optional switch off of some sources.

Can you tell me, how bato.to is irregular? Maybe I could generally help out by coding and do some pushes, only if you don't mind.

**Comment by beepFTW** [comment]
I think for the reason that it is an International source? Like It shows all languages instead of just one. Some just add an option to filter Batoto chapter languages in their settings. This goes without saying that I would LOVE to see Batoto supported, it is definitely my favorite source.

**Comment by Johndeep** [comment]
Is that so? Well okay then, I though about something like bato.to changes their html structures and requests (like search function) often, so you have to keep up with updates in the server java files.

**Comment by Sheiko222** [comment]
Gracias y intentaré mantenerte en tanto con los ingleses.

**Comment by Johndeep** [comment]
Once again I'm asking, why KissManga has a fixed IP, whereas you can just use the normal URL of it.
To just test this, can someone please verify this code snippet for me in <i>KissManga.java</i>?

Instead of

    String source = nav.post(IP, "/Search/Manga", HOST);

Use this

    nav.addHeader( "User-Agent", "Mozilla/4.0 (compatible; MSIE 5.5; Windows NT)" );
    String source = nav.post( HOST + "/Search/Manga" );

This will add the necessary header (well, any valid User-Agent would work) for passing by the 403 Error of any cloudflare. With this, we wouldn't need any fixed IP anymore.

**Comment by Johndeep** [comment]
I now have an improved KissManga.java, which now works without IP and the search function even works properly now.

For the IP issue, Navegador already provides the necessary methods to POST and bypass cloudflare server properly, just like any browser, only HOST is needed, no IP at all.

For the search function, problem was, if a search term results in only one single result, the app thinks there is no result at all! I made use of the AdvanceSearch, so now it can search properly, even if the term results only in one single entry.

Second issue of search function, if you type more than one word for searching, the result will always be empty. I fixed it by removing the UTF-8 encoding, whose idea was it in the first place to encode the term at all?

So, how can I contribute this piece of code?

**Comment by raulhaag** [comment]
when i was coding this kissmanga was using cloudflare whit a browser verificator normally used for "DOS" atacks now cloudflare are workink as a cache and proxy. if you want contribute, i'm happy because every help is usefull when don´t have a lot of time and realy like other people enjoy my app.

**Comment by raulhaag** [comment]
just realized i dont pull the last update :-P i don't remenmber why

**Comment by Johndeep** [comment]
Yeah, in short, I just set a User-Agent header, so cloudflare let you stay.
I want to contribute, but I don't quite see how.. maybe I try the fork thingy of github, since it's my first time using github.

**Comment by Johndeep** [comment]
I see, so mangapanda and mangareader is almost exactly the same in structure, I can remove StarKana and add mangareader.net instead, stay put!

I will release a pull request, after I made my improvements.
