### ISSUE TITLE
The settings, meaning and structure

### ISSUE THREAD

**Issue by Johndeep** [raulhaag/MiMangaNu#94]
During my attempt to improve the settings (like setting the summary and default index etc,), I came across "Maximum number of errors" and "Number of entries".

I think "Number of entries" is for the trying of one single Image out of a chapter, right?
But then, what is "Maximum number of errors" for?

**Comment by raulhaag** [comment]
Maximum number  of errors to stop the download is per chapter,  typo error
retries number

**Comment by raulhaag** [comment]
Retries is for an image

**Comment by Johndeep** [comment]
Do you mind, if I restructure the settings (so that it becomes a bit more clear) and make a separate changelog file?

**Comment by Johndeep** [comment]
By the way, what is the minimum Android API Version?

**Comment by raulhaag** [comment]
minimum api was honeycomb but they aren´t a lot of devices with this (in others words ice cream will be), about settings and changelog do it, i go to do same changes in other part of the source.

**Comment by Johndeep** [comment]
So in other words, api level 14.
About the settings, now I have the pull request, you'll see, how I solve the stuff, I'll close this issue after everything is okay.

**Comment by Johndeep** [comment]
So in other words, api level 14.
By the way, do you allow me to replace the color picker with a simple colorlist or seekbar rgb config?
The reason for this is, the colorpicker library is confusing, I can't set a reasonable defaultvalue (see code). Also it would make colorpicking simpler and cleaner to maintain.

**Comment by Johndeep** [comment]
Well, okay, many stuff happened, settings are okay, meaning is much clearer now. But there are always improvements to do.
