### ISSUE TITLE
About LazyList, part 2

### ISSUE THREAD

**Issue by Johndeep** [raulhaag/MiMangaNu#97]
It is really annoying that LazyList always creates a folder in the main storage..

Is there a way to store the lazy loaded picture into the main system temp folder like any other programs, something more common like into "android/data/<mimanganu_name>/cache" or "DCIM/.thumbnails"? Something more hidden, which is maybe cleanable by cache cleaner of other programs?

Consider to change to something like "https://github.com/nostra13/Android-Universal-Image-Loader" or "https://code.google.com/p/android-query/wiki/ImageLoading" or just modify LazyList?

**Comment by Johndeep** [comment]
Na nevermind, I try to figure this out myself.

**Comment by Johndeep** [comment]
Also, please consider this:
https://dzone.com/articles/be-lazy-productive-android-0

**Comment by raulhaag** [comment]
the libraries like not in maven was modified, to do especific things, other ways i try to use the android "volley" and the speed is really bad, lazylist is easy to modify clean to read and there are changes to work with ip, etc
the cache can be changed to mimanganufolder/cache, or appfolder/cache

**Comment by raulhaag** [comment]
check last commit

**Comment by Johndeep** [comment]
Great, I'll close this for now, because it solves _this_ issue, maybe I'll push a patch, where lazylist will create one database file instead of spamming many little images.

**Comment by Johndeep** [comment]
Now another thing about LazyList, specifically about the ImageLoader, the decodeFile() method.
Why is it modified from the original LazyList? What purpose does this has?

**Comment by raulhaag** [comment]
do you refer to the image scale?

**Comment by Johndeep** [comment]
yeah, in the lazylist from thest1 https://github.com/thest1/LazyList/blob/master/src/com/fedorvlasov/lazylist/ImageLoader.java#L89, it seems to scale, do we not need it?

**Comment by raulhaag** [comment]
we need to add parameter to know the sizes (pixel on screen on representation) if th image is greater transform it, other case no, it can improbe the performance but on todo list for the moment

**Comment by Johndeep** [comment]
Hmm, I want to know why, because it's better to save the pictures in a sql database.
During the download you can already scale them in the correct size and store them with the necessary information, and if you retrieve them, just get them.

It seems, you only need them for the Details and for the Overview, so what are the fixed size of them?

**Comment by raulhaag** [comment]
not a good idea save in db beacuse the db is actually stored in internal memory.

**Comment by Johndeep** [comment]
Well, that is an easy problem, I already solve this problem and save the database directly into the manga folder.
So, again, where is the maximum size stored?

**Comment by Johndeep** [comment]
Well, someday this will be solved, but for now.. closed.
